### ISSUE TITLE
iOS 一直显示“JPush ERROR 配置文件不存在”

### ISSUE THREAD

**Issue by todayliu** [jpush/jpush-phonegap-plugin#105]
完全按安装方式 cordova 在线安装，提示：
2015-12-21 11:40:18.284 Saler[998:325759] JPushLog: 
 ---------------------Jpush(IOS8Version) log----------------------
 --------------------Jpush SDK Version:1.8.8---------------------
2015-12-21 11:40:18.314 Saler[998:325829] JPushLog ERROR: JPush ERROR
配置文件不存在。
（有关配置文件的说明请参考开发文档“SDK集成步骤”第5条。http://docs.jpush.cn/pages/viewpage.action?pageId=2621727
在Resources目录中，有PushConfig.plist文件。
cordova版本：5.4.1
ios platform :  3.9.2
xcode          :7.1
在Buid phases->copy bundle resources中也存在pushConfig.plist文件

**Comment by darkterrorooo** [comment]
最新SDK 可以直接填写APP_KEY，具体地：
在你的ios 工程中的 JPushPlugin.m ----》 setLaunchOptions 函数 ----》JM_APP_KEY 替换为你的 APP_KEY
