### ISSUE TITLE
ionic 环境下找不到window.plugins

### ISSUE THREAD

**Issue by guzenyin** [jpush/jpush-phonegap-plugin#106]
你好，
    我在ionic的环境下，使用jpush 插件时，调用window.plugins.jPushPlugin.init()，window.plugins提示为undefined,请问这大概是什么问题？ 

   非诚感谢！

**Comment by AbelYangGitHub** [comment]
写到$ionicPlatform.ready(function () {})中就行了

**Comment by guzenyin** [comment]
已经解决，非常感谢你的这个插件，给我们非常大。

**Comment by AbelYangGitHub** [comment]
我不是这个插件的开发者
感谢开发者，希望能持续更新到android和ios的JPush最新版，谢谢
