### ISSUE TITLE
js api Cannot read property 'jPushPlugin'

### ISSUE THREAD

**Issue by yeesuu** [jpush/jpush-phonegap-plugin#108]
```html
<script type="text/javascript" src="cordova.js"></script>
	 <script type="text/javascript" src="cordova_plugin.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
        <script type="text/javascript">
            app.initialize();
            window.plugins.jPushPlugin.init(); //line:42
            window.plugins.jPushPlugin.getRegistrationID(onGetRegistradionID);
            var onGetRegistradionID = function(data) {
                try{
                    console.log("JPushPlugin:registrationID is "+data)      }
                catch(exception){
                    console.log(exception);
                }
            }
            window.plugins.jPushPlugin.setAlias('renkun');
        </script>
```

Uncaught TypeError: Cannot read property 'jPushPlugin' of undefined at file:///android_asset/www/index.html:42

please help me,thank you!

**Comment by darkterrorooo** [comment]
这些情况下是插件没被正确初始化。就我所知道的原因有可能有多种，可以尝试以下方法
1， 重新安装下插件。
2，查看 jPushPlugin.js 中，开头的 cordova.define(xxx)是否包一两层。
如果还有问题，加我QQ 597326493

**Comment by hennychen** [comment]
我还是会报出这个  Uncaught TypeError: Cannot read property 'jPushPlugin' of undefined
请问按照你的描述我尝试了，还是会有

**Comment by lhw5123** [comment]
@hennychen 你好，有试过用下面这句命令来安装插件吗？
cordova plugin add jpush-phonegap-plugin --variable API_KEY=your_jpush_appkey

**Comment by hennychen** [comment]
@lhw5123 我是用的ionic  cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=e8ba354b4d7129d9637b11d8
Fetching plugin "https://github.com/jpush/jpush-phonegap-plugin.git" via git clone
Repository "https://github.com/jpush/jpush-phonegap-plugin.git" checked out to git ref "master".

我不知道问题到底出在哪了，大家可以用ionic试试

**Comment by lhw5123** [comment]
@hennychen 如果插件正确安装了的话，那就应该是在初始化完成之前就调用了 jPushPlugin 中的方法，可以试下下面这样，等到设备准备完成后，再调用插件的方法。: )

     <script type="text/javascript">
      document.addEventListener("deviceready", function() {
        window.plugins.jPushPlugin.init();
      }, false);
    </script>

**Comment by hennychen** [comment]
@lhw5123 
按照上面你说的，在极光推送的后台发推送消息会出现以下提示：
没有满足条件的推送目标
如果是群发：则此应用还没有一个客户端用户注册。请检查 SDK 集成是否正常。
如果是推送给某别名或者标签：则此别名或者标签还没有在任何客户端SDK提交设置成功。
如果是根据 Registration ID 推送：则此 Registration ID 不存在。

**Comment by lhw5123** [comment]
@hennychen AndroidManifest.xml 中的 JPUSH_APPKEY 是和控制台中应用一致的吗？
