### ISSUE TITLE
JPushLog ERROR: JPush ERROR APP_KEY不能为空。

### ISSUE THREAD

**Issue by qifanrui** [jpush/jpush-phonegap-plugin#109]
参照文档设置的api_key="myappkey"或api_key=myappkey都试了,运行时报APP_KEY不能为空的错误

**Comment by darkterrorooo** [comment]
APP_KEY，注意大小写

**Comment by darkterrorooo** [comment]
--variable API_KEY=xxx
你是否少了 --variable ？
