### ISSUE TITLE
设置别名时返回错误码6003

### ISSUE THREAD

**Issue by newhzh** [jpush/jpush-phonegap-plugin#110]
调用window.plugins.jPushPlugin.setAlias()进行别名设置时，别名内容是个id号：46，但是返回错误码6003。
看了api说明： |6003| alias| 字符串不合法 有效的别名、标签组成：字母（区分大小写）、数字、下划线、汉字。
貌似数字组合应该是可以用的，不懂了。。。。烦请指教一下

**Comment by shx1545** [comment]
请问下你是如何解决的？是什么原因呢

**Comment by DASSDAO** [comment]
6004是什么错误，错误码api说明哪里可以找到呢
