### ISSUE TITLE
No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

### ISSUE THREAD

**Issue by willnewii** [jpush/jpush-phonegap-plugin#111]
把platform ios升级到4.0 就出现了这个问题.    https://github.com/shazron/KeychainPlugin/issues/21

**Comment by darkterrorooo** [comment]
你说的这个版本是指什么版本？

ps:  我用的cordova 是5.4.0 ,   xcode 版本7.2 。  ios SDK 9.2

**Comment by willnewii** [comment]
不好意思是我没说清.  cordova 是5.4.0 , xcode 版本7.2 。 ios SDK 9.2  这些都一样. 我说的是cordova-ios的版本号. 发的链接是类似的问题.  应该是cordova-iOS升级到4.0.X,移除了一些东西造成的吧.

**Comment by darkterrorooo** [comment]
好，我看一下是什么问题

**Comment by darkterrorooo** [comment]
@willnewii  Cordova iOS 是一个专为 Ios 平台的 cordova ，是 cordova 的一个分支？

**Comment by darkterrorooo** [comment]
@willnewii 能否加Q 597326493 交流下？
