### ISSUE TITLE
插件是否支持android x86 设备?

### ISSUE THREAD

**Issue by hayden621** [jpush/jpush-phonegap-plugin#117]
在插件 android 档案里没有 x86。想问插件是否支持android x86 的设备?

**Comment by lhw5123** [comment]
可以在项目的 libs 目录下，自己创建一个名为 x86 的文件夹，在里面添加 libjpush.so 文件，这样就能支持 android x86 设备了。
![1d9926ef-83dd-4ebf-a826-73e3df319bba](https://cloud.githubusercontent.com/assets/6531354/13593987/8f4d5a7a-e53b-11e5-8fb3-44a025020d95.png)
