### ISSUE TITLE
"检测到集成SDK未添加统计代码"

### ISSUE THREAD

**Issue by Alplob** [jpush/jpush-phonegap-plugin#118]
Hello,

I have installed this plugin this morning and it seems working well. Nevertheless, the following notification is shown sometimes in the status bar:

PUSH提示：缺少统计代码
检测到集成SDK未添加统计代码。点击查看

What should I do ?

Thanks!

**Comment by cnryb** [comment]
#80 跟这个一样的问题

**Comment by Alplob** [comment]
Thanks!
