### ISSUE TITLE
无法在ios8.x中获取到RegistrationID

### ISSUE THREAD

**Issue by cnryb** [jpush/jpush-phonegap-plugin#121]
使用代码中的例子代码无法在8.x ios中获取到RegistrationID  

已测试无法获取到RegistrationID的版本
8.3     12F70
8.3     12F69
8.0     12A365

测试两台9.x的正常，没有测试更低版本。

**Comment by Yasashi** [comment]
@cnryb  你好 getRegistrationID 在 native 的方法，跟 iOS 系统的版本关系不大。应该是你获取不到RegistrationID 的手机的配置不正确：appkey、发布/开发环境、证书、描述文件等。如果重新配置之后还存在该问题可以进入 gitter im https://gitter.im/ 我再帮你查找具体原因 ^_^

**Comment by cjj871030** [comment]
我也遇到ios8.4版本注册不了，但是在ios9.3上可以注册。。求解。。

**Comment by Yasashi** [comment]
@cjj871030 你好，请参照上面的回答重新进行相关配置，如果仍然存在该问题，请进入 gitter https://gitter.im/jpush/jpush-phonegap-plugin

**Comment by cjj871030** [comment]
齿轮出问题导致ios8无法注册，现已解决。。这个问题可以关闭了呀~
