### ISSUE TITLE
ios 9.2里面屏幕锁屏能收到通知打开就收不到了

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#124]
ios 9.2里面屏幕锁屏能收到通知打开就收不到了？发现ios里面的问题比较多啊

**Comment by xgzl87** [comment]
cordova软件打开就收不通知消息了，jpush.receiveNotification也会执行，但是顶部通知栏没有消息提示

**Comment by Yasashi** [comment]
你好，iOS APNs 通知是系统自带的。 App 在前台时，通知是不展示的。 这是无法改变的。但如果你有需要，可以兼听jpush.receiveNotification获取到通知的内容。

**Comment by xgzl87** [comment]
好的，谢谢！
