### ISSUE TITLE
LED flash when receiving notification

### ISSUE THREAD

**Issue by Alplob** [jpush/jpush-phonegap-plugin#125]
Hello,

Thanks a lot for this great plugin, it works well. Nevertheless, I would like to know how to make Android phone's LED flash when receiving notifications?

Thanks!

**Comment by lhw5123** [comment]
Hi,
You could see this [http://community.jpush.cn/t/topic/257](请问如何设置当接收到推送消息时呼吸灯闪烁).
^ ^

**Comment by Alplob** [comment]
Hello,

Thanks a lot for your prompt answer. I added **builder.notificationDefaults = Notification.DEFAULT_LIGHTS; ** in JPushPlugin.java (around line 422) but I could not build anymore

Function setBasicPushNotificationBuilder:

        void setBasicPushNotificationBuilder(JSONArray data,
            CallbackContext callbackContext) {
        BasicPushNotificationBuilder builder = new BasicPushNotificationBuilder(
                this.cordova.getActivity());
        builder.developerArg0 = "Basic builder 1";

        builder.statusBarDrawable = R.drawable.jpush_notification_icon;
        builder.notificationFlags = Notification.FLAG_AUTO_CANCEL;  //设置为自动消失
        builder.notificationDefaults = Notification.DEFAULT_SOUND ｜ Notification.DEFAULT_VIBRATE | Notification.DEFAULT_LIGHTS;  // 设置为铃声与震动都要
        
        JPushInterface.setPushNotificationBuilder(1, builder);
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", 1);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        //callbackContext.success(obj);
    }

Error message I get when I build:
> :compileDebugJava
/Applications/XAMPP/xamppfiles/htdocs/mobile_ebm/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:422: error: cannot find symbol

> builder.notificationDefaults = Notification.DEFAULT_LIGHTS;
                                       ^

>  symbol:   variable Notification
  location: class JPushPlugin

**Comment by lhw5123** [comment]
@Alplob 
Hi, Did you import " import android.app.Notification; " ?    ：）

**Comment by Alplob** [comment]
Thanks a lot for your prompt feedback, I can build again but the LED still does not flash when receiving a notification

**Comment by lhw5123** [comment]
I think you could add this code "builder.notificationFlags = Notification.FLAG_SHOW_LIGHTS;"
And this function should be called after "window.plugins.jPushPlugin.init();". Like this: 
![08b136c3-d808-4c18-bc92-8615ab0b4d23](https://cloud.githubusercontent.com/assets/6531354/13732917/7e767cd8-e9c6-11e5-8db0-8d492a2a7474.png)  : )

**Comment by Alplob** [comment]
Thanks @lhw5123 for your support but unfortunately I still could not get the LED flash.

Here is my code:

        <script type='text/javascript'>
            document.addEventListener('deviceready', function(){
                window.plugins.jPushPlugin.init();
                window.plugins.jPushPlugin.getRegistrationID();
                window.plugins.jPushPlugin.setBasicPushNotificationBuilder();
                window.plugins.setDebugMode(true);
            },true);
        </script>

And in JPushPlugin.java
```
void setBasicPushNotificationBuilder(JSONArray data,
        CallbackContext callbackContext) {
        BasicPushNotificationBuilder builder = new BasicPushNotificationBuilder(cordovaActivity);
        builder.developerArg0 = "Basic builder 1";
        builder.statusBarDrawable = R.drawable.jpush_notification_icon;
        builder.notificationFlags = Notification.FLAG_SHOW_LIGHTS;
        builder.notificationDefaults = Notification.DEFAULT_LIGHTS;

        
        JPushInterface.setPushNotificationBuilder(1, builder);
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", 1);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        //callbackContext.success(obj);
    }
```

**Comment by lhw5123** [comment]
Did you set builder id = 1 when you sending notification    : )
![5e1b9772-66cb-4bd5-ac78-48e3ce406afa](https://cloud.githubusercontent.com/assets/6531354/13736534/3e6abda0-e9f0-11e5-8399-b39a2945b6f4.png)

**Comment by Alplob** [comment]
Thanks, I did not know that point, but it still does not work...
I feel it is a bit complex to get the LED flash when receiving a notification, however every popular mobile application that I know have it. In addition, I think that most of users of this plugin would be interested to get it in their application. So I suggest that LED flash get included in the defaults settings of this plugin. Thanks! :smiley:

**Comment by lhw5123** [comment]
@Alplob  Thanks for your suggestion.
We will consider your suggestion. ^_^
You can contact me via QQ(328066446) or email(liuhw@jpush.cn), 
let me help u to solve this problem completely.

**Comment by Alplob** [comment]
Hello,

I would like to know if there is any change planned for this? My customers asked me why my app is the only one they have whose push notifications does not have any LED flash..

Thanks!

**Comment by lhw5123** [comment]
Our PM said the feature would be added, but is lower priority. Sorry, if there is any change, I will inform you.

**Comment by Alplob** [comment]
Hello, do you have any news about this feature ? 😃 

It looks still not available in the latest release.

Thanks!

**Comment by Alplob** [comment]
Just to be clear, here is below a picture of the LED I am talking about (I am **NOT** talking about the LED that flashes when taking picture).
![qrjhl](https://cloud.githubusercontent.com/assets/7520095/21077225/7035eb6a-bf7f-11e6-968d-5dd4fc29843a.jpg)

**Comment by Alplob** [comment]
Up!
