### ISSUE TITLE
在android中当应用程序在后台运行时，可以收到推送，但是不能触发监听的事件jpush.receiveNotification

### ISSUE THREAD

**Issue by zhaoxinpeng** [jpush/jpush-phonegap-plugin#126]
现在的2.1.0版本中没有receiveNotificationInAndroidCallback回调了吗？
我改成
var onReceiveNotification = function(event){
      try{
        console.log('***************order jpush jpush**********************');
        var  jpushdata = window.plugins.jPushPlugin.receiveNotification;
        if(jpushdata.extras['cn.jpush.android.EXTRA'].type == "order"){
          repeatRemind.set();  
          window.plugins.NativeAudio.play( 'click' );
          console.log('***************order background jpush**********************');
        }else if(jpushdata.extras['cn.jpush.android.EXTRA'].type == "message"){
          recivesCount = recivesCount + 1;
         }
      }
      catch(exception){
        console.log("JPushPlugin:receiveNotification-->"+exception);
      }
    }
document.addEventListener("jpush.receiveNotification", onReceiveNotification, false);
这样app在后台时根本不能执行onReceiveNotification呀。
原来我用receiveNotificationInAndroidCallback回调时，是完全没问题的？
我哪里写错了吗？

**Comment by zhaoxinpeng** [comment]
现在receiveNotificationInAndroidCallback还可以使用，就是在后台运行时不能进回调函数了。但是再发自定义消息时receiveMessageInAndroidCallback回调却可以在后台运行。不知道为什么。

**Comment by zhaoxinpeng** [comment]
至少在2.0.2版本时，APP在后台运行时receiveNotificationInAndroidCallback在收到通知就执行。但是现在的2.1.0版本，receiveNotificationInAndroidCallback只有在前台运行才能回调。

**Comment by lhw5123** [comment]
@zhaoxinpeng 你好，问题已经修复了  ^ ^

**Comment by zhaoxinpeng** [comment]
你好，我从新安装了插件，现在怎么报这个错误。
:compileDebugJava/Users/zhaoxinpeng/Documents/gitwork/test/myApp/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:61: 错误: 找不到符号
    private static Activity cordovaActivity;
                   ^
  符号:   类 Activity
  位置: 类 JPushPlugin
/Users/zhaoxinpeng/Documents/gitwork/test/myApp/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:321: 错误: 找不到符号
        Context context = this.cordova.getActivity().getApplicationContext();
        ^
  符号:   类 Context
  位置: 类 JPushPlugin
/Users/zhaoxinpeng/Documents/gitwork/test/myApp/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:327: 错误: 找不到符号
        Context context = this.cordova.getActivity().getApplicationContext();
        ^
  符号:   类 Context
  位置: 类 JPushPlugin
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/zhaoxinpeng/Documents/gitwork/test/myApp/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
3 个错误

**Comment by zhaoxinpeng** [comment]
好像是JPushPlugin.java里少导入了两个文件吧？
我添加两行代码就好了
import android.app.Activity;
import android.content.Context;

**Comment by Alplob** [comment]
非常感谢 Zhaoxinoeng!

**Comment by zhaoxinpeng** [comment]
应该谢谢你们做了这个插件。：）
现在我build ios时也报错了。
/Users/zhaoxinpeng/Documents/gitwork/test/myApp/platforms/ios/宅店/Plugins/cn.jpush.phonegap.JPushPlugin/AppDelegate+JPush.m:17:19: error: no visible @interface for 'NSObject' declares the selector 'application:didFinishLaunchingWithOptions:'
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
            ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/宅店.build/Debug-iphonesimulator/宅店.build/Objects-normal/i386/AppDelegate+JPush.o 宅店/Plugins/cn.jpush.phonegap.JPushPlugin/AppDelegate+JPush.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by Yasashi** [comment]
你好，建议你重新搭建ionic项目。从你的日志来看 AppDelegate继承自 NSObject，故而super找不到该方法。而如果ionic项目搭建成功，AppDelegate 会继承自 CDVAppDelegate 。

**Comment by lhw5123** [comment]
@zhaoxinpeng  感谢指出，已经把 JPushPlugin.java 里缺少的导入代码添加进去了。 : )

**Comment by zhaoxinpeng** [comment]
@Yasashi  你好。我这个项目之前用极光没有问题，就是最近升级了一下插件。出现的问题。现在我
ionic plugin remove jpush
ionic platform remove ios
ionic platform add ios
ionic plugin add jpush
这样也不行。难道必须要从ionic start开始吗？

**Comment by Yasashi** [comment]
@zhaoxinpeng 你好，为ionic项目添加jpush-phonegap-plugin插件可以使用以下代码：
```
ionic platform add ios
ionic plugin add  https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey  
ionic plugin add org.apache.cordova.device
```
其中 your_jpush_appkey 替换成你在极光官网app管理中的appkey

**Comment by zhaoxinpeng** [comment]
@Yasashi 。你好，我一直是像你那么写的。IOS依然报错，我该怎么办。

**Comment by Yasashi** [comment]
@zhaoxinpeng 你好，这个问题已经修复了。您现在直接更新cordova的版本，或者再更新一下jpush-phonegap-plugin都可以解决。
