### ISSUE TITLE
iOS reset badge value

### ISSUE THREAD

**Issue by Alplob** [jpush/jpush-phonegap-plugin#129]
Hello,

I use successfully this plugin with my iOS app. Nevertheless I meet a problem when I want to reset the badge value. It does not restart from 1 when I receive a new notifications. Per example:

1. Imagine Badge value = **2**

2. -> window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);

3. Badge value = **0**   (not shown on app's icon actually, that it is fine)

4. I receive a new notification -> Badge value = **3**

The normal behaviour should be **1**, not **3**, as there is only one new notification.

By the way, it seems that window.plugins.jPushPlugin.resetBadge() and window.plugins.jPushPlugin.setBadge(0) has no any effect on the displayed badge value..

So I would like to know how to reset properly the badge value so that next notification will be shown with "**1**"

Thanks!

**Comment by Yasashi** [comment]
Hi, Alplob:
&ensp;  Thanks a lot for using our plugin.
&ensp;  When badge value = 2 , means the value is 2 on our service the same time.
&ensp;  And then u send a new notification, makes badge value +1, it will also +1 from 2 to 3 on our service.
&ensp;  So u will receive a notification with the badge = 3.
&ensp;  So if u want to make the badge value show on app is 1, u should first make the value on service is 0
&ensp;  before +1. This two method will help u make that:
```
window.plugins.jPushPlugin.setBadge() //set the badge value on our service
window.plugins.jPushPlugin.resetBadge() //set the badge value = 0 on our service
```

**Comment by Alplob** [comment]
Hello Yasashi,

Thanks a lot for your prompt answer. I got your point, you mean I should combine setApplicationIconBadgeNumber() with either resetBadge() or setBadge(). But unfortunately, I tried these combinations but it seems the service value is never changed..

```
        <script type='text/javascript'>
            document.addEventListener('deviceready', function(){
                window.plugins.jPushPlugin.init();
                window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
                window.plugins.jPushPlugin.resetBadge();
            },true);
        </script>
```

```
        <script type='text/javascript'>
            document.addEventListener('deviceready', function(){
                window.plugins.jPushPlugin.init();
                window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
                window.plugins.jPushPlugin.setBadge(0);
            },true);
        </script>
```

**Comment by Yasashi** [comment]
@Alplob 
hi Alplob， actrully when u called "window.plugins.jPushPlugin.init();" it needs a bit time to start our plugin, make connection with our server .i suggest u choose a better place and try that two method again.such as:
```
function onOpenNotification(event){
    var noti;
    if (device.platform == "Android") {
        noti = window.plugins.jPushPlugin.openNotification;
    } else {
        noti = event.aps.alert;
        window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
//      window.plugins.jPushPlugin.setBadge(0);
        window.plugins.jPushPlugin.resetBadge();
    }
    document.getElementById("pushContent").innerText = noti;
}
function onReceiveNotification(event){
    window.plugins.jPushPlugin.nslog("onReceiveNotification");
    onOpenNotification(event);
}
```

**Comment by Alplob** [comment]
Ok, it seems it works now, thanks a lot for your suppor!
