### ISSUE TITLE
3月8号 iOS AppDelegate+JPush.m 的修改导致无法Build

### ISSUE THREAD

**Issue by markfredchen** [jpush/jpush-phonegap-plugin#130]
![image](https://cloud.githubusercontent.com/assets/955546/13738626/3380c1f8-ea01-11e5-90f9-b5b12cf139c7.png)

**Comment by Yasashi** [comment]
@markfredchen  你好，请加一下qq，我帮你看一下这个问题。

**Comment by zhaoxinpeng** [comment]
我也遇到了这个问题
