### ISSUE TITLE
新版本编译不通过！

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#133]
platforms\android\src\cn\jpush\phonegap\JPushPlugin.java:527: ����: ���ڲ����з��ʱ��ر���jsEvent; ��Ҫ������Ϊ��������
1>                          instance.webView.loadUrl("javascript:" + jsEvent);
1>  ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
1>  ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
1>  ע: ĳЩ�����ļ�ʹ����δ�����򲻰�ȫ�Ĳ�����
1>  ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1>  1 ������
1>  :compileDebugJavaWithJavac FAILED
1>
1>  FAILURE: Build failed with an exception.

**Comment by lhw5123** [comment]
请用最新版本的插件试一下

**Comment by xgzl87** [comment]
就是用的最新版！

**Comment by lhw5123** [comment]
@xgzl87  您好，我这边测试是没有问题的，你可以使用一个新的项目重新测试一下，如果还有问题的话，请把日志重新贴上来一下，您这个不太好判断错误。
