### ISSUE TITLE
setTags only one tag work, other tags don't work

### ISSUE THREAD

**Issue by maxer028** [jpush/jpush-phonegap-plugin#134]
var tags = new Array("2016","test");
window.plugins.jPushPlugin.setTags(tags);  //only tag '2016' work

**Comment by lhw5123** [comment]
是 Android 还是 iOS?

**Comment by Yasashi** [comment]
on iOS platform, in old version plugin ，using "setTags" method ,tags should be a string like “tag1,tag2”,in new version plugin, just an array [tag1,tag2] is ok.

**Comment by maxer028** [comment]
Android

**Comment by lhw5123** [comment]
Please try this code, or update to the latest version of the plugin if still has problem.

window.plugins.jPushPlugin.init();
getRegistrationID();

if (device.platform != "Android") {
    window.plugins.jPushPlugin.setDebugModeFromIos();
    window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
} else {
    var tags = new Array("2016", "test");
    window.plugins.jPushPlugin.setTags(tags);
}

**Comment by maxer028** [comment]
The latest version works. thanks.
