### ISSUE TITLE
error: app key not found in PushConfig.plist 

### ISSUE THREAD

**Issue by zhaoxinpeng** [jpush/jpush-phonegap-plugin#136]
我安装插件的时候是按照说明ionic plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=2cb31d4433ec656a2228eceb
这样装的，但是在PushConfig.plist里还是没有appkey.我手动添加
APP_KEY
2cb31d4433ec656a2228eceb
后重新编译，依然报错error: app key not found in PushConfig.plist

**Comment by Yasashi** [comment]
@zhaoxinpeng 你好，建议你重新执行一遍
```
 ionic plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=2cb31d4433ec656a2228eceb
```
然后检查PushConfig.plist中APP_KEY的值，如果没有再手动添加编译一下。
如果还是有问题，可以进入 https://gitter.im/  我帮你看看。

**Comment by zhaoxinpeng** [comment]
@Yasashi 你好我按照你说的做了，问题依旧。
