### ISSUE TITLE
setApplicationIconBadgeNumber not working

### ISSUE THREAD

**Issue by Nealyang** [jpush/jpush-phonegap-plugin#137]
iOS中badge设置无法成功，setApplicationIconBadge和window.plugins.jPushPlugin.prototype.setBadge(value);都没有作用，点击进入应用立刻就清零，请问这是什么问题呢？

**Comment by Nealyang** [comment]
setApplicationIconBadge是工作的，但是openNotification貌似给badge清空了。。。

**Comment by Yasashi** [comment]
你好，openNotification 只是提供了一个回调，内部并没有做badge的处理。如果是你的app一进入前台badge就会清零的话，请检查 AppDelegate+JPush.m 或者 AppDelegate.m 中的
```
- (void)applicationWillEnterForeground:(UIApplication *)application {
    //  [application setApplicationIconBadgeNumber:0];
}
```
是否对badge做了处理，在我们的AppDelegate+JPush.m里，默认是注释掉的。
如果还有问题，可以进入 gitter im https://gitter.im/    ，我会帮你解答^_^。
