### ISSUE TITLE
setApplicationIconBadgeNumber数字不准确什么原因呢？

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#138]

**Comment by Yasashi** [comment]
你好，该方法调用的是系统UIKit中的方法，本身不会有什么问题的。麻烦你检查自己的代码，或者更详细的描述问题。如果还有问题可以进入 gitter im https://gitter.im/home/explore 我会帮你解答。

**Comment by xgzl87** [comment]
啥代码也没写，iOS自动添加的角标。setApplicationIconBadgeNumber就是每次打开的时候设为0。
