### ISSUE TITLE
如何用js控制或者自定义提示音

### ISSUE THREAD

**Issue by jason5149** [jpush/jpush-phonegap-plugin#140]
框架是ionic，目前已经简单实现了从官网应用管理发一条推送消息到android客户端，但是我如何自定义这个推送消息的提示音？

**Comment by lhw5123** [comment]
你好，如果要自定义提示音的话，需要使用“自定义消息”来实现，可以在 JPushPlugin.java 文件中的 transmitPush() 方法中添加自己自定义通知的代码，可以参考下面的代码：
![image](https://cloud.githubusercontent.com/assets/6531354/14164694/527dae32-f734-11e5-9599-35d4e6d98bf4.png)
和官方的有关自定义消息的文档：http://docs.jpush.io/client/android_tutorials/#vs

**Comment by jason5149** [comment]
有办法只通过js实现么？这是要写原生，我们本不打算写原生

**Comment by lhw5123** [comment]
你好，如果只用 js 实现的话，可以使用极光发送自定义消息，在 js 中监听收到消息事件，像这样：
`        document.addEventListener("jpush.receiveNotification", onReceiveNotification, false);`
onReceiveNotification 方法需要自己定义，在该方法中使用 cordova 官方的本地通知插件，来发送一个本地通知，插件地址：https://github.com/katzer/cordova-plugin-local-notifications

**Comment by jason5149** [comment]
好的，谢谢~
