### ISSUE TITLE
app key not found in PushConfig.plist

### ISSUE THREAD

**Issue by crapthings** [jpush/jpush-phonegap-plugin#142]
我们使用 meteor

可否支持 meteor 的 app.configurePlugin ?

App.configurePlugin(id, config)

NSLog(@"error: app key not found in PushConfig.plist ");

	App.configurePlugin('cn.jpush.phonegap.JPushPlugin', {
	  API_KEY: 'OUR_API_KEY'
	});

**Comment by crapthings** [comment]
我们没有办法通过这种形式安装

cordova plugin add  https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey

**Comment by Yasashi** [comment]
@crapthings  
你好，请查阅 meteor 安装 Cordova 插件方法的相关资料。

**Comment by crapthings** [comment]
查过了，我们平常所有第三方 cordova 的方法都是通过 meteor 提供的方法设置的

一般都是三方插件需要“标准化一点”

**Comment by crapthings** [comment]
ios 下边 pushconfig 这个文件是怎么样的？

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
		<key>APP_KEY</key>
		<string>558c165d3226d48157812437</string>
	</dict>
	</plist>

**Comment by Yasashi** [comment]
PushConfig.plist 文件内容：
https://github.com/jpush/jpush-phonegap-plugin/blob/master/src/ios/PushConfig.plist
另，meteor 安装插件方法建议你参考 ：
http://stackoverflow.com/questions/26624649/how-to-add-cordova-plug-that-havent-registration-on-plugins-cordova-io
还有问题请进入 gitter im https://gitter.im/

**Comment by crapthings** [comment]
安装插件不是什么问题，那是我几年前问的了

if (!appkey || appkey.length == 0) {
        NSLog(@"error: app key not found in PushConfig.plist ");
        assert(0);
    }

**Comment by lhw5123** [comment]
@crapthings 你好，现在已经支持了，你可以再试一下

**Comment by crapthings** [comment]
cool 给你们点赞👍

等我试验一下
