### ISSUE TITLE
Andorid版本推送图标无法修改

### ISSUE THREAD

**Issue by guotingchaopr** [jpush/jpush-phonegap-plugin#143]
## 使用版本
**Cordova 6.0**
**Android Target 23**
——————————
__推送消息正常 但是无法更改默认图标 已经修改了配置的图标 也替换了默认图标 但是启动推送到达后还是在本地显示的 cordova默认LOGO__

**Comment by lhw5123** [comment]
@guotingchaopr  你好，默认通知的图标就是应用的图标，请确认下是否替换了所有的 icon.png，并且将已有的应用删除，再重新安装来测试。

**Comment by Harry-III** [comment]
> ## 使用版本
> **Cordova 6.0**
> **Android Target 23**
> ——————————
> **推送消息正常 但是无法更改默认图标 已经修改了配置的图标 也替换了默认图标 但是启动推送到达后还是在本地显示的 cordova默认LOGO**

Cordova 8.1.2  
Android Target 6.0 
同样发生上面的情况，推送消息显示cordova默认的LOGO
--------
我把icon.png换了，并且卸载应用重新安装还是一样。
