### ISSUE TITLE
jpush.openNotification事件只触发一次

### ISSUE THREAD

**Issue by ThassarianJohn** [jpush/jpush-phonegap-plugin#144]
jpush.openNotification事件只在第一次点击时触发，之后就不再触发了。

代码：

```js
        var alertContent="";
        document.addEventListener("jpush.openNotification", function() {
            
            if(device.platform == "Android") {
                alertContent = window.plugins.jPushPlugin.openNotification.alert;
            } else {
                alertContent = event.aps.alert;
            }
            alart(alertContent);
        }, false);
```

系统：安卓5.1.1
设备：红米3

**Comment by lhw5123** [comment]
是常驻通知吗？还是说同时多个通知，只有第一次点击触发？

**Comment by ThassarianJohn** [comment]
多个通知，只有第一次点击触发

第一次点击通知打开app，触发事件；(此处我清除了所有其他通知)
按下Home键返回桌面；
新的通知，点击通知打开app，不触发事件。

**Comment by lhw5123** [comment]
是最新版的插件吗？

**Comment by ThassarianJohn** [comment]
id="cn.jpush.phonegap.JPushPlugin"
version="2.1.6"

用cordova plugin add jpush-phonegap-plugin安装的

**Comment by lhw5123** [comment]
也就是程序在后台时，收到通知，不触发点击事件吗？

**Comment by ThassarianJohn** [comment]
在前台也一样，只有第一次触发（无论是前后台）

**Comment by lhw5123** [comment]
@ThassarianJohn 要不你进 [gitter](https://gitter.im/Yasashi/jpush-phonegap-plugin)，我详细给你看看吧。

**Comment by ThassarianJohn** [comment]
找到原因了。
上边代码的alert拼错了。
方法中使用toast后有很奇怪的问题，应该是和toast插件有冲突。

进行其他的操作没有问题了。
