### ISSUE TITLE
jpush-ios-2.1.6.a not found

### ISSUE THREAD

**Issue by sunjk000** [jpush/jpush-phonegap-plugin#147]
in plugin.xml 
"<source-file src="src/ios/lib/jpush-ios-2.1.6.a" framework="true" />"
jpush-ios-2.1.6.a not found;

**Comment by Yasashi** [comment]
@sunjk000  你好，已修复。
- 你可以尝试**删除**并重新安装插件
- 或者直接修改 `projectName/plugins/cn.jpush.phonegap.JPushPlugin/`目录下的 `plugin.xml` 文件，搜索`jpush-ios-2.1.6.a`,改为`jpush-ios-2.1.7.a`
