### ISSUE TITLE
插件安装成功后Android运行正常  ios端接收不到通知

### ISSUE THREAD

**Issue by iyibo** [jpush/jpush-phonegap-plugin#148]
在真机上，xcode打印启动成功了，控制台也发送成功了，但是显示目标数为0

run函数代码：
      //启动极光推送服务
      window.plugins.jPushPlugin.init();
//      window.plugins.jPushPlugin.setDebugMode(true);
      // 接收通知
     document.addEventListener("jpush.receiveNotification", function(event) {
                               
                                                 console.log(event);
                                                
                                                 }, false);

**Comment by Yasashi** [comment]
@iyibo  你好，可能是相关配置不正确：
- 打开 iOS 项目中的 `PushConfig.plist` 文件，检查：
 - `APP_KEY` 的值是否跟极光控制台的一致
 - `IsProduction` YES发布环境/NO开发环境 是否跟配置的证书一致
- 证书配置不正确，参考 [iOS 证书 设置指南](http://docs.jpush.io/client/ios_tutorials/#ios_1)

**Comment by iyibo** [comment]
多谢，找的俩个错误的地方：
1：targets-capabilities-background modes开启remote notifications功能
2：APNs is not available,please check your provisioning profile and certification；
--------需要重新配置证书

**Comment by Yasashi** [comment]
你好，关于 Background Remote Notification 可以参照 [iOS 7 Background Remote Notification](http://docs.jpush.io/client/ios_tutorials/#ios-7-background-remote-notification)
