### ISSUE TITLE
按官方文挡，无法安装这个plugin。 Cannot find module 'cordova-common/src/configparser/ConfigParser'

### ISSUE THREAD

**Issue by eguan88** [jpush/jpush-phonegap-plugin#149]
Failed to install 'cn.jpush.phonegap.JPushPlugin':Error: Cannot find module 'cordova-common/src/configparser/ConfigParser'
.
.
.
.

Error: Cannot find module 'cordova-common/src/configparser/ConfigParser'

**Comment by lhw5123** [comment]
你好，你的 Cordova 是哪一个版本的？可以更新下 Cordova 版本，再试一下。
这个问题主要是因为 Cordova 最新版本添加了一个新的 cordova-common 模块，并将之前的 ConfigParse 和其他的一些组件移到了里面，更新下新版本的 Cordova 应该就可以了。

**Comment by eguan88** [comment]
cordova -v

6.2.0

应该是新版的

**Comment by eguan88** [comment]
platforms/android/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js

文件也在cordova-common里面

**Comment by eguan88** [comment]
如果运行cordova build android 还会出现

:compileDebugJavaWithJavac/xxxxxxx/platforms/android/src/cn/jpush/phonegap/MyReceiver.java:45: error: cannot find symbol
        JPushPlugin.transmitMessageReceive(msg, extras);

**Comment by lhw5123** [comment]
是用的 cordova plugin add jpush-phonegap-plugin --varibale API_KEY=your_app_key 来安装的吗？
