### ISSUE TITLE
安装device插件

### ISSUE THREAD

**Issue by zyf0330** [jpush/jpush-phonegap-plugin#150]
直接在plugin.xml中写个dependency好了，不必手动要求装个device插件。

**Comment by lhw5123** [comment]
Good idea，已改。: )

**Comment by zyf0330** [comment]
@lhw5123 
提交b01b4bf2590a213a212af17bf87e3f0050d1cea3中的dependency，现在又没了？发生了什么？
还有，文档中的isPushStopped返回结果的说明反了，我记得这个也是改过的呀？

**Comment by lhw5123** [comment]
加了 dependency 会导致命令行安装插件时，会先要通过 git 访问 cordova-plugin-device 插件的 url（不论之前用户是不是已经装了 device 插件），如果用户没有装 git 就会报错。依赖还会导致在删除插件时会将 device 插件一并删除，之前有好几个用户反映了这个问题，并还以为是插件的问题。

并且鉴于现在很多框架，如 ionic 等都已经默认安装了 device 插件和加了依赖可能导致的问题，还是决定去掉了这个依赖。

**Comment by zyf0330** [comment]
那是因为你用的不单纯是cordova-plugin-device作为id，加上了url，那么就会通过git去拉取github，否则的话，就会通过npm去拉取npmjs包，而且移除插件的时候，cordova也会检查是否有其他依赖，如果加了url就不会检查了。
😓

**Comment by zyf0330** [comment]
[plugin.xml dependency](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#dependency)

**Comment by zyf0330** [comment]
嘿，没事。让它好用一点。
