### ISSUE TITLE
openNotification的回调

### ISSUE THREAD

**Issue by zyf0330** [jpush/jpush-phonegap-plugin#152]
`openNotification`注册的回调函数，只会在调用它的页面执行，毋庸置疑。那么，就得在每一个页面都注册它了，对吗？

**Comment by lhw5123** [comment]
本质上是的，但可以将方法写在 js 里，之后在界面中引用。

**Comment by zyf0330** [comment]
总之，每个页面必须执行回调注册吧

On Mon, Jun 27, 2016, 12:46 Hevin <notifications@github.com> wrote:

> 本质上是的，但可以将方法写在 js 里，之后在界面中引用。
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jpush/jpush-phonegap-plugin/issues/152#issuecomment-228653133>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZ5ge6YTryE_xwRpyILfCnME0SuPuDKks5qP1WkgaJpZM4I-vKG>
> .
>
-- 

追随

**Comment by lhw5123** [comment]
是的。

**Comment by zyf0330** [comment]
还有一个问题，附加数据kv，在ios中是否也能单独作为一个属性。

**Comment by Yasashi** [comment]
开发者根据不同需求，附加字段个数、类型都不定，自己定义，自己处理。

**Comment by zyf0330** [comment]
@Yasashi 为什么android的可以在`extras['cn.jpush.android.EXTRA']`中呢？

**Comment by zyf0330** [comment]
@Yasashi 我只是要提供一个统一的对外接口，不管是什么平台。

**Comment by Yasashi** [comment]
Android 是在 Java 里实现的，所以你可以从 JavaScript 直接调用。iOS 里我添加一个 NSString 或者 NSDictionary 或者 NSArray 的属性，你也调不了。
返回字段参考 [event - jpush.openNotification](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#%E8%8E%B7%E5%8F%96-apns-%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9) 可以尝试使用 `event.key ` 的方式获取自定义字段。

**Comment by zyf0330** [comment]
好吧。其实我不认为这是一个技术上的问题，js作为一个跨平台语言，Cordova作为一个解决跨平台app开发的解决方案，对于其上的模块和接口，跨平台的统一性，自然应该作为一个优先考虑的事情。

**Comment by Yasashi** [comment]
在 iOS native 和 js 之间只能通过 json 字符串进行沟通的。

**Comment by Yasashi** [comment]
Objective-C、Java、JavaScript 毕竟是不同的语言。iOS 和 Android 毕竟是不同的平台，API 的数量也不同，完全统一可能无法实现。
openNotification 回调中既然可以通过 `event.key` 的方式直接获取到自定义字段，plugin 再内部处理并添加一个 `openNotification.extra.key` 的方法岂不多余？

**Comment by zyf0330** [comment]
我只好把event对象作为optional属性值，这样，外部调用接口，alert在content，msgid在msgid，kv在optional，不需要为每个平台都写不同的字段来取值。

On Mon, Jun 27, 2016, 15:03 Pikachu <notifications@github.com> wrote:

> Objective-C、Java、JavaScript 毕竟是不同的语言。iOS 和 Android 毕竟是不同的平台，API
> 的数量也不同，完全统一可能无法实现。
> openNotification 回调中既然可以通过 event.key 的方式直接获取到自定义字段，plugin 再内部处理并添加一个
> openNotification.extra.key 的方法岂不多余？
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jpush/jpush-phonegap-plugin/issues/152#issuecomment-228668439>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZ5gda5r4bHCYSAhU6_R34bW7FoMfQgks5qP3XKgaJpZM4I-vKG>
> .
>
-- 

追随
