### ISSUE TITLE
Android中的hook有问题

### ISSUE THREAD

**Issue by zyf0330** [jpush/jpush-phonegap-plugin#153]
删除``文件那条分支，没有判断是否是删除的本插件，导致其他插件删除会触发，因此build失败。

**Comment by lhw5123** [comment]
那个卸载插件的 hook 确实没有必要，但是就算执行了脚本，也只是做了修改包名的操作，build 失败有什么具体的日志吗?

**Comment by zyf0330** [comment]
不，我的意思是，插件移除钩子会触发删除JPushPlugin.java的操作。

**Comment by lhw5123** [comment]
ok，我把卸载插件的那个 hook 去掉吧，只留安装插件的 hook。

**Comment by zyf0330** [comment]
其实我更倾向于，按照cordova的推荐方式使用R。

**Comment by lhw5123** [comment]
嗯，也可以，我现在优化下。

**Comment by zyf0330** [comment]
感谢。

**Comment by lhw5123** [comment]
@zyf0330 已经修改发布了。

**Comment by zyf0330** [comment]
直接把用到R的代码注释了吗

**Comment by lhw5123** [comment]
对的，因为其实那段代码就是要开发者自己写的，用来自定义通知栏，之前的代码也只是个例子。

**Comment by zyf0330** [comment]
哦
