### ISSUE TITLE
receiveNotification会触发两次

### ISSUE THREAD

**Issue by zyf0330** [jpush/jpush-phonegap-plugin#154]
ios上，每一条消息会触发两次receiveNotification

**Comment by Yasashi** [comment]
你好，如果你是用的 iOS 9 ，可能是你重复安装 App 多次注册推送服务导致，这是 apple 的 bug。
- 可以通过判断 msg_id 是否跟上次相同来只处理一条
- 或者尝试重启手机看是否恢复正常

**Comment by zyf0330** [comment]
原来是这样。希望这个问题可以放到常见问题中。

**Comment by zyf0330** [comment]
那么，msg_id是否全部是唯一的？

**Comment by Yasashi** [comment]
会加到常见问题里的。msg_id 是唯一的亲。

**Comment by zyf0330** [comment]
哦，好。

**Comment by zyf0330** [comment]
@Yasashi 的确重启就好了，不过我发现，重启以后，如果不打开应用，就不会收到通知，应该是因为没有init，这个有什么办法呢？

**Comment by Yasashi** [comment]
我试了一下，重启以后手机可能需要一点时间联系苹果服务器还有启动系统服务，等一会推送是可以收到的。

**Comment by zyf0330** [comment]
哦，好，谢谢了。
