### ISSUE TITLE
ios的自定义消息没有msg_id?

### ISSUE THREAD

**Issue by zyf0330** [jpush/jpush-phonegap-plugin#155]
receiveMessage没有msg_id吗？

**Comment by Yasashi** [comment]
没有

**Comment by zyf0330** [comment]
为什么呢？

**Comment by Yasashi** [comment]
控制台可以查询到

**Comment by zyf0330** [comment]
服务端发送时候，有msgid吗

**Comment by zyf0330** [comment]
服务端发送时候，有id吗

**Comment by Yasashi** [comment]
没有。native 取到的是啥，我传到 js 里的就是啥。原封不动的传给你。

**Comment by zyf0330** [comment]
那客户端怎么根据id判断呢？

**Comment by Yasashi** [comment]
你要判断什么？能把你的问题描述清楚吗？

**Comment by zyf0330** [comment]
其实我只是比较奇怪，这个自定义消息看起来和通知没什么区别，什么地方会用到它呢？

**Comment by Yasashi** [comment]
iOS 里只有在前端运行的时候才能收到自定义消息，是通过我们极光服务器发送的消息，不通过苹果服务器，并且不会有显式的弹窗。

**Comment by zyf0330** [comment]
这个自定义消息和通知，内容上有什么区别吗？我没发现，都是只能放文本和自定义键值对。

**Comment by lhw5123** [comment]
@zyf0330 这个问题嘛，可以看看这里 http://docs.jiguang.cn/client/android_tutorials/#vs ，讲得清楚点。

**Comment by zyf0330** [comment]
可以认为，自定义消息主要是对Android的？

**Comment by lhw5123** [comment]
@zyf0330 可以这样认为，iOS 上因为苹果的特定规则，我们也有一个[应用内消息](http://docs.jiguang.cn/client/ios_sdk/#ios-sdk_1)的形式，只是比自定义消息用法要窄些。但基本意图都是，可以通过这个发送用户不会察觉的消息，然后根据收到的消息来做一些特定的业务逻辑，就不一定只是展示推送这样的了，当然具体的业务逻辑每个应用都不一样。: )

**Comment by zyf0330** [comment]
哦，我知道了。谢谢。
