### ISSUE TITLE
為什麼客製化notification style無法變更

### ISSUE THREAD

**Issue by bruce0718** [jpush/jpush-phonegap-plugin#157]
我試著想要變更客製化 notification
把basenotification設定跟customernotification一致
然後變更test_notification_layout的版面設定
為什麼實際上機測試後，版面都沒有做任何異動
是我哪邊有設定錯誤嗎

**Comment by lhw5123** [comment]
是這樣的，自定義 notification layout，是需要修改 JPushPlugin.java 中的 setCustomPushNotificationBuilder 方法，並且修改之後要指定一個 builderID（或者直接設置為默認樣式）：

    void setCustomPushNotificationBuilder(JSONArray data, CallbackContext callbackContext) {
        ....
        JPushInterface.setPushNotificationBuilder(2, builder);  // 2: builder ID.
        JPushInterface.setDefaultPushNotificationBuilder(builder);  // 設置為默認的 notification 樣式，不需要再指定 builder ID。
    }

然後在 JS 中調用 

    window.plugins.jPushPlugin.setCustomPushNotificationBuilder()

如果設置了 builder ID，最後在發送 notification 時，也要額外指定要使用的 notification builder ID。
> 也可以參考下官網的文檔： http://docs.jiguang.cn/client/android_tutorials/#_11

![ol m5e2u1g x4o2iir 9d](https://cloud.githubusercontent.com/assets/6531354/16798053/caafc1da-491c-11e6-9a2f-621552853624.png)


> ps: 抱歉，Github 上傳圖片太慢了...

**Comment by bruce0718** [comment]
感謝lhw5123的回答
 我其實是看到JPushPlugin.java 中的 setCustomPushNotificationBuilder 方法，下面看起來可以自己定義style(R.layout.test_notification_layout)，所以直接在setBasicPushNotificationBuilder使用下面這段程式，所以這樣也是不行的嗎?

    /**
    *  自定义推送通知栏样式，需要自己实现具体代码。
    *  http://docs.jiguang.cn/client/android_tutorials/#_11
    */
    void setCustomPushNotificationBuilder(JSONArray data,
            CallbackContext callbackContext) {
        // CustomPushNotificationBuilder builder = new CustomPushNotificationBuilder(
        //         this.cordova.getActivity(), R.layout.test_notification_layout,
        //         R.id.icon, R.id.title, R.id.text);
        // builder.developerArg0 = "Custom Builder 1";
        // JPushInterface.setPushNotificationBuilder(2, builder);
        // JSONObject obj = new JSONObject();
        // try {
        //     obj.put("id", 2);
        // } catch (JSONException e) {
        //     e.printStackTrace();
        // }
    }

**Comment by lhw5123** [comment]
那如果這樣的話，也是可以的，但這段只是示例代碼，裡面指定了 builder ID 為 2（也可以改作其他數字），所以發送通知時，就也需要指定「通知欄樣式」為 2 了。然後 JS 端也需要調用：

    window.plugins.jPushPlugin.setBasicPushNotificationBuilder()

**Comment by bruce0718** [comment]
我知道 可是我重點是在變更test_notification_layout的版面設定，例如ImageView的大小
但是實際上機卻沒有反應

**Comment by lhw5123** [comment]
@bruce0718 這樣試下：
![aba e e 1 mr6f k2fqo 0](https://cloud.githubusercontent.com/assets/6531354/16800418/c81c15da-4927-11e6-9c27-f6cd8c2ee3c3.png)

然後在頁面文件中這樣調用：
![oc ce1hisvpkb8mc g4m5a](https://cloud.githubusercontent.com/assets/6531354/16800473/12844962-4928-11e6-8e12-694767cba67d.png)

這裡是我的測試佈局文件：
![o a9i0a3t3qvvxyf85b7n0d](https://cloud.githubusercontent.com/assets/6531354/16800500/2f3319bc-4928-11e6-8f8e-6e355f306209.png)

這裡是實際效果：
![vl92 ap 4 x n j17fzji67](https://cloud.githubusercontent.com/assets/6531354/16803088/e55d0a8c-4936-11e6-8763-f93ded34e33e.png)

**Comment by bruce0718** [comment]
謝謝您的回覆與幫忙
我會在測試一下，再回覆您
