### ISSUE TITLE
关于API_KEY的安装替换问题

### ISSUE THREAD

**Issue by vcboy** [jpush/jpush-phonegap-plugin#159]
cordova plugin add jpush-phonegap-plugin --variable API_KEY=your_jpush_appkey 用这个命令安装，包是可以安装进去，但是API_KEY无法替换掉，是不是直接把plugin.xml文件的API_KEY替换成真正的AppKey就行了？其他文件不需要调整?

**Comment by pikacode** [comment]
是的。如果是 iOS 可以在工程目录中搜索 `PushConfig.plist` 文件，手动为 `APP_KEY` 字段赋值。
