### ISSUE TITLE
networkDidReceiveMessage 收不到任何消息。

### ISSUE THREAD

**Issue by guanjinke** [jpush/jpush-phonegap-plugin#16]
在AppDelegate.m中的didReceiveRemoteNotification中确实收到了消息，但是在JPushPlugin.m中的networkDidReceiveMessage却没有任何反应。

**Comment by simplechen** [comment]
然后呢。我也遇到这样的问题！如何解决这个问题？

**Comment by zhangqinghe** [comment]
@simplechen 你发的是通知还是消息？
