### ISSUE TITLE
不能下载/更新？

### ISSUE THREAD

**Issue by ctl1690** [jpush/jpush-phonegap-plugin#161]
会一直收到连线错误, 跟压缩包检查错误

Fetching plugin "https://github.com/jpush/jpush-phonegap-plugin.git" via git clone
Error: Failed to fetch plugin https://github.com/jpush/jpush-phonegap-plugin.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/mr/gqx8_84n6v381vx0wgrlk8x00000gn/T/git/1471406422138'...
error: RPC failed; curl 56 SSLRead() return error -9845
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed

-------------------------

Error: Failed to fetch plugin jpush-phonegap-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: shasum check failed for /var/folders/mr/gqx8_84n6v381vx0wgrlk8x00000gn/T/npm-23291-67400c87/registry.npmjs.org/jpush-phonegap-plugin/-/jpush-phonegap-plugin-2.2.5.tgz
Expected: 206e85d1a27c2be5eb4ecb5221b77066794cf187
Actual:   0bf98d6f44530b85fda6b67cff2610197903ab49
From:     https://registry.npmjs.org/jpush-phonegap-plugin/-/jpush-phonegap-plugin-2.2.5.tgz

**Comment by pikacode** [comment]
@ctl1690 
建议重试是否还存在该问题。或者检查安装插件命令
```
//cordova plugin 安装
cordova plugin add jpush-phonegap-plugin --variable API_KEY=your_jpush_appkey
//URL 安装
cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey  
//本地安装
cordova plugin add Your_Plugin_Path  --variable API_KEY=your_jpush_appkey
```
