### ISSUE TITLE
setPushNotificationBuilder无效

### ISSUE THREAD

**Issue by hewz** [jpush/jpush-phonegap-plugin#164]
需要在cordova客户端中设置铃声和震动提醒，于是改写插件代码如下。但是发现并无效果，是调用问题还是bug?

   js

    JPushPlugin.prototype.setBasicPushNotificationBuilder = function (type) {
         if (device.platform == 'Android') {
            data = [type]
            this.call_native('setBasicPushNotificationBuilder', data, null)
         }
    }
   java

    void setBasicPushNotificationBuilder(JSONArray data,CallbackContext callbackContext) {
        BasicPushNotificationBuilder builder = new BasicPushNotificationBuilder(
                this.cordova.getActivity());
        try {
            builder.developerArg0 = "Basic builder 1";
            String type = data.getString(0);
            if(type != null)
            {
                if(type.equals("sound"))
                {
                    builder.notificationDefaults = Notification.DEFAULT_SOUND
                            | Notification.DEFAULT_LIGHTS;  // 设置为铃声、呼吸灯
                }
                else if(type.equals("vibrate"))
                {
                    builder.notificationDefaults = Notification.DEFAULT_VIBRATE
                            | Notification.DEFAULT_LIGHTS;  // 设置为震动、呼吸灯
                }
                else if(type.equals("all"))
                {
                    builder.notificationDefaults = Notification.DEFAULT_SOUND
                            | Notification.DEFAULT_VIBRATE
                            | Notification.DEFAULT_LIGHTS;  // 设置为铃声、震动、呼吸灯闪烁都要
                }
                else
                {
                    builder.notificationDefaults = Notification.DEFAULT_LIGHTS;  // 设置为呼吸灯闪烁
                }
            }
            JPushInterface.setPushNotificationBuilder(1, builder);
            callbackContext.success();
            } catch (JSONException e) {
                e.printStackTrace();
                callbackContext.error("Error reading Notification type");
            }
        }

**Comment by lhw5123** [comment]
`JPushInterface.setPushNotificationBuilder(1, builder);`
你这里的样式 builder ID 为 1，那在推送的时候也需要指定样式 ID 为 1 才行。
![3155dc07-88eb-4301-bf64-66404e9ca75b](https://cloud.githubusercontent.com/assets/6531354/18373895/b9cd6b0c-767a-11e6-9901-3b51bfc1a03f.png)

或者调用 `public static void setDefaultPushNotificationBuilder(BasicPushNotificationBuilder builder)` 方法，将这个 builder 设置为默认的，具体可以参考下[文档](http://docs.jiguang.cn/jpush/client/Android/android_api/#api_6)。: )

**Comment by hewz** [comment]
已解决，谢谢。以为编号1就是默认的。
