### ISSUE TITLE
IOS10待支持

### ISSUE THREAD

**Issue by xianseng000** [jpush/jpush-phonegap-plugin#165]
刚升级ios10的设备，客户端使用不了

**Comment by pikacode** [comment]
请详细描述一下遇到的问题

**Comment by xianseng000** [comment]
是这样的 ，项目在ios9设备上推送使用没有问题。
但今天另一台设备升级ios10后，获取不到RegistrationID
window.plugins.jPushPlugin.getRegistrationID(function (data) {
    //data为“”
});
另：极光的sdk升级到2.1.9了，目前的2.1.8应该还没有支持ios10系统吧

**Comment by xianseng000** [comment]
是这样的 ，项目在ios9设备上推送使用没有问题。
但今天另一台设备升级ios10后，获取不到RegistrationID
window.plugins.jPushPlugin.getRegistrationID(function (data) {
//data为“”
});
另：极光的sdk升级到2.1.9了，目前的2.1.8应该还没有支持ios10系统吧



yi_longhui@163.com
 
发件人： pikacode
发送时间： 2016-09-14 14:47
收件人： jpush/jpush-phonegap-plugin
抄送： xianseng000; Author
主题： Re: [jpush/jpush-phonegap-plugin] IOS10待支持 (#165)
请详细描述一下遇到的问题

**Comment by pikacode** [comment]
近日会更新支持 iOS 10

**Comment by xianseng000** [comment]
thx

**Comment by imeasyer** [comment]
坐等。thx

**Comment by HotaruSun** [comment]
具体什么时候能release新版本，现在ios的审核就出问题了

**Comment by ickeep** [comment]
@pikacode 具体什么时候会支持到IOS10呢？

**Comment by pikacode** [comment]
@ickeep 
https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v2.2.4
