### ISSUE TITLE
Cordova 6.3.1 白屏

### ISSUE THREAD

**Issue by Orange637** [jpush/jpush-phonegap-plugin#166]
升级了Cordova 6.3.1之后，程序启动白屏。
测试过6.3.0也不行，同样白屏和闪退。
但是Cordova 6.2.0与6.1.1正常。
测试系统是IOS10。

有谁知道是什么原因吗？

**Comment by pikacode** [comment]
建议暂时使用不会白屏的 Cordova 版本，最新版本 iOS 这边后续会测试。我现在使用的是 6.1.1 版本开发的插件，可以正常运行。

**Comment by pikacode** [comment]
@Orange637 
更改 Cordova 版本后，删除插件重装。

**Comment by pikacode** [comment]
把 `Content-Security-Policy` 替换成
```html
<meta http-equiv="Content-Security-Policy" content="default-src gap://ready file://* *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *">
```
