### ISSUE TITLE
jpush 安卓应用后台杀掉之后收不到推送。。

### ISSUE THREAD

**Issue by a81584944** [jpush/jpush-phonegap-plugin#167]
你好
我想请问下
我在开发环境下配置prodution为false的模式推送，发现app在打开和在后台的时候都可以有效收到，但是杀掉进程就收不到，重新打开app的时候就会把离线的消息推送过来。
是不是在生产环境下没有这个问题？还是说安卓的app在杀掉后台进程之后就确实收不到的。

**Comment by lhw5123** [comment]
Android 系统下如果 App 被杀掉进程确实是收不到推送的，因为现在很多第三方 ROM 都会限制应用的后台服务。

**Comment by a81584944** [comment]
可能我的表述不是非常清楚，我所说的杀后台就类似于任务管理器中将其remove掉，这样子也收不到么。我还试了下微信 他是可以收到notification的。

**Comment by lhw5123** [comment]
是这样的，像微信、QQ 这样的大厂应用，手机厂商是会加入到白名单中的，也就是不禁止它们的自启动。但一般的应用被 remove 掉，是会被有些第三方 ROM 禁止自启动的，也就收不到通知了。如果想让自己的应用无论什么时候都能收到通知，需要自己去做应用保活，可以看看[这里](https://www.zhihu.com/question/29826231)（但不是很推荐）。

或者用文案引导用户把你的应用在手机设置中设置允许自启动，[这里是](http://docs.jiguang.cn/jpush/client/Android/android_faq/#push-android)不同手机的情况，把选择权交给用户，这个也是 Google 官方推荐的方法。: )
