### ISSUE TITLE
升级到 v2.2.4 后，iOS9 收不到推送

### ISSUE THREAD

**Issue by shaung** [jpush/jpush-phonegap-plugin#171]
iOS10 可以收到，iOS9.3 收不到推送了。极光后台显示推送成功，但设备上收不到。证书没变。

**Comment by MiracleYF** [comment]
ios9 初始化的时候，显示APP_KEY 不能为空，但配置文件中已经填写了APP_KEY

**Comment by pikacode** [comment]
iOS 9设备没有在 Apple 开发者官网添加到 Apple Device 里
