### ISSUE TITLE
之前一直是好的 昨天重新安装之后 build failed 

### ISSUE THREAD

**Issue by jiaxiaxia** [jpush/jpush-phonegap-plugin#172]
Plugins/jpush-phonegap-plugin/JPushPlugin.m:13:9: fatal error: 'UserNotifications/UserNotifications.h' file not found
#import <UserNotifications/UserNotifications.h>
        ^
1 error generated.

**Comment by chineseneo** [comment]
应该是因为升级了xcode吧？

**Comment by pikacode** [comment]
#168
