### ISSUE TITLE
安装插件失败，Error: Unexpected token }？

### ISSUE THREAD

**Issue by kangkangding** [jpush/jpush-phonegap-plugin#174]
安装   cordova plugin add jpush-phonegap-plugin
错误信息   Error: Unexpected token }
cordova 版本6.1.1

**Comment by pikacode** [comment]
- 贴完整日志
- 删除重装
- 经测试最新插件是支持 Cordova 6.1.1 6.3.1 的

**Comment by kangkangding** [comment]
D:\javawork\SmartFluxClnt2>cordova plugin add jpush-phonegap-plugin
Fetching plugin "jpush-phonegap-plugin" via npm
Error: Unexpected token }
日志就这么多了   
一共安装了十几次了，cordova 版本也换了好几个，plugins下有这个插件jpush-phonegap-plugin，不过没有自动配置

**Comment by pikacode** [comment]
- 尝试下载到本地安装
```
cordova plugin add Your_Plugin_Path  --variable API_KEY=your_jpush_appkey
```
- 尝试 url 安装
```
cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey  
```

**Comment by kangkangding** [comment]
不知道我的cordova版本下的文件对不对
![333333](https://cloud.githubusercontent.com/assets/12298713/19378081/5056225e-921d-11e6-8e21-3959cbedc352.png)

**Comment by kangkangding** [comment]
D:\javawork\SmartFluxClnt2>cordova plugin add  F:\atencenttong\jpush-phonegap-pl
ugin --variable API_KEY=？
Error: Unexpected token }
还是报这个错 ，不过插件还是装上了，只不过android.json里面没有自动配置

**Comment by pikacode** [comment]
亲，能麻烦你把  your_jpush_appkey 替换成你的 appkey 吗？

**Comment by kangkangding** [comment]
额，我用的就是我的appkey，只是用？代替了，那个android.json里面会自动配置吗

**Comment by kangkangding** [comment]
问题解决了，原来安装的文件没有清理干净，万分感谢！！！
