### ISSUE TITLE
在 IPv6 环境下 RegistrationID 可能取不到

### ISSUE THREAD

**Issue by GuoDapeng** [jpush/jpush-phonegap-plugin#176]
window.plugins.jPushPlugin.getRegistrationID(onGetRegistradionID);
var onGetRegistradionID = function(data) {
    try {
        console.log(data);  
    } catch(exception) {
        console.log(exception);
    }
}

在 IPv4 网口下从来没有遇到 RegistrationID 取不出来的问题。

提交 APP Store 时，人家用的 IPv6 环境，然后 RegistrationID 取不出来。

我自己试试了试试， IPv6 一定是不好用的。获得 RegistrationID 和 IP 协议有啥关系么？？？

**Comment by pikacode** [comment]
本插件直接调用的 JPush SDK 的方法，JPush SDK v2.1.7 已经支持了 IPv6，本插件版本在 >= [v2.1.6](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v2.1.6) 支持了 IPv6。

**Comment by pikacode** [comment]
调用方法需要选在何时的时机参照 demo，刚刚启动 App（刚刚启动 JPush SDK）的时候调用是无法获取的，因为启动未完成。

**Comment by GuoDapeng** [comment]
我用 Mac 建立的 ipv6 网络，每一次都是获得不到，换到 ipv4网络时就好了。每次测试都删除了 APP。我没有改变我的代码。在 cordova 加载完成后调用，如果失败下一秒再次调用，重复了 100 次，ipv6 下是得不到的。ipv4 下挺好的。我有空在试试吧。

**Comment by pikacode** [comment]
我这边测试 IPv6，API 调用正常。建议你重新搭建 IPv6 测试环境，并重试。
