### ISSUE TITLE
什么时候能够集成ionic2

### ISSUE THREAD

**Issue by kongdewen1994** [jpush/jpush-phonegap-plugin#179]
最近在使用ionic2，不知道如何集成到ionic2中使用

**Comment by pikacode** [comment]
这里有一位开发者提供的 基于IONIC2极光推送示例
[ionic2-jpush-demo](https://github.com/zjcboy/ionic2-jpush-demo)

**Comment by pikacode** [comment]
或者直接使用 `(<any>window).plugins.jPushPlugin.doSomething(); ` 调用现有 API。

**Comment by yozman** [comment]
可以使用
`declare var JPushPlugin`
然后用 `JPushPlugin.init()` 的形式调用现有接口

**Comment by kongdewen1994** [comment]
@pikacode https://github.com/kongdewen1994/ionic2-jpush-cordova-plugin

**Comment by kongdewen1994** [comment]
@yozman https://github.com/kongdewen1994/ionic2-jpush-cordova-plugin

**Comment by lh4111** [comment]
https://github.com/lh4111/ionic-jpush.git
或者直接使用
```
npm i ionic3-jpush -S
```
仅支持ionic-native3以上
