### ISSUE TITLE
  cordova 安装JPush PhoneGap Plugin插件产生 Error loading cordova-browser

### ISSUE THREAD

**Issue by zqy216** [jpush/jpush-phonegap-plugin#180]
执行安装插件命令：cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=1111111111
后报错
Error loading cordova-browser

**Comment by pikacode** [comment]
- 删除原有插件
- 选择网络好的时候重试
- 或者下载插件到本地，进行本地安装
