### ISSUE TITLE
怎么有些手机拿不到registrationId呢

### ISSUE THREAD

**Issue by suichukewan** [jpush/jpush-phonegap-plugin#181]
怎么有些手机拿不到registrationId呢

**Comment by pikacode** [comment]
请提供具体日志信息。

**Comment by suichukewan** [comment]
就是拿到的是空

**Comment by pikacode** [comment]
如果是有的设备能取到，有的不能取到，那可能是取不到的手机设备没有加入到 Apple Device 中 [iOS 证书 设置指南](https://docs.jiguang.cn/jpush/client/iOS/ios_cer_guide/)

**Comment by suichukewan** [comment]
努比亚也不行

**Comment by pikacode** [comment]
@lhw5123

**Comment by lhw5123** [comment]
@suichukewan 努比亚现在确实有这个问题，https://community.jiguang.cn/t/6-0-h2os-registrationid/7014

**Comment by suichukewan** [comment]
@lhw5123  谢谢
