### ISSUE TITLE
不好意思啊，升级后还是报AppDelegate+JPush.m

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#183]
Plugins/jpush-phonegap-plugin/AppDelegate+JPush.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>         (1 failure)

**Comment by pikacode** [comment]
建议删除插件重新安装

**Comment by xgzl87** [comment]
重装依然报同样的错....

**Comment by pikacode** [comment]
更新 Cordova 到最新版本重试下。

**Comment by xgzl87** [comment]
更新过了6.4.0

**Comment by pikacode** [comment]
加q群帮你看一下问题咯，Cordova / Hybrid App 交流群 413602425

**Comment by xgzl87** [comment]
是我的开发环境问题，mac的系统版本不正确。
