### ISSUE TITLE
ionic android通知栏不显示推送数据

### ISSUE THREAD

**Issue by jeneser** [jpush/jpush-phonegap-plugin#184]
安装插件：
cordova plugin add jpush-phonegap-plugin --variable API_KEY=your_jpush_appkey
没有问题，装置ready后：
//启动极光推送服务
window.plugins.jPushPlugin.init();
//调试模式
window.plugins.jPushPlugin.setDebugMode(true);
然后：
ionic run android -lc 开始调试
命令行成功打印：推送的数据
![screenshot from 2016-11-19 11-22-17](https://cloud.githubusercontent.com/assets/15034042/20452916/7be3429c-addb-11e6-8cf8-f60d3044796f.png)

但是：
设备通知栏没有任何显示，查看其他资料说，自定义的消息不会在通知栏显示，需要用ionic命令行调试输出。
另外并没有查到通知的资料，但网上的教程按照以上的步骤就能直接接收了，包括在设备的通知栏显示

我遇到的问题是：能接收推送数据，但是通知栏不显示这些数据，不论是后台推送的通知还是自定义消息
谢谢！-_-

**Comment by jaymz1439** [comment]
首先你要确保你的应用中是否已经集成了jpush，然后是否能在jpush后台注册成功。

**Comment by jeneser** [comment]
上面的描述有什么漏掉吗?
已经集成成功，推送也能收到，问题是不能在通知栏显示任何推送数据，看截图console的输出(o´ω`o)

**Comment by jaymz1439** [comment]
看上面的步骤好像没问题啊，我也是这样，但是最后我是把工程build，在测试的，就是插件装完之后，cordova build android，之后就可以了。很少用run调试（不知道是不是这个影响）

**Comment by jeneser** [comment]
这个没有影响，我测试了很多方法
cordova build android之后依然没有任何反应。

不过有一点，网上有文章说插件的安装顺序会影响正常使用，不知是否可信。
这个插件的安装是在已有android平台，device插件已安装的情况下添加的，安装过程并未产生任何错误。

我现在的解决方案是：

利用cordovaLocalNotification结合来自极光平台的数据将消息展示在通知栏，经过测试这种方法可行。
但网上许多教程在安装成功后直接就能达到这种效果，不解？我的问题也在这里...

下面是我的代码：我把它写在了.run()的$ionicPlatform.ready()里

```
var onReceiveMessage = function(event) {
            try {
                var jid = window.plugins.jPushPlugin.receiveMessage.extras.id || 1;
                var jtitle = window.plugins.jPushPlugin.receiveMessage.extras.title || 'title';
                var message;
                if (device.platform == "Android") {
                    message = event.message;
                    var scheduleSingleNotification = function () {
                        $cordovaLocalNotification.schedule({
                            id: jid,
                            title: jtitle,
                            text: message,
                            badge: 1,
                            data: {
                              customProperty: 'value'
                            }
                        }).then(function (result) {
                            // console.log(result);
                        });
                    };
                    scheduleSingleNotification();
                } else {
                    message = event.content;
                }
            } catch (exception) {
                console.log("err" + exception);
            }
        };
        document.addEventListener("jpush.receiveMessage", onReceiveMessage, false);
```

**Comment by lhw5123** [comment]
@jeneser 看你的代码里是 receiveMessage，这个是表示的监听自定义消息，自定义消息确实是不会显示在通知栏上的。是用的极光控制台来推送的通知吗？
![z 4cl u s5 xwfszcsb iq6](https://cloud.githubusercontent.com/assets/6531354/20549389/a6792b14-b166-11e6-99ce-1666dc1b09f1.png)

**Comment by jeneser** [comment]
@lhw5123 感谢你的关注
是的，这些测试是使用的极光推送控制台

自定义消息不会显示在通知栏上
上面的代码是让自定义消息显示在通知栏上，可能这些代码不恰当，但可以说明一些问题。

那么现在的问题就是:
从极光推送控制台  发送通知  ，不能直接显示在通知栏上。控制台里能打印这些通知。

再补充一下插件安装过程吧:
添加jpush插件,插件安装过程中没有报任何错误。
然后在app.js页面中添加下面两行代码
window.plugins.jPushPlugin.init();
window.plugins.jPushPlugin.setDebugMode(true);

其他并未做任何配置。

**Comment by lhw5123** [comment]
@jeneser 是 ionic1 还是 ionic2 呢？有尝试过不同的手机吗？: )

**Comment by jeneser** [comment]
@lhw5123 是ionic1，测试的安卓模拟器是运行在Ubuntu上的Android5.1版本。真机测试用的是魅蓝note2。
没有在其他设备上测试过。
是的，我需要去测试一下(o´ω`o)...

**Comment by jeneser** [comment]
@lhw5123 在社区里发现了这个，按题主说的魅族的手机有几款不支持

https://community.jiguang.cn/t/flame-5-1-os-2-0/6512/17

**Comment by Dpuer** [comment]
真机索尼Z5P，安卓5.1.1系统也有相同问题，消息能发送成功，但是通知栏没通知

**Comment by jeneser** [comment]
测试后忘了过来回复，抱歉！
又真机测试了：华为荣耀４，红米
仍然是同样的问题
消息能发送成功，但是通知栏没通知

顺便说一下：
这次的测试是ｒｅｌｅａｓ之后并签名成功的ａｐｋ包。
在开启setDebugMode的情况下进行测试，插件并未抛出任何异常

**Comment by lhw5123** [comment]
我这里没能重现这个问题，使用模拟器、Smartian T2 和华为P8 都是可以显示通知的。app.js 中是这样写的：
![7rqsn8j11c3on5yux tid0](https://cloud.githubusercontent.com/assets/6531354/21039606/017a191e-be1a-11e6-98ef-0a7d2bc7d7b4.png)

**Comment by jeneser** [comment]
感谢！ @lhw5123

这就尴尬了-_-,我这边能提供的调试信息就这些了，难道我身边的手机都比较奇葩...
还是我的代码有问题？
我把仓库贴过来吧，大神如果不介意看我的烂代码的话。。。

https://github.com/jeneser/hpuHelper
