### ISSUE TITLE
cordova在线安装插件，手机接收不到推送的消息

### ISSUE THREAD

**Issue by cxpyear** [jpush/jpush-phonegap-plugin#185]
你好，我在终端中添加了jpush插件,并在app.js页面中添加了下面两行代码
window.plugins.jPushPlugin.init();
window.plugins.jPushPlugin.setDebugMode(true);
打包并安装apk文件。
为啥在极光推送后台发送通知，手机还是接收不到推送的消息呢

**Comment by lhw5123** [comment]
能看到日志吗？

**Comment by jeneser** [comment]
@lhw5123 

这个问题貌似和 #184 一个意思...
