### ISSUE TITLE
ios backgroundNotification 进入后台后无法调用

### ISSUE THREAD

**Issue by huigesv123** [jpush/jpush-phonegap-plugin#186]
IOS 9.3.5
XCODE Version 8.0 (8A218a)
已打开 background modes 的 Remote notifications
按HOME进入后台后，收到推送，但没触发backgroundNotification此方法，以下是用法
    var onBackgroundNotification = function(event) {
                       var alertContent; alertContent = event.aps.alert;
                       console.log("open Notificaiton:" + alertContent);
                       };
    document.addEventListener("jpush.backgroundNotification", onBackgroundNotification, false);

**Comment by pikacode** [comment]
服务端推送设置 payload 需要携带 content-available: 1，否则无法触发后台通知。详情参考 [iOS 7 Background Remote Notification](https://docs.jiguang.cn/jpush/client/iOS/ios_new_fetures/#ios-7-background-remote-notification)

**Comment by huigesv123** [comment]
@pikacode 我在 JPUSH控制台在content-available打了勾推送还是不行

**Comment by pikacode** [comment]
现有事件拼写有点点错误，现有是`jpush.backgoundNotification`，下周会修复。

**Comment by huigesv123** [comment]
@pikacode 这个还没解决？

**Comment by pikacode** [comment]
新版本已经解决

**Comment by keepJion** [comment]
进程杀死之后,收到远程通知,点击远程通知监听不到点击通知的事件!
