### ISSUE TITLE
添加插件后build ios报错

### ISSUE THREAD

**Issue by lliu123** [jpush/jpush-phonegap-plugin#189]
** BUILD FAILED **
The following build commands failed:
    Ld build/emulator/yqw.app/yqw normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/AX/yqw/platforms/ios/cordovaild-debug.xcconfig,-project,yqw.xcodeproj,ARCHS=i386,-target,yqw,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/AX/yqw/platforms/iosild/emulator,SHARED_PRECOMPS_DIR=/Users/AX/yqw/platforms/iosilddpch
Error: /Users/AX/yqw/platforms/ios/cordovaild: Command failed with exit code 2
请问怎么解决

**Comment by pikacode** [comment]
3.0.0及以上版本将不再支持处理器为i386的模拟器。

**Comment by lliu123** [comment]
请问下怎么解决呢，能用3.0.0之前的版本吗

**Comment by pikacode** [comment]
可以用3.0之前版本。该问题可至ionic官方论坛寻求技术支持。
