### ISSUE TITLE
phonegap build现在不再审核插件了

### ISSUE THREAD

**Issue by sunnylqm** [jpush/jpush-phonegap-plugin#19]
phonegap build现在对提交的插件不再进行审核，直接上传可用，且可以包含预编译的二进制文件，甚至不需要开源。
http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/
请极光官方赶紧提上日程吧！谢谢

**Comment by Chener** [comment]
对啊，现在到底 Phonegap Builld 上能不能用这个插件？请回答~

**Comment by zhangqinghe** [comment]
@Chener 现在还没有支持Phonegap  Builld 服务

**Comment by Chener** [comment]
@zhangqinghe 哎，只能找别的方法了。
