### ISSUE TITLE
JPushPlugin.prototype.receiveMessageIniOSCallback不见了？？？

### ISSUE THREAD

**Issue by GitMr** [jpush/jpush-phonegap-plugin#191]
document.addEventListener("jpush.receiveMessage", onReceiveMessage, false);
添加“jpush.receiveMessage”监听，在ios中收到推送事件没有响应？？？
看了最新的JPushPlugin.js中代码，发现JPushPlugin.prototype.receiveMessageIniOSCallback不见了。以前版本有。

**Comment by pikacode** [comment]
- 没有响应的问题已经在 master 上修复，可以更新插件重试一下。
- iOS 不推荐使用 receiveMessageIniOSCallback，因为作用重复，所以已经删掉了。建议使用监听 "jpush.receiveMessage" 事件的方式获取消息内容。

**Comment by GitMr** [comment]
It works! Thanks!
