### ISSUE TITLE
关于极光服务SDK建议

### ISSUE THREAD

**Issue by wilhantian** [jpush/jpush-phonegap-plugin#193]
因为`极光开发者服务SDK采用了模块化的使用模式，即一个核心（JCore）+N种服务（JPush，JAnalytics，...）的使用方式`，当cordova开发者需要安装多个极光服务时，会出现jcore.jar/jcore.a文件冲突情况。

故提议维护jpush插件的官方人员，新建一个插件依赖: cordova-plugin-jcore，其他插件使用`<dependency id="cordova-plugin-jcore" version="x.x.x">`进行依赖即可。

**Comment by javenfang** [comment]
非常好的建议！

感谢提出，我们会认真考虑与评估的。
