### ISSUE TITLE
监听jpush.openNotification，安卓上成功，ios上不调用对应的监听函数

### ISSUE THREAD

**Issue by cxpyear** [jpush/jpush-phonegap-plugin#194]
监听jpush.openNotification，安卓上成功，ios上不调用对应的监听函数

**Comment by pikacode** [comment]
移除插件，然后用 `cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey` 的方式安装插件再试一下。

**Comment by gusumuzhe** [comment]
我也遇到这个问题了，当程序在关闭的时候，通过通知打开程序时，jpush.openNotification并没有触发

**Comment by pikacode** [comment]
该问题已经在 dev 分支上修复，可以用以下命令安装插件（添加了#dev）：
```
cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git#dev --variable API_KEY=your_jpush_appkey
```
