### ISSUE TITLE
[iOS] getRegistrationID is empty

### ISSUE THREAD

**Issue by Alplob** [jpush/jpush-phonegap-plugin#195]
Hello,

Some of my iOS app users, not all, do not receive push notifications anymore.. After investigation, it seems that the result got from the function _getRegistrationID_ is empty..
And in my development environment even if I get registrationID, I could not receive notification anymore..

Thanks!

**Comment by pikacode** [comment]
you can try this way to install/update plugin
```
cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey  
```
if u still have this problem, you can get into gitter, and I will give you more support https://gitter.im/jpush/jpush-phonegap-plugin

**Comment by Alplob** [comment]
Ok, thanks for your reply. I am quite busy now and I am going on business trip... I will check this in 10 days...

**Comment by Alplob** [comment]
Hello, I wrote on message on gitter this morning to solve that problem, but I have not got any answer so far, thanks!

**Comment by pikacode** [comment]
solved on gitter.
