### ISSUE TITLE
ios监听事件不调用相应的回调函数

### ISSUE THREAD

**Issue by ywkobe** [jpush/jpush-phonegap-plugin#196]
ios监听jpush.receiveNotification事件不调用相应的回调函数，Android上可以

**Comment by pikacode** [comment]
建议尝试 url 方式安装插件
```
cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable API_KEY=your_jpush_appkey  
```

**Comment by ywkobe** [comment]
下载最新的插件后，ios前台jpush.receiveNotification可以使用，但是ios backgroundNotification后无法调用

**Comment by pikacode** [comment]
`jpush.backgroundNotification` 之前存在拼写错误，之前是 `jpush.backgoundNotification` 少了一个 `r`，现已修正。

**Comment by ywkobe** [comment]
我用的是这个啊，没写错啊  document.addEventListener("jpush.backgroundNotification", function (event)

**Comment by ywkobe** [comment]
@pikacode 还是接收不到这个事件啊

**Comment by pikacode** [comment]
后台通知需要想要配置 具体参考 [API](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#event---jpushbackgroundnotification)

**Comment by ywkobe** [comment]
@pikacode ,按照上面的配置了，ion在前台运行时执行了两次jpush.receiveNotification"前台通知事件，后台还是收不到jpush.backgroundNotification通知事件

**Comment by pikacode** [comment]
加qq57380422，帮你看看咯

**Comment by ninechung** [comment]
我也遇到了这个问题，是用的最新的dev版本。而且其它通知和消息事件我只有在app.component.ts文件里监听，才有效。。在另外一个页面类里，监听不到。。另外，我生成了ionic-native后，调用不起来，只能addEventListener?
