### ISSUE TITLE
ios生产环境，收不到推送通知，配置都是成功的

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#198]

**Comment by pikacode** [comment]
- 开发环境是否能收到推送通知
- 用控制台推送或者用 API 推送都可以在 控制台推送历史里 查看推送结果的详细信息

**Comment by xgzl87** [comment]
推送历史里显示的是成功

**Comment by pikacode** [comment]
生产环境需要修改 Pushconfig.plist 文件中的 isProduction 字段为 YES

**Comment by xgzl87** [comment]
好的，我试试

**Comment by xgzl87** [comment]
线上的还是不行，收不到通知，RegistrationId都是成功的。isProduction 也修改过了，
但是通过jpush官网的测试推送 ios生产环境是可以收到消息的

**Comment by xgzl87** [comment]
解决了 是后台发送的参数问题

**Comment by huangzk** [comment]
后台发送参数有什么问题吗。我最近也是发送成功，但是客户端收不到。。@xgzl87
