### ISSUE TITLE
iOS jpush.backgroundNotification 不触发

### ISSUE THREAD

**Issue by gusumuzhe** [jpush/jpush-phonegap-plugin#199]
在自己的机器上无法触发，最后发现JPushDefine.h 中对 JPushDocumentEvent_BackgroundNotification 的定义 @"backgroundNotification"，实际的值是 backg\boundNotification，导致事件无法触发，忘作者修改下这个问题

**Comment by pikacode** [comment]
已经注意到这个问题了。。在 Xcode 编译器中显示是正常的，可能是输入的时候不小心按了什么特殊字符，显示不出来。
