### ISSUE TITLE
iOS 添加插件失败 报错 buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

### ISSUE THREAD

**Issue by FallingWood** [jpush/jpush-phonegap-plugin#202]
当我添加插件时报错buildSettings.LIBRARY_SEARCH_PATHS.push is not a function。   具体如下  Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.
Error during processing of action! Attempting to revert...
Failed to install 'jpush-phonegap-plugin':TypeError: Uh oh!
buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

**Comment by pikacode** [comment]
- 升级 Xcode
- 升级 Cordova
- 移除插件，安装插件
