### ISSUE TITLE
这个插件不支持i386架构么! 在iphone5 上面运行报错

### ISSUE THREAD

**Issue by keepJion** [jpush/jpush-phonegap-plugin#203]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate+JPush.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in JPushPlugin.o
      objc-class-ref in AppDelegate+JPush.o
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in JPushPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
希望您能解决下!谢谢

**Comment by pikacode** [comment]
不再支持 i386。「在iphone5 上面运行报错」你指的是 iPhone 5 模拟器，而不是 iPhone 5 真机吧。iPhone 5 真机不是 i386。
