### ISSUE TITLE
添加配置

### ISSUE THREAD

**Issue by aniy00** [jpush/jpush-phonegap-plugin#204]
请问下载最新版插件需要在AppDelegate.m 添加oc代码吗？
如果需要请问有demo吗？
谢谢！

**Comment by pikacode** [comment]
- 不需要，请参照 [readme](https://github.com/jpush/jpush-phonegap-plugin) 安装插件即可
- 有，[demo](https://github.com/jpush/jpush-phonegap-plugin#demo)
- 各种资源在 readme 中都有列出，请仔细查阅

**Comment by aniy00** [comment]
你好，我现在用demo是推送不到的，但是在AppDelegate.m中添加官方的代码是可以推送的到，这是什么原因，我需要检查哪些东西？
我这边已经按照readme中说明，添加了插件

**Comment by pikacode** [comment]
在 JPushConfig.plist 文件设置 IsProduction 是否为生产环境，推送时指定对应环境。

**Comment by aniy00** [comment]
不是生产环境，但是我测试的时候2个环境都测试了，都一样

**Comment by pikacode** [comment]
- 2个环境在AppDelegate.m中添加官方的代码 都可以收到推送，用 demo 都收不到推送。是这个意思吗？
- 是否安装的是最新的插件？
- 检查 PushConfig.plist 中的 appkey 字段，是否跟你的 appkey 一样。

**Comment by aniy00** [comment]
你好，appkey是一样的
我是用开发环境的，添加官方的代码，可以收的到
用demo  开发环境和生产环境都发了，收不到

**Comment by leason00** [comment]
用命令安装插件 还要手动去改config。xml中的appkey吗

**Comment by pikacode** [comment]
如果一样就不改，不一样就改成你自己的 appkey。
