### ISSUE TITLE
demo的疑问

### ISSUE THREAD

**Issue by aniy00** [jpush/jpush-phonegap-plugin#205]
你好，我下载了jpush-phonegap-plugin 3.0.2 ,使用时发现JPushPlugin.js没有请求startJPushSDK，
JPushPlugin.m中startJPushSDK，也没有在初始化的时候被调用到，请问这是遗漏了吗，还是我理解错了

**Comment by pikacode** [comment]
JPushConfig.plist 中设置 delay
NO，不延迟启动 SDK，App 启动的时候自动启动 SDK
YES，延迟手动启动 SDK，手动调用 startJPushSDK 启动

**Comment by aniy00** [comment]
你好，demo设置alias  设置结果显示result code :6002 tags:  alias:aa   这是什么错误

**Comment by pikacode** [comment]
- API 调用及说明请参阅 [API 文档](https://github.com/jpush/jpush-phonegap-plugin#api)
- [错误码定义](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#错误码定义)

**Comment by aniy00** [comment]
6002	设置超时	建议重试。
重试了好几遍还是这样，网络是通的，推送所有人是通的

**Comment by aniy00** [comment]
你好，我这边可能是什么原因会出现这种情况

**Comment by pikacode** [comment]
之前好像是服务器问题已经修复，现在是否还有同样问题。
