### ISSUE TITLE
IOS APP关闭后收到消息 jpush.backgroundNotification 不触发

### ISSUE THREAD

**Issue by archangellcc** [jpush/jpush-phonegap-plugin#206]
IOS APP关闭后，不在后台运行，可以收到消息，但对应的 jpush.backgroundNotification 事件不触发，但当APP在后台运行时，可以收到消息且 jpush.backgroundNotification 事件触发。不知道这样是不是正常的。若是正常的，那么当APP关闭后，收到消息，如何做对应的处理？

**Comment by chy89310** [comment]
@archangellcc 我也有同样的疑问，想问下解决了么
