### ISSUE TITLE
极光cordova插件ios坑多：Push Notifications 开关问题，应用运行时收不到推送问题，角标＋1，与点击后清除问题，好多坑！

### ISSUE THREAD

**Issue by hefanhappy** [jpush/jpush-phonegap-plugin#207]
http://www.jianshu.com/p/02ac579e3bde
http://blog.sina.com.cn/s/blog_134451adb0102wc31.html

**Comment by pikacode** [comment]
@hefanhappy @所有使用本插件的开发者
如果你愿意的话：
- 花 2 分钟时间看一下 [readme](https://github.com/jpush/jpush-phonegap-plugin)，了解一下这个插件提供那些资源（安装、demo、API文档、常见问题、交流群）
- 花 30 秒浏览一下 [API 文档](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md) 顶部的目录结构，了解一下都有哪些可用的 API

大多数情况下，花这 2 分 30 秒时间，可以解决开发者 80% 以上的「坑」，节约开发时间 1~2 个工作日以上（根据跟多位开发者的交流情况来看，很多童鞋浪费了 2 天以上在自己瞎折腾、各种百度看2年前的文章、加群到处问问题）。
