### ISSUE TITLE
ionic build ios 编译报错 　jpush3。0 ，谢谢帮忙看下

### ISSUE THREAD

**Issue by coolara** [jpush/jpush-phonegap-plugin#209]
ld: warning: ignoring file /Users/apple/Desktop/580pocket1.1.0/platforms/ios/580口袋/Plugins/jpush-phonegap-plugin/jpush-ios-3.0.0.a, missing required architecture i386 in file /Users/apple/Desktop/580pocket1.1.0/platforms/ios/580口袋/Plugins/jpush-phonegap-plugin/jpush-ios-3.0.0.a (4 slices)
ld: warning: ignoring file /Users/apple/Desktop/580pocket1.1.0/platforms/ios/580口袋/Plugins/jpush-phonegap-plugin/jcore-ios-1.0.0.a, missing required architecture i386 in file /Users/apple/Desktop/580pocket1.1.0/platforms/ios/580口袋/Plugins/jpush-phonegap-plugin/jcore-ios-1.0.0.a (4 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate+JPush.o
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[JPushPlugin initPlugin] in JPushPlugin.o
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in JPushPlugin.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in JPushPlugin.o
      objc-class-ref in AppDelegate+JPush.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pikacode** [comment]
参考[这里](http://cordova.apache.org/docs/en/6.x/guide/platforms/ios/index.html#page-toc-source)，或者尝试 cordova platfrom update ios
