### ISSUE TITLE
Xcode8 安装插件没有打开工程 Capabilities 下的 Push Notification 开关

### ISSUE THREAD

**Issue by snipking** [jpush/jpush-phonegap-plugin#210]
需要修改 xxx.xcodeproj/project.pbxproj，改写 SystemCapabilities 加入类似如下内容以解决该问题。

```
SystemCapabilities = {
	com.apple.Push = {
		enabled = 1;
	};
};
```

**Comment by jackyxxu** [comment]
太蛋疼了，这么明显的问题怎么一直不修啊...

**Comment by pikacode** [comment]
这是推送的基本配置，打开 Xcode 点开 Push 开关即可。

**Comment by jackyxxu** [comment]
一般都是一句cordova build ios完成编译打包的，每次新生成工程都手动开打开关的话CI都用不了了。

**Comment by snipking** [comment]
@pikacode 道理很简单，但是如果要用 CI 就很麻烦了。

我写了一个 nodejs 脚本来启用这个功能，不过目前还不是很通用，我修改修改后传上来作为一个 after hook，应该就能解决了。

**Comment by diegozhu** [comment]
after hook 呢？

**Comment by shikelong** [comment]
+1.. CI hen dan teng..

**Comment by shikelong** [comment]
@snipking

**Comment by snipking** [comment]
今年太忙一直在赶进度，我端午节搞定 @diegozhu @shikelong

**Comment by diegozhu** [comment]
@snipking   many thanks.

hook加了之后只能开启一半。step 1 是ok的。 2 add the push notifications entitlement to your entitlements file 挂了。。

我自己尝试解决。 cordova build 了之后， git commit * , 然后打开xcode，点fix， 再git diff， 发现xcode会在 platforms/ios/XXX.xcodeproj/project.pbxproj
中：
/* Begin XCBuildConfiguration section */
后面， COPY_PHASE_STRIP = NO;之前加一行 CODE_SIGN_ENTITLEMENTS = "心脑血管家庭关护/心脑血管家庭关护.entitlements";

两个地方。 一个是debug一个是release。 以及project.pbxproj其他几个地方添加了好多其他我看不懂的内容。



Xcode Version 8.3.2 (8E2002)
cordova -v 7.0.1
npm -v 5.3.0
macOS 10.12.3
cordova-ios 4.4.0

**Comment by diegozhu** [comment]
@snipking any thoughts ?

**Comment by snipking** [comment]
@diegozhu add plugin 的时候打印的日志帖来看一下

**Comment by snipking** [comment]
还有确认一下你的 platform ios 是 4.3.0 以上，entitlements 应该是直接读取 ios 工程根目录下面的 Debug-Entitlements.plist 和 Release-Entitlements.plist
