### ISSUE TITLE
监听事件的几个疑问

### ISSUE THREAD

**Issue by ninechung** [jpush/jpush-phonegap-plugin#212]
目前的状态：
1）已经配置remote notifications和push notifications。
2）本插件用的最新的dev版本
3）ionic 2.0.1
4）监听openNotification事件正常
5）监听receiveNotification事件正常
6）dev版本的问题和master版本差不多
7）使用了ionic-native project生成ionic-native的JPush（我自己参照本插件的接口生成的，init、setAlias、setTags等正常）
8）真机调试iOS10.2.1
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2 Build version 8C38

Q1、只能在APP活动时才能接收到自定义消息吗？
iOS回到桌面后。再推送自定义消息，receiveMessage没有任何反应。

Q2、backgroundNotification没有触发事件，方法按照文档写的。

Q3、我在app.componnent.ts里监听有效，在另外一个Page类里，所有监听（包括上文提到的4、5点）都不可触发。

Q4、remote notifications是不是要设置info.plist项才有效果？

**Comment by pikacode** [comment]
Q1：是
Q2：用 url 安装的方式重新安装插件
Q3：可能是你的代码需要调整
Q4：如何使用 Remote Notification 文档里有说明 [Remote Notification](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#后台收到推送)

**Comment by ninechung** [comment]
Q2: 用url安装不了，我是下载了包，然后覆盖本地目录安装的。然后重新生成了platforms的。
Q3: 这个问题很奇怪。我试了把第一次监听放在HomePage、ChatPage，但是进入HomePage时，不会触发事件。进入ChatPage后，两个页面类的监听都能触发。
Q4: 我之前已经明确按文档配置了，上文第一条就提出已经配置了remote notifications和push notifications。哎，好奇怪！

**Comment by ninechung** [comment]
能不能把Demo里的示例扩充完整？？只有一个init的示例，好坑。
