### ISSUE TITLE
APP在前台时，iOS的通知仍然弹出显示了

### ISSUE THREAD

**Issue by ninechung** [jpush/jpush-phonegap-plugin#213]
我看其它APP在前台时，如果有通知，都是APP内部处理，不弹出提示了，弹出的提示也是APP内部的，不是系统的通知提示。。请问这个是因为生产环境和开发环境的差异导致的？还是需要做什么配置？

**Comment by pikacode** [comment]
App 在前台时展示横幅这是 iOS 10 的新特性，如果要更改需要手动修改原生代码。

**Comment by ninechung** [comment]
可以告知需要改哪一段吗？

**Comment by pikacode** [comment]
参照 https://docs.jiguang.cn/jpush/client/iOS/ios_guide_new/#_6
「添加处理APNs通知回调方法」部分的代码
