### ISSUE TITLE
iOS10.2版本里不能获取registrationId

### ISSUE THREAD

**Issue by robert-luoqing** [jpush/jpush-phonegap-plugin#214]
环境： ionic2
代码如下： 
`var plugins = window['plugins'];
      if (plugins) {
        var jpush = plugins.jPushPlugin;
        if (jpush) {
          jpush.setDebugMode(true);
          jpush.init();
          window.setTimeout(()=>{
            jpush.getRegistrationID(function (data) {
              console.log("JPushPlugin:registrationID is " + data)
            })
          }, 1000);
        }
      }
`
结果是：
017-02-28 15:57:03.200019 携运网[8222:3824041] Action - registrationID
2017-02-28 15:57:03.230958 携运网[8222:3824002] THREAD WARNING: ['JPushPlugin'] took '46.494873' ms. Plugin should use a background thread.
2017-02-28 15:57:03.280035 携运网[8222:3824002] JPushPlugin:registrationID is

使用的版本是：
  "name": "jpush-phonegap-plugin",
  "version": "3.0.3",

**Comment by robert-luoqing** [comment]
找到原因了
要把JpPushConfig.plist的Delay设为false

**Comment by pikacode** [comment]
JPushConfig.plist 中 Delay 的值文档中有详细说明，并且默认值是 false。
[延迟注册和启动推送通知服务](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#延迟注册和启动推送通知服务)
