### ISSUE TITLE
后台删除alias后，客户端无法再次设置alias

### ISSUE THREAD

**Issue by nouh** [jpush/jpush-phonegap-plugin#215]
当客户端登录设置好alias后，如果后端通过rest api删除了这个alias，那么这个客户端再次设置同一个alias再也无法成功，但是先设置一次别的alias，再设回原来那个alias却是可以的。

**Comment by pikacode** [comment]
设置tagalias的接口调用频率是5s以上，低于5s就会报6002超时
极光后台在短时间内不允许对同个设备重复设置别名和标签
2小时内，不支持对同个regid设置相同tag、alias值；
5s内也不支持对同个regid设置不同tag、alias值

如果是设置相同的，会直接返回成功，如果超频（5s内）会直接丢弃，客户端就是收不到响应
