### ISSUE TITLE
请问推送插件的铃声如何重定义？

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#216]

**Comment by lhw5123** [comment]
Android 还是 iOS ？

**Comment by xgzl87** [comment]
麻烦都说明下吧

**Comment by DarrenHou1993** [comment]
同问

**Comment by huangminlinux** [comment]
iOS 只需要把音频文件放到工程里面， 当后台推送的时候有一个 sound 字段，这个字段设为音频文件的名字即可

**Comment by DarrenHou1993** [comment]
@huangminlinux ios的这个了解。 现在就是安卓的不会弄。有便捷的方法设置啥的吗。

**Comment by lhw5123** [comment]
Android 目前暂不支持自定义铃声。可以选择发送自定义消息，在收到消息时使用[这款插件](https://github.com/katzer/cordova-plugin-local-notifications)，来触发本地通知。

**Comment by DarrenHou1993** [comment]
@lhw5123 大哥 发送自定义消息的话 只能前台接口到通知。还有别的选择吗

**Comment by DarrenHou1993** [comment]
配合 backgroundMode 这个插件 已经达到功能了。

**Comment by xgzl87** [comment]
...就为了改个铃声，累死了
