### ISSUE TITLE
ios 获取极光插件的问题

### ISSUE THREAD

**Issue by yuzhenApril** [jpush/jpush-phonegap-plugin#217]
安卓端已调试通。  iOS 端调用(<any>window).plugins.jPushPlugin 是个空对象。似乎是插件没注入进去。但是，当使用ionic run -l -c 实时调试的时候就可以调用到这个插件，实时调试前端服务是启在电脑的。。很奇怪。这两者的区别就在于前端服务是启在电脑端还是手机端。

**Comment by lhw5123** [comment]
推送插件只能在手机端使用，电脑端的话是不行的。
