### ISSUE TITLE
IOS上build报错

### ISSUE THREAD

**Issue by xupx1993** [jpush/jpush-phonegap-plugin#219]
duplicate symbol _SharedJPushPlugin in:
.../Objects-normal/arm64/JPushPlugin.o
.../Objects-normal/arm64/AppDelegate+JPush.o
ld: 1 duplicate symbol for architecute arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
删除插件，重新安装试试
