### ISSUE TITLE
在-(void)applicationDidLaunch:(NSNotification *)notification方法中怎么使用了只有iOS10才能用的API？

### ISSUE THREAD

**Issue by youshaoduo** [jpush/jpush-phonegap-plugin#220]
-(void)applicationDidLaunch:(NSNotification *)notification{

    if (notification) {
        if (notification.userInfo) {
            NSDictionary *userInfo1 = [notification.userInfo valueForKey:UIApplicationLaunchOptionsRemoteNotificationKey];
            if (userInfo1.count > 0) {
                [NSTimer scheduledTimerWithTimeInterval:0.1 repeats:YES block:^(NSTimer * _Nonnull timer) {
                    if (SharedJPushPlugin) {
                        [JPushPlugin fireDocumentEvent:JPushDocumentEvent_OpenNotification jsString:[userInfo1 toJsonString]];
                        [timer invalidate];
                    }
                }];
            }
            NSDictionary *userInfo2 = [notification.userInfo valueForKey:UIApplicationLaunchOptionsLocalNotificationKey];
            if (userInfo2.count > 0) {
                [NSTimer scheduledTimerWithTimeInterval:0.1 repeats:YES block:^(NSTimer * _Nonnull timer) {
                    if (SharedJPushPlugin) {
                        [JPushPlugin fireDocumentEvent:JPushDocumentEvent_OpenNotification jsString:[userInfo2 toJsonString]];
                        [timer invalidate];
                    }
                }];
            }
        }
        [JPUSHService setDebugMode];

        NSString *plistPath = [[NSBundle mainBundle] pathForResource:JPushConfig_FileName ofType:@"plist"];
        NSMutableDictionary *plistData = [[NSMutableDictionary alloc] initWithContentsOfFile:plistPath];
        NSNumber *delay       = [plistData valueForKey:JPushConfig_Delay];

        _launchOptions = notification.userInfo;

        if (![delay boolValue]) {
            [self startJPushSDK];
        }
    }
}

NSTimer scheduledTimerWithTimeInterval:0.1 repeats:YES block这个函数在iOS10及以上版本才能用，低于iOS10的手机点击推送就会崩溃。

**Comment by pikacode** [comment]
你好，我去确认一下这个问题

**Comment by youshaoduo** [comment]
App在没有运行的情况下点击推送就会崩溃。

**Comment by pikacode** [comment]
正在修复这个问题。

**Comment by pikacode** [comment]
@youshaoduo 你好，bug 修复了，用 url 安装方式重新安装试一下。
