### ISSUE TITLE
cordova-plugin-jcore 中的jar 包为何没有同步更新？

### ISSUE THREAD

**Issue by REBOOTERS** [jpush/jpush-phonegap-plugin#221]
[cordova-plugin-jcore](https://github.com/jpush/cordova-plugin-jcore/tree/master) 中jar 包已经升级到v1.1.1 版本，为何我现在安装此插件后，依赖插件cordova-plugin-jcore 中jcore-android_v1.1.0.jar 没有同步更新？master 分支内容为何没有做同步更新？npm  仓库中的cordova-plugin-jcore 请及时更新。

**Comment by lhw5123** [comment]
已更新。: )
