### ISSUE TITLE
xcode控制台可以看到RegistrationID，但是window.plugins.jPushPlugin.getRegistrationID却是undefined

### ISSUE THREAD

**Issue by rayeyeued** [jpush/jpush-phonegap-plugin#222]
1.卸载再安装插件会报"APP_KEY不能为空",这个是因为重装之后JPUSHConfig.plist里面的app_key还是空的
2.获取RegistrationID是undefined，但是xcode的控制台可以看到这个RegistrationID，推送也是成功的

**Comment by pikacode** [comment]
1.安装插件的命令需要附带 appkey 参数，具体可以参照 (readme - install)[https://github.com/jpush/jpush-phonegap-plugin#install]
2.获取 RegistrationID 方法可以参照 (readme - demo)[https://github.com/jpush/jpush-phonegap-plugin#demo]

**Comment by rayeyeued** [comment]
我肯定带了app_key的参数啊，第一次安装插件JPUSHConfig.plist里面的app_key是好的，卸载再安装就是空的了，第一个问题我已经找到了，我是问第二个问题的，上一个版本是好的，这个版本android还是可以获取到RegistrationID，ios获取不到

**Comment by pikacode** [comment]
获取 RegistrationID 方法可以参照 [readme - demo](https://github.com/jpush/jpush-phonegap-plugin#demo)
