### ISSUE TITLE
iOS集成问题

### ISSUE THREAD

**Issue by niwenk** [jpush/jpush-phonegap-plugin#223]
duplicate symbol _SharedJPushPlugin in:
    /Users/andy/Library/Developer/Xcode/DerivedData/IOSPKUfiProject-buuwhvygyxwlmfgjtaikrbhxugbo/Build/Intermediates/IOSPKUfiProject.build/Debug-iphoneos/IOSPKUfiProject.build/Objects-normal/arm64/AppDelegate+JPush.o
    /Users/andy/Library/Developer/Xcode/DerivedData/IOSPKUfiProject-buuwhvygyxwlmfgjtaikrbhxugbo/Build/Intermediates/IOSPKUfiProject.build/Debug-iphoneos/IOSPKUfiProject.build/Objects-normal/arm64/JPushPlugin.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
删除插件，重新安装试试

**Comment by fish-ball** [comment]
@niwenk @huangminlinux 同样问题，重装无效，请问最终解决了吗

**Comment by niwenk** [comment]
最后jpush 我用pod 'jpush' 集成的 jpush的cordova插件是我手动添加的，可能是jpush的依赖关系的问题

**Comment by huangminlinux** [comment]
@niwenk 这样会导致代码冲突的，  pod  和 cordova 含有相同的代码会出现命名错误， 删掉一个试试

**Comment by niwenk** [comment]
cordova项目我不用命令创建，是纯手动创建的

**Comment by huangminlinux** [comment]
@fish-ball 这个命名重复错误， 检查一下是不是有重复的库文件，要只留一个

**Comment by huangminlinux** [comment]
@niwenk  如果你的 cordova 已经成功集成了 jpush， 你可以删掉 cocoapod 的集成方式

**Comment by Jerry-0425** [comment]
一样的问题, 重新卸载/安装了几次还是编译报一样的错误, 插件版本也是最新的.
