### ISSUE TITLE
import { JPush } from ‘ionic-native’

### ISSUE THREAD

**Issue by leif123** [jpush/jpush-phonegap-plugin#225]
import { JPush } from ‘ionic-native’
问题:不识别ionic-native
我用的ionic2版本2.2.2

**Comment by leif123** [comment]
还要有个npm install --save @ionic-native/...  吗

**Comment by lhw5123** [comment]
JPush 插件目前没有加入 ionic-native，所以不能通过 ionic-native 引入。
可以直接用 window.plugins.jPushPlugin.xxx 来使用。

**Comment by kongdewen1994** [comment]
@leif123 试下 https://github.com/kongdewen1994/ionic2-jpush-cordova-plugin
