### ISSUE TITLE
清除角标后，收到新的推送角标会在原来的基础上累加。

### ISSUE THREAD

**Issue by huangzk** [jpush/jpush-phonegap-plugin#226]
window.plugins.jPushPlugin.setApplicationIconBadgeNumber(badge)。
比如：角标5，调用上边的方法清掉角标，当新的推送过来的时候，角标就变成6了。。再清除，新的推送过来又变成7.。不应该是从1开始吗。服务端代码
        .addPlatformNotification(IosNotification.newBuilder()
                                .incrBadge(1)
                                .addExtras(extra).build())
                        .build())
incrBadg(1)没有问题吧。

**Comment by huangminlinux** [comment]
推送过来 badge 这个值是又服务器那边下发的，极光服务器端会存有一个 badge 值， 这个值用于用户记录 app 当前的badge， 所以只改了本地的还不行。还需要调用下面的方法

```
setBadge(badge)
```
