### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by gonnavis** [jpush/jpush-phonegap-plugin#227]
按照readme里 

cordova platform update ios  和 
升级至 Xcode 8
先删除插件、再重装插件
先使用 cordova platform add ios，后使用 cordova plugin add
都不行， 

一 cordova build ios 就报错，提示里有 Undefined symbols for architecture i386 之类的。
请问是什么情况啊？

**Comment by huangminlinux** [comment]
模拟器的话需要使用  iphone5s 以上的模拟器，  真机没有限制

**Comment by gonnavis** [comment]
@huangminlinux  Mac  iphone6sp 都是真机， 没用模拟器。

**Comment by huangminlinux** [comment]
有完整错误信息吗？

**Comment by huangminlinux** [comment]
如果用xcode 的话 不需要 cordova build ios，  而且 cordova build ios   需要在 cordova platform add ios 之后调用。

我这边没有问题

**Comment by gonnavis** [comment]
嗯 是 add 后再 build 的， 完整错误信息

Ld build/emulator/HelloCordova.app/HelloCordova normal i386
    cd /Users/vis/Documents/cordova/jpush/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -L/Users/vis/Documents/cordova/jpush/platforms/ios/build/emulator -L/Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/cordova-plugin-jcore -L/Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/jpush-phonegap-plugin -F/Users/vis/Documents/cordova/jpush/platforms/ios/build/emulator -filelist /Users/vis/Documents/cordova/jpush/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/HelloCordova.LinkFileList -mios-simulator-version-min=6.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vis/Documents/cordova/jpush/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/HelloCordova_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/vis/Documents/cordova/jpush/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova.app.xcent -framework AssetsLibrary /Users/vis/Documents/cordova/jpush/platforms/ios/build/emulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -lz /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/cordova-plugin-jcore/jcore-ios-1.1.3.a /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/jpush-phonegap-plugin/jpush-ios-3.0.2.a -weak_framework CFNetwork -weak_framework CoreFoundation -weak_framework CoreTelephony -weak_framework SystemConfiguration -weak_framework Foundation -weak_framework UIKit -weak_framework Security -weak_framework AdSupport -weak_framework UserNotifications -weak-lresolv -Xlinker -dependency_info -Xlinker /Users/vis/Documents/cordova/jpush/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/HelloCordova_dependency_info.dat -o /Users/vis/Documents/cordova/jpush/platforms/ios/build/emulator/HelloCordova.app/HelloCordova
ld: warning: ld: warning: ignoring file /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/jpush-phonegap-plugin/jpush-ios-3.0.2.a, missing required architecture i386 in file /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/jpush-phonegap-plugin/jpush-ios-3.0.2.a (4 slices)ignoring file /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/cordova-plugin-jcore/jcore-ios-1.1.3.a, missing required architecture i386 in file /Users/vis/Documents/cordova/jpush/platforms/ios/HelloCordova/Plugins/cordova-plugin-jcore/jcore-ios-1.1.3.a (4 slices)

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate+JPush.o
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[JPushPlugin initPlugin] in JPushPlugin.o
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in JPushPlugin.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in JPushPlugin.o
      objc-class-ref in AppDelegate+JPush.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/HelloCordova.app/HelloCordova normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/vis/Documents/cordova/jpush/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/vis/Documents/cordova/jpush/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/vis/Documents/cordova/jpush/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/vis/Documents/cordova/jpush/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/vis/Documents/cordova/jpush/platforms/ios/cordova/build: Command failed with exit code 2

**Comment by huangminlinux** [comment]
用 xcode 编译试试

**Comment by gonnavis** [comment]
试了不 build,  add ios 后直接 xcode 里运行也不行,

**Comment by gonnavis** [comment]
重新 plugin remove/add 后, 现在不停循环 onGetRegistrationID 并提示 JPushPlugin:registrationID is , 后面没东西, 没有拿到id.

**Comment by gonnavis** [comment]
试了 build 依然报错, 还是不停循环  onGetRegistrationID 并提示 JPushPlugin:registrationID is , 后面没东西, 没有拿到id.

**Comment by huangminlinux** [comment]
你现在的问题是  编程出问题，还是运行的时候出问题了，  我看你签名的错误是编译就没有通过。

onGetRegistrationID 没有获得 id 应该是运行时的问题

**Comment by gonnavis** [comment]
因为 build 没通过, 但是 add 没问题, 所以想直接 add 后跑一下试试, 但是试下来不行.

**Comment by gonnavis** [comment]
您这边也说 "用 xcode 编译试试" , xcode 编译指什么? 我理解就是直接运行

**Comment by gonnavis** [comment]
我也希望能先解决 build 报错问题, 不知道通过报错信息, 您这边能看出是什么问题吗? 多谢了!

**Comment by huangminlinux** [comment]
错误是试图编译 i386 arch 上的 app， 不过确实不知道什么原因导致的。

onGetRegistrationID 问题，具体可以加我 Q 讨论一下： 380108184

**Comment by alonehover** [comment]
遇到了同样的问题，请问最后怎么解决的？

**Comment by gonnavis** [comment]
@alonehover 报错不用管, 实际已经编译好可以正常工作了.

**Comment by alonehover** [comment]
@gonnavis 我只有在打release包的时候才会遇到，找到解决的方法是在cordova 的build 命令里加个参数 `cordova build ios --release --device`，这样就没有再报错了，我用的Cordova版本是7.0.1
