### ISSUE TITLE
node服务器推送离线用户问题

### ISSUE THREAD

**Issue by kongdewen1994** [jpush/jpush-phonegap-plugin#229]
node服务器推送离线用户，服务器推送不在线的用户时，用户再次登陆后无法接收到推送，如果用户在线时，服务器推送就能接收到服务器推送来的信息

**Comment by lhw5123** [comment]
是用的官方的 node 客户端吗？

**Comment by kongdewen1994** [comment]
就是官方提供的node-serverSDK，只有用户在线时发送，客户端才接受到，不在线时推送，等用户再次打开app却没有推送

**Comment by lhw5123** [comment]
用的插件版本是多少？

**Comment by kongdewen1994** [comment]
客户端是最新的版本

**Comment by lhw5123** [comment]
有测试过用官网的控制台推送吗？

**Comment by kongdewen1994** [comment]
控制台正常，无论发送时离线还是在线，再次打开app连上极光后都能正常接收到推送

**Comment by lhw5123** [comment]
方便把使用的推送代码贴上来吗？

**Comment by kongdewen1994** [comment]
var JPush = require("jpush-sdk");
var client = JPush.buildClient('xxx', 'xxx');

function jp(title, conttext, alias) {
	client.push().setPlatform('ios', 'android')
		.setAudience(JPush.alias(alias))
		.setNotification('吃乎通知',
			JPush.android(conttext, title, 1, {
				'key': 'value'
			}),
			JPush.ios(conttext, 'sound', 1)
		)
		.setMessage('msg content')
		.send(function(err, res) {
			if(err) {
				if(err instanceof JPush.APIConnectionError) {
					console.log("APIConnectionError:" + err.message);

				} else if(err instanceof JPush.APIRequestError) {
					console.log(err.message);
				}
			} else {

				console.log('Msg_id: ' + res.msg_id);
			}
		});
}

jp("通知", "内容", "推送的用户id");

**Comment by lhw5123** [comment]
我这里测试了下，用 node sdk 推送没有出现这个问题。可以试下 `setOptions(null, 86400)` 设置离线消息保存时间：
```javascript
...
.setMessage('msg content')
.setOptions(null, 86400)
.send(...)
```
