### ISSUE TITLE
附加字段的自定义消息，json格式问题 

### ISSUE THREAD

**Issue by bensonning** [jpush/jpush-phonegap-plugin#23]
{
    "message": "a",
    "extras": {
        "cn.jpush.android.MSG_ID": "941365619",
        "cn.jpush.android.EXTRA": "{"b":"c"}",
        "cn.jpush.android.CONTENT_TYPE": ""
    }
}
这个是通过控制台发送的 一条 自定义 附加字段的信息
添加字段b 内容 为c

这一行的 json 在JSON.parse() 会报错
是不是应该 去掉 extra 后面那个大括号的 双引号
"cn.jpush.android.EXTRA": {"b":"c"},

**Comment by zhangqinghe** [comment]
@bensonning  从native sdk中出来的数据结构就是"cn.jpush.android.EXTRA": "{"b":"c"}"，导致插件传递给js时就多了个双引号，我正在想办法解决这个问题。

**Comment by bensonning** [comment]
嗯 谢谢
刚才 我看论坛还有其它人也在问这个问题 了

**Comment by zhangqinghe** [comment]
please see #21
