### ISSUE TITLE
与百度定位插件冲突

### ISSUE THREAD

**Issue by zhouhaolaoda** [jpush/jpush-phonegap-plugin#232]
与百度定位插件同时使用，百度定位无法正常使用

**Comment by huangminlinux** [comment]
android 还是 ios ？

**Comment by zhouhaolaoda** [comment]
目前只测试了android，好像只有6.+的版本会冲突

**Comment by lhw5123** [comment]
参考下这个链接：https://community.jiguang.cn/t/anroid-apk-baidu-sdk/11668/6
手动修改下 /platform/android 中的 so 文件
