### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by luyingjia** [jpush/jpush-phonegap-plugin#236]
Error: npm: Command failed with exit code 194 Error output:
npm ERR! path /Users/cetc-server/yunhuizhen2/node_modules/cordova-plugin-jcore/package.json
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/Users/cetc-server/yunhuizhen2/node_modules/cordova-plugin-jcore/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cetc-server/.npm/_logs/2017-06-06T03_23_42_016Z-debug.log

**Comment by lhw5123** [comment]
我这里测试了下是 ok 的，clean npm cache 试下。

**Comment by Tneciv** [comment]
同样的问题 clean cache没用

**Comment by zim-lee** [comment]
我的安装不报错，但是注册一直失败，报class找不到，如@Tneciv 所说，降低cordova到6.5就行了，希望官方能够解决这个问题

**Comment by lhw5123** [comment]
@zim-lee 是 Android 中出现的问题吗？

**Comment by zim-lee** [comment]
@lhw5123 是的

**Comment by lhw5123** [comment]
@luyingjia 这个问题初步推测是 cordova 7 的 bug。目前在安装插件和添加 platform 的时候先在命令后面加上 --nofetch。

**Comment by giscafer** [comment]
```

[ERROR] An error occurred while running cordova plugin add jpush-phonegap-plugin --variable APP_KEY=e874f264e3bd4572cbcc... (exit code 1):

        Installing "jpush-phonegap-plugin" for android
        Plugin dependency "cordova-plugin-device@1.1.4" already fetched, using that version.
        Dependent plugin "cordova-plugin-device" already installed on android.
        Failed to install 'jpush-phonegap-plugin': CordovaError: Failed to fetch plugin cordova-plugin-jcore via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "node_modules\cordova-plugin-jcore" as it does not contain a package.json file.
```

同样报错

cordova -v
7.0.0

**Comment by giscafer** [comment]
升级7.0.1安装成功

```
cordova plugin add jpush-phonegap-plugin --variable APP_KEY=e874f264e3bd4572cbcc
Adding jpush-phonegap-plugin to package.json
Saved plugin info for "jpush-phonegap-plugin" to config.xml
```

**Comment by zim-lee** [comment]
cordova7.0.1 加了--nofetch后安装不报错，不过再安装其他的插件就报错了，错误和luyingjia的一样：
`
19 error path ******\node_modules\cordova-plugin-jcore\package.json
20 error code ELOOP
21 error errno -4067
22 error syscall open
23 error ELOOP: too many symbolic links encountered, open '*****\node_modules\cordova-plugin-jcore\package.json'
`

**Comment by zim-lee** [comment]
移除极光推送的插件，再安装其他的就不报错了。。。。
感觉是和cordova-plugin-jcore有关，
而且因为它是push的依赖，自动安装的，package.json记录的是本地文件路径，导致在别的机器也无法直接执行npm install，路径根本找不到

**Comment by giscafer** [comment]
@zim-lee 一直包错，清npm 缓存也不想，如何解决jcore错误
`Could not install from "node_modules\cordova-plugin-jcore" as it does not contain a package.json file.`

node_modules删除了并且清除了npm 缓存，重新install 还报错

**Comment by lhw5123** [comment]
@zim-lee 试下最新的版本，我这里 7.0.1 ok 了。

**Comment by zim-lee** [comment]
@lhw5123 可以了，感谢
