### ISSUE TITLE
请问有支持ionic3么

### ISSUE THREAD

**Issue by mizne** [jpush/jpush-phonegap-plugin#237]
请问有支持ionic3 @ionic-native的插件么

**Comment by lhw5123** [comment]
目前没有支持 ionic-native。

**Comment by CacheTechLtd** [comment]
可以自己下载ionic-native，然后集成进去。

**Comment by kongdewen1994** [comment]
@mizne @CacheTechLtd 可以试下https://github.com/kongdewen1994/ionic2-jpush-cordova-plugin
