### ISSUE TITLE
为什么ios不能进onOpenNotification

### ISSUE THREAD

**Issue by HotaruSun** [jpush/jpush-phonegap-plugin#238]
推送能正常收到，但是按照文档，就是进不了onOpenNotification和onReceiveNotification，只在生产环境下操作。

**Comment by HotaruSun** [comment]
jpushplugin.js里面有'receiveNotificationInAndroidCallback'，但没有iOS的，确定文档没问题？

**Comment by lhw5123** [comment]
用插件的 example 测试过吗？

**Comment by HotaruSun** [comment]
测试过，不行
