### ISSUE TITLE
我跟随guide安装出现了 “ 错误: 程序包R不存在 ” 的问题，请高手帮我解答一下，谢谢

### ISSUE THREAD

**Issue by yaonie084** [jpush/jpush-phonegap-plugin#24]
[javac] Compiling 8 source files to /Users/ethanwang/mobile/my2/platforms/android/ant-build/classes
    [javac] /Users/ethanwang/mobile/my2/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:341: 错误: 程序包R不存在
    [javac] 				this.cordova.getActivity(), R.layout.test_notification_layout,
    [javac] 				                             ^
    [javac] /Users/ethanwang/mobile/my2/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:342: 错误: 程序包R不存在
    [javac] 				R.id.icon, R.id.title, R.id.text);
    [javac] 				 ^
    [javac] /Users/ethanwang/mobile/my2/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:342: 错误: 程序包R不存在
    [javac] 				R.id.icon, R.id.title, R.id.text);
    [javac] 				            ^
    [javac] /Users/ethanwang/mobile/my2/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:342: 错误: 程序包R不存在
    [javac] 				R.id.icon, R.id.title, R.id.text);
    [javac] 				                        ^
    [javac] /Users/ethanwang/mobile/my2/platforms/android/src/cn/jpush/phonegap/JPushPlugin.java:344: 错误: 程序包R不存在
    [javac] 		builder.layoutIconDrawable = R.drawable.jpush_notification_icon;
    [javac] 		                              ^
    [javac] 注: 某些输入文件使用或覆盖了已过时的 API。
    [javac] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    [javac] 5 个错误

BUILD FAILED
/Users/ethanwang/Library/Android/sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/ethanwang/Library/Android/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 3 seconds

/Users/ethanwang/mobile/my2/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/Users/ethanwang/mobile/my2/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR building one of the platforms: Error: /Users/ethanwang/mobile/my2/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project

**Comment by sunnylqm** [comment]
仔细看文档
在cn.jpush.phonegap的JPushPlugin.java文件开始处,import your.package.name.R;

**Comment by yaonie084** [comment]
我加了也是这样子。。我看到 JPushPlugin.java 有一行注释掉的代码，然后我取消注释了，并且改成了自己package的名字。
import com.ionicframework.my2272636.name.R;

不知道我加的对不对， 另外我是用的ionic 不知道是否有影响

**Comment by sunnylqm** [comment]
包名看着就奇怪…你就在config.xml里面找你的app的id，比如是<widget... id=com.abc.app> 然后import com.abc.app.R就行了

**Comment by yaonie084** [comment]
@sunnylqm thanks~

**Comment by zhangqinghe** [comment]
@yaonie084 已修改文档，按照最新文档就可避免这个包名的问题

**Comment by Tony-Lee** [comment]
这个.R太隐晦了!

**Comment by MyateJx** [comment]
Atl+Enter，我是这样解决的

**Comment by 0312birdzhang** [comment]
感谢，已解决。

**Comment by zyf0330** [comment]
@zhangqinghe 
关于这个问题，我希望修改一下，这样太不好了。因为阻挠了正常的build。
按照现在的代码，调用R，需要改为自己的包名，而现在的实现方式，是通过hook修改文件内容。
我有两个解决办法
* [如何在插件中代码中调用和具体项目有关的R](http://stackoverflow.com/questions/26116955/cordova-plugin-android-activity-accessing-resources)
* 修改hook的使用方式。build操作包括prepare，那么只要把文件修改放到after_prepare，或者before_prepare钩子上，就好了吧。

不知道有没有其他涉及的问题。

**Comment by lhw5123** [comment]
@zyf0330 不太清楚你说的阻挠了正常的 build，具体是怎么样的？

**Comment by zyf0330** [comment]
@lhw5123 正如JPush文档所说，不要使用build，改为使用compile。
而build包括prepare+compile，prepare会恢复修改的src文件（这是按照Cordova文档所说，实际上并不会恢复修改的java文件）。

**Comment by lhw5123** [comment]
java 文件确实是不会恢复的，因为 prepare 命令是按照 plugin.xml 中的配置将文件拷贝到指定目录、写入一些配置到 AndriodManifest.xml 文件。如果修改了默认写入到 AndroidManifext.xml 的某些代码，这个时候用 build，就会导致 cordova 再把修改前的这段代码写进来，就会有错，所以这句话主要是这个意思，回头我修改下说法。

**Comment by zyf0330** [comment]
@lhw5123 我无语……我搞错了，我还以为这个问题是导致那个无法build成功的原因，我刚才找到真正原因了。我另开一个issue吧。
