### ISSUE TITLE
关于极光后台发送通知和自定义消息有点疑问

### ISSUE THREAD

**Issue by giantss** [jpush/jpush-phonegap-plugin#241]
1，后台发送通知只能是纯文本吗？我试着按文档中的格式发json格式但是显示出来的通知也是json数据的格式。。。
2，自定义消息，现在还是app只能在前台是才能接受到么？接收到自定义消息如果要显示通知是要我们手动添加代码啊？
麻烦解答一下 ，谢谢
@lhw5123

**Comment by lhw5123** [comment]
1. 通知内容是纯文本，可以通过 extra 来添加键值对。
2. 自定义消息是不会显示通知的。通知和自定义消息的区别可以看这个链接：https://docs.jiguang.cn/jpush/client/Android/android_senior/#vs

**Comment by giantss** [comment]
![wechatimg1130](https://user-images.githubusercontent.com/13778798/27412694-ebb0b9e6-5728-11e7-8f4a-52a8640040bd.jpeg)
我后问题1后半句，这种问题是怎么回事呢  
@lhw5123

**Comment by lhw5123** [comment]
文档中的是服务器 API，如果用自己的服务器发送通知，就是按照文档中的发 POST 请求，数据体为 JSON 格式。
极光官网后台也是封装的 API，不需要发 JSON，文本是什么内容，通知就展示什么。

**Comment by giantss** [comment]
谢谢 如果我要在极光官网后台测试 点击app通知后进入指定页面  我需要传一个tid参数应该如何在后台文本中体现呢

**Comment by giantss** [comment]
我明白了，
作为新人看完你们的开发文档提点意见：
     我觉得我们开发人员，需要有一个在极光官方后台测试的详细文档啊  很多地方写的不够详细 比如说我要官方后台测传参，不知道怎么传，文档中应该指出在什么位置传吧，最好图文。或者第一次进入你们发通知后台时给出图文引导，不然谁知道这些东西是在最下面的“可配置选项”设置这些参数呢。
