### ISSUE TITLE
ios add platform时报错 找不到Entitlements-Debug.plist文件

### ISSUE THREAD

**Issue by xiaoxiaofan123** [jpush/jpush-phonegap-plugin#242]
Installing "jpush-phonegap-plugin" for ios

Dependent plugin "cordova-plugin-device" already installed on ios.

Dependent plugin "cordova-plugin-jcore" already installed on ios.

Do not detected 'build.json' to get ios developent team. 
Will not enable XCode Push Notification Capability. 
Will only enable Push Notification for CI by add config to './platforms/ios/xxx/Entitlements-Debug.plist' and './platforms/ios/Entitlements-Release.plist' 
Please add 'build.json' to cordova project root folder to make after hook fullly functional. 
Reference [1]https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-build-command 
Reference [2]https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#signing-an-app

Installing "maycur-plugin-external-browser" for ios

Error: ENOENT: no such file or directory, open './platforms/ios/xxx/Entitlements-Debug.plist'

**Comment by snipking** [comment]
你的 cordova 版本和 ios platform 版本是什么？

请在项目目录下执行如下两个命令，把结果贴上来。

```
cordova -v

cordova platform ls
```

**Comment by xiaoxiaofan123** [comment]
cordova 6.4.0
 android 6.0.0
 ios 4.1.0

**Comment by snipking** [comment]
@xiaoxiaofan123 

是否可以升级 cordova 7.0.1
ios 4.4.0 呢？

另外本地的 Xcode 是哪个版本的？

我需要一点时间试一下 cordova 6.4.0 & iOS 4.1.0 的兼容性

**Comment by snipking** [comment]
@xiaoxiaofan123 

我试了一下在保持 cordova 6.4.0 版本不变的情况下，只需要将 ios 从 4.1.0 升级到 4.3.0 即可解决问题。

**Comment by xiaoxiaofan123** [comment]
@snipking 
好的谢谢 我试一下4.3.0
