### ISSUE TITLE
IOS安装插件后 add platform报错

### ISSUE THREAD

**Issue by Dawn2Yuan** [jpush/jpush-phonegap-plugin#245]
<img width="588" alt="qq 20170627173438" src="https://user-images.githubusercontent.com/9798058/27580990-f0e8bcc6-5b5e-11e7-978d-d30ae0653e1a.png">
Failed to install 'jpush-phonegap-plugin':SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:179:20)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20

Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by snipking** [comment]
升级你的 nodejs 版本

**Comment by Dawn2Yuan** [comment]
nodejs升级到那个版本呢 ？

**Comment by snipking** [comment]
@Dawn2Yuan 

你现在使用的是哪一个版本？为什么不升级到最新版本呢？

**Comment by Dawn2Yuan** [comment]
v5.3.0   现在的版本  我试试升级到最新版试一下

**Comment by Dawn2Yuan** [comment]
@snipking 
<img width="535" alt="jpush_2" src="https://user-images.githubusercontent.com/9798058/27625510-76bb87b2-5c17-11e7-9840-781b5ca4ebad.png">
这个又是什么原因？？

**Comment by snipking** [comment]
你的工程目录下面有 build.json 的 cordova 编译配置文件吗？如果有的话内容是什么？

日志报错上面的部分是什么？

**Comment by Dawn2Yuan** [comment]
@snipking 
build.json
{
	"android": {
	"release": {
		"keystore": "HengHeKeystore",
		"alias": "john",
		"storePassword": "123456",
		"password": "123456"
		}
	}
}
1:没有配置ios的配置   这样会报错吗？
2:顺便给一个build.json的官方配置说明地址呗

**Comment by snipking** [comment]
是的，因为没有配置 ios 的部分。

配置说明见如下两个文档

https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-build-command
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#signing-an-app

需要从 build.json 里面读取 `ios.release.developmentTeam` 以自动打开 ios 项目的 push notification，否则需要你手工用 xcode 打开项目启用 push notification。

这里我修改一下加一个检测吧。

**Comment by Dawn2Yuan** [comment]
@snipking 谢谢 细心指导

**Comment by Dawn2Yuan** [comment]
1：IOS添加插件的时候报一个错误 



2：remove插件的时候 也 报一个错误

**Comment by snipking** [comment]
1. 请手工移除 Plugins 目录下的 cordova-plugin-jcore 插件，以及 fetch.json 中的对应配置，node_modules 中的对应模块，package.json 中的对应配置。再尝试重新安装，并提供安装时的日志。

2. 请将 `platforms/ios/<proj_name>.xcodeproj/project.pbxproj` 中 `/* Begin PBXProject section */` 至 `/* End PBXProject section */` 的部分贴来看一下，并提供插件安装时的日志以及 Xcode 版本，描述插件安装完成后通过 xcode 对项目做过哪些修改。

3. 移除插件的问题开一个新的 issue
