### ISSUE TITLE
调用 window.plugins.jPushPlugin.resetBadge() ios图标右上角标无法清除

### ISSUE THREAD

**Issue by giantss** [jpush/jpush-phonegap-plugin#246]
我在点击通知回调函数中调用了 用了 window.plugins.jPushPlugin.resetBadge() ios图标右上角标无法清除，请问怎么回事呢

**Comment by giantss** [comment]
@lhw5123

**Comment by lhw5123** [comment]
设置应用本地的角标数，要用 `setApplicationIconBadgeNumber` 方法。

**Comment by giantss** [comment]
好的   看岔了。。。
