### ISSUE TITLE
IOS js中用户打开消息有没有相应的方法

### ISSUE THREAD

**Issue by xlz926** [jpush/jpush-phonegap-plugin#25]
在Android中打开消息有openNotificationInAndroidCallback 可以调用，在IOS中有没有类似的方法可以用呢？

**Comment by zhangqinghe** [comment]
iOS 点击的时候，phonegap插件本身还没有被构造出来，object-c to js的任何代码都无法传递，所以我建议在写object-c处理点击事件，而不是用js来实现

**Comment by xlz926** [comment]
@zhangqinghe 好的，谢谢
