### ISSUE TITLE
Cannot read property 'jPushPlugin' of undefined

### ISSUE THREAD

**Issue by www-okrs-cn** [jpush/jpush-phonegap-plugin#250]
window.plugins.jPushPlugin.init();这一行初始化的时候报错。。。。

**Comment by huangminlinux** [comment]
anddroid  还是 iOS

**Comment by www-okrs-cn** [comment]
android

**Comment by lhw5123** [comment]
是 ionic 项目还是一般的 Cordova 项目？插件版本是多少？用插件的 example 测试过了吗？这边测试没有出现这个问题。

**Comment by www-okrs-cn** [comment]
ionic  项目 插件版本是最新的 
我依据这个做的：http://www.cnblogs.com/tonge/p/5696058.html
我试试example 中的代码啊

**Comment by www-okrs-cn** [comment]
我按照example中的事例。在//启动极光推送服务  
window.plugins.jPushPlugin.init();
结果报：TypeError: Cannot read property 'init' of undefined"

**Comment by anonzi** [comment]
@www-okrs-cn 请问，这个问题解决了吗

**Comment by SevenWang666** [comment]
@www-okrs-cn 请问解决了吗？

**Comment by huangminlinux** [comment]
在 deviceReady 中调用 jpushplugin 相关方法。

**Comment by JoshLipan** [comment]
注意看下是不是cordova-android版本问题 @SevenWang666
