### ISSUE TITLE
backgroundNotification 无法在未激活应用的时候执行代码

### ISSUE THREAD

**Issue by youli2013** [jpush/jpush-phonegap-plugin#253]
已执行操作：
1：安装了最新版本的插件版本
2：勾选了Background Modes -->>  Remote notifications
3：推送通知的时候勾选了 content-available 
操作结果：
1：手机处于待机情况下，可以接收到通知，不会执行监听的代码，打开应用后才会执行监听的代码。
2：监听的代码中没有alert，打开应用后不会执行监听的代码。

```
document.addEventListener("jpush.backgroundNotification", onBackgroundNotification, false)
var onBackgroundNotification = function(event) {
    var alertContent;
    if (device.platform == "Android") {
        alertContent = event.alert;
    } else {
        alertContent = event.aps.alert;
    }
    alert(alertContent);
    xunfeiListenSpeaking.startSpeak(null,null,alertContent);// 调用cordova插件读取信息
}
```

**Comment by huangminlinux** [comment]
应用设置页面，后台应用刷新点开没

**Comment by youli2013** [comment]
手机的后台应用刷新是打开的状态

**Comment by youli2013** [comment]
1：是不是 App 处于后台状态时，收到推送消息，需要进入 App ，才会触发jpush.backgroundNotification方法 ？
2：如果是的话，有没有办法在 App 处于后台状态，收到推送消息及时触发 一系列 代码呢？

@huangminlinux

**Comment by youli2013** [comment]
@jasonz1987 
更新了最新的版本就解决了。

**Comment by chy89310** [comment]
@youli2013 想问下，如果app删了后台，还能触发jpush.backgroundNotification的监听么
