### ISSUE TITLE
setTagsWithAlias callback return nil

### ISSUE THREAD

**Issue by Xiangfs** [jpush/jpush-phonegap-plugin#254]
`window.plugins.jPushPlugin.setTagsWithAlias(res.data.tags, res.data.alias, function (res) {
console.log("success:" + res);
}, function (errorMsg) {
console.log("error:" + errorMsg);
}`

> **after doing function setTagsWithAlias, in successCallback, i got nil as res, and in Xcode, it print as follow:**

![124ecd31-648c-4d4e-a965-a8ef0abd59f3](https://user-images.githubusercontent.com/20461849/28152546-ad5ef11a-67d3-11e7-9725-e8b87431ac23.png)

> **I really don't know if the tags and alias are success registed or not, in js code, it should happens to return a object with four params, but i got nil, but in ios code, the iResCode is 0 which means success:**

<img width="687" alt="qq20170713-140319 2x" src="https://user-images.githubusercontent.com/20461849/28152647-28e6a184-67d4-11e7-8ab2-fd0594da303a.png">

when i send a notification with web api, it shows target/success as 1/1, but i got no notification with my phone, want to know what's the problem?
有中国同志请用中文回我-.-

**Comment by huangminlinux** [comment]
更新到最新版本

**Comment by Xiangfs** [comment]
`cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY=your_app_key`
用这个命令装上的就是最新版本了吧？
设置标签和别名之后应该会有成功或失败的反馈吧，XCODE里还是只有一个Action，没有成功或失败的提示（之前好像是会有两个Action的，一个是发起设置标签和别名的LOG，一个是设置成功的LOG），在JS的成功回调里拿到的res直接是null，不是应该拿到{resultCode, status, tags, alias}的么？（看到在OC里面对回调做处理的时候成功了之后直接把resultMessage的内容置为nil了0-0）
<img width="874" alt="qq20170713-162520 2x" src="https://user-images.githubusercontent.com/20461849/28157216-58d3e686-67e8-11e7-850e-2fa51cac73e6.png">
我现在还遇到一个奇怪的问题，直接用XCODE在设备上RUN的话，第一次登录上去，服务器也连接上了，但是在web端发推送，显示目标1/成功1，但是设备上收不到提示。在XCODE上停止再重新RUN一遍之后起来，没有设置标签和别名，但是这之后发送的推送都能收到了，不知道是为什么。

**Comment by huangminlinux** [comment]
回调函数里面 接口没有返回值， 因为这些返回值和传入参数是一样的，

所以只提供了回调事件

**Comment by Xiangfs** [comment]
哦~~是这样哒~~谢谢了，现在推送已经通了，就是用XCODE直接在设备上跑第一次会接收不到通知，我把应用打包出来之后下载看看~~如果没问题的话就OK了

**Comment by Dawn2Yuan** [comment]
window.plugins.jPushPlugin.setAlias(UserData.FUserID,
				function(){alert('sucsetAlias')},
				function(error){alert('error|setAlias:'+angular.toJson(error))}
				);


2017-07-17 18:47:47.180118+0800 聚材商城[10509:3337929] JPushPlugin=>PushResult=>>obj=>>> {"data":"101d855909700898e5a","method":"onGetRegistrationID.response"}
2017-07-17 18:47:47.194469+0800 聚材商城[10509:3337929] getApplicationIconBadgeNumber 0
2017-07-17 18:47:47.474460+0800 聚材商城[10509:3337966]  | JIGUANG | I - [JIGUANGBadgeNumberReport] set badge:0 succeed
2017-07-17 18:47:54.443316+0800 聚材商城[10509:3337929] api/SysUser/GetUserPushConfigInfo=>successJson=>> [object Object]
2017-07-17 18:47:54.445238+0800 聚材商城[10509:3337966]  | JIGUANG | D - [JIGUANGService] Action - setTags: (null) alias: 727 fetchCompletionHandle:
2017-07-17 18:47:54.446632+0800 聚材商城[10509:3337967]  | JIGUANG | D - [JIGUANGService] Action - setTags: {(
    727
)} alias: 727 fetchCompletionHandle:
2017-07-17 18:47:54.447546+0800 聚材商城[10509:3337966]  | JIGUANG | D - [JIGUANGService] Action - setTags: {(
    727
)} alias: 727 fetchCompletionHandle:


android上正常
ios下出现一下问题
走到 失败的回调函数里面    而且失败的回调函数为nil  why?

**Comment by huangminlinux** [comment]
@Dawn2Yuan  版本是多少，先试试更新到最新版本。

**Comment by Xiangfs** [comment]
@huangminlinux 现在推送功能正常了，但是第一次连接服务器并成功设置标签及别名之后收不到通知，只有杀掉APP进程再打开APP之后才能正常收到推送，不知道是什么原因？

**Comment by Dawn2Yuan** [comment]
@Xiangfs  奇怪 你都可以设置  标签与别名   我设置后   就走到 失败的回调函数里面的  
而且错误代码 为 nil根本查不出是什么原因

**Comment by Xiangfs** [comment]
@Dawn2Yuan 之前问过他们开发人员，说是现在用户不用管内部实现，只要根据返回的iResCode判断成功或失败就行了。
话说看到你是设置别名，为什么控制台里还有setTags？是不是API用错了？

**Comment by Dawn2Yuan** [comment]
@Xiangfs 
iResCode  这个是在插件源码里面
js端  拿不到这个值啊

**Comment by Xiangfs** [comment]
JS端就传一个成功回调一个失败回调，成功就会调成功回调，就没有参数传回来了~
我是在成功回调里LOG出success，失败回调里LOG出failed来判断是否成功的

**Comment by huangminlinux** [comment]
@Dawn2Yuan  只需要关注成功回调和失败回调就行。两种情况走的不同回调。

**Comment by Xiangfs** [comment]
@huangminlinux 我那个问题是什么原因呢？你们有遇到过么？

**Comment by huangminlinux** [comment]
@Xiangfs  不确定是不是 原生SDK 的问题，我初步测了一下没出现这问题， 明天再看看

**Comment by Xiangfs** [comment]
@huangminlinux IOS的问题依然存在~~望查一下原因~~安卓那边，如果杀掉进程的话是收不到推送的~~如果想杀掉之后还收的到的话要怎么配置呢？
