### ISSUE TITLE
新版3.2.2   ios提示角标数量一直增加   android和ios获取不到打开推送事件

### ISSUE THREAD

**Issue by DreamPWJ** [jpush/jpush-phonegap-plugin#256]
//启动极光推送服务
        try {
          window.plugins.jPushPlugin.init();
          if (device.platform != "Android") {
            window.plugins.jPushPlugin.setDebugModeFromIos();
            window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
          } else {
            window.plugins.jPushPlugin.setDebugMode(true);
            window.plugins.jPushPlugin.setStatisticsOpen(true);
          }
        } catch (e) {
          console.log(e);
        }
        window.setTimeout(function () {
          function resume() {
            if (window.plugins.jPushPlugin.isPlatformIOS()) {
              window.plugins.jPushPlugin.setBadge(0);
              window.plugins.jPushPlugin.resetBadge();
              window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
            } else if (device.platform == "Android") {
              window.plugins.jPushPlugin.setLatestNotificationNum(3);
              window.plugins.jPushPlugin.clearAllNotification();
            }
          }

          // System events
          document.addEventListener("resume", resume, false);

          //点击极光推送跳转到相应页面/点击通知栏的回调
          document.addEventListener("jpush.openNotification", function (data) {
            var BLNo = data.extras.BLNo; //订单号
            $state.go("myorderdetails", {no: BLNo});//订单详情
          }, false)

        }, 3000);

**Comment by huangminlinux** [comment]
服务端发送的字段，  badge 的值是什么？

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#%E8%8E%B7%E5%8F%96%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9

**Comment by huangminlinux** [comment]
测试没有问题， 确定集成成功了？

**Comment by DreamPWJ** [comment]
jpush.openNotification事件都不执行 不知道为什么

**Comment by DreamPWJ** [comment]
集成成功了 推送都没问题的

**Comment by huangminlinux** [comment]
有日志吗？

**Comment by DreamPWJ** [comment]
//点击极光推送跳转到相应页面/点击通知栏的回调
      document.addEventListener("jpush.openNotification", function (data) {
        var BLNo = data.extras.BLNo; //订单号
        $state.go("myorderdetails", {no: BLNo});//订单详情
      }, false)    这个事件没执行  现在不好看日志信息

**Comment by DreamPWJ** [comment]
window.plugins.jPushPlugin.setDebugMode(true)  打开后都不打印日志 说明没错误吧

**Comment by zuowensheng** [comment]
遇到同样的问题  jpush.openNotification  android正常  ios 不执行

**Comment by huangminlinux** [comment]
@zhangmeteor 什么系统

**Comment by zuowensheng** [comment]
什么系统是指？ 就是苹果真机测试

**Comment by zuowensheng** [comment]
Android正常回调 ios没回调

**Comment by huangminlinux** [comment]
这边测试没出现这种情况， 能否提供有问题的 demo 到 github 上，我这边拉下来看看

**Comment by zuowensheng** [comment]
可以了. 之前是js顺序问题导致的
