### ISSUE TITLE
应用在前台时如何取消部分推送的通知栏/横幅提醒

### ISSUE THREAD

**Issue by hewz** [jpush/jpush-phonegap-plugin#257]
项目中集成了聊天功能，需要应用在前台时收到消息不触发通知栏/横幅提醒，而在其他业务中保留。请问如何操作？

**Comment by huangminlinux** [comment]
android 还是 iOS？

**Comment by hewz** [comment]
两个平台都需要

**Comment by huangminlinux** [comment]
使用推送不好满足这个需求，需要修改原生代码。
所以建议，应用在前台使用 极光的自定义消息 来代替推送消息。 这可以满足你的需求

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#%E8%8E%B7%E5%8F%96%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9

**Comment by hewz** [comment]
这样的话服务器要记录客户端状态了吧？对前台应用发消息，对后台应用发推送，好像更麻烦呀..

改原生代码的话，iOS是在这个userInfo中拿到推送数据吧，Android又是在哪里调用的呢？
<img width="755" alt="qq20170721-140659 2x" src="https://user-images.githubusercontent.com/3361000/28451624-e4d2c1a0-6e20-11e7-9e84-772fa6cec534.png">

**Comment by huangminlinux** [comment]
我用刚刚推荐的 自定义消息

**Comment by hewz** [comment]
您的意思是，服务器发自定义消息，客户端在JS jpush.receiveMessage回调函数里判断应用是否在前台，然后决定是否调用本地通知？但是当app只有PushService在后台运行时，js不会被调用。

**Comment by huangminlinux** [comment]
我先把这个 issue 关闭，如果还有问题可以重新打开
