### ISSUE TITLE
标签无法清除更改

### ISSUE THREAD

**Issue by xiaofuyesnew** [jpush/jpush-phonegap-plugin#259]
使用cordova 7.0.1打包应用程序，根据本地存贮的uid作为标签来识别用户，同一台设备登录之后获取uid能正常使用推送通知功能，然而在使用另外一些账户登录时，uid设置tags失效，尝试过用空数组清除之前的设置，和使用新的uid覆盖设置的方法都不奏效。即用第一个登录的账户uid可以推送，而不管后面登录多少个账户，这些账户对应的uid作为标签都无法推送。

**Comment by lhw5123** [comment]
插件版本是多少？出现在 Android 还是 iOS 上？

**Comment by xiaofuyesnew** [comment]
@lhw5123 挺尴尬的，这个可以关闭了，找到问题了，有小伙伴改了我的代码，把cordova.js的引用误删了，我这里也关闭了调试模式，没有返回提示。梳理了一遍之后，运行正常的。
