### ISSUE TITLE
IOS平台下面集成后的结果是可以收到系统栏通知,但进入应用后获取不到推送内容,求解

### ISSUE THREAD

**Issue by simplechen** [jpush/jpush-phonegap-plugin#26]
HI:
    最近在集成jpush在phonegap下面的项目时遇到，如题困扰。如何解决呢，
    另外在www/index.html中如何调用消息内容？
   JPushPlugin.prototype.receiveMessageIniOSCallback  方法在何处调用？

   我的做法：
    var notice_data = {};
    document.addEventListener('resume', function(){
                console.log('--start resume--');
     window.plugins.jPushPlugin.getNotification(JPushPlugin.prototype.openNotificationInAndroidCallback,notice_data);
                console.log(notice_data);
                console.log("--end resume--");
            },false);

但这种写法无效

**Comment by simplechen** [comment]
根据我的理角正确的使用应该是在www/index.html中
1. 引入jspushplugin
    <script type="text/javascript" src="JPushPlugin.js"></script>
2. 注册设备准备好的事件(如获取deviceToken,注册收到消息后处理的数据)
document.addEventListener("deviceready", function(){
    window.plugins.jPushPlugin.init();
    window.plugins.jPushPlugin.setDebugMode(true);
    window.plugins.jPushPlugin.getRegistrationID(onGetRegistradionID);
    
   if(window.plugins.jPushPlugin.isPlatformIOS()){
                window.plugins.JPushPlugin.receiveMessageIniOSCallback(notice_data);
    }
}, false);  

3. 重新进入界面中直接调用收到的消息
  document.addEventListener('resume', function(){
        console.log(notice_data);  //判断接收到的消息
        //清空消息等其它的处理
},false);


不知道我这样的理解是否正常，我也正是按这个方式做的，但应用层收不到消息，为何，请指点！多谢！

**Comment by zhangqinghe** [comment]
@simplechen  请问，你发送的是notificaiton还是message？

**Comment by Samurais** [comment]
在iOS中，我用这种方式抓push过来的消息的。
* 修改  JPushPlugin.m
```
- (void)networkDidReceiveMessage:(NSNotification *)notification {

    NSDictionary *userInfo = [notification userInfo];
    NSLog(@"%@",userInfo);

    NSError  *error;
    NSData   *jsonData   = [NSJSONSerialization dataWithJSONObject:userInfo options:0 error:&error];
    NSString *jsonString = [[NSString alloc]initWithData:jsonData encoding:NSUTF8StringEncoding];

    NSLog(@"JPUSH networkDidReceiveMessage");
    NSLog(@"%@",jsonString);

    dispatch_async(dispatch_get_main_queue(), ^{

        [self writeJavascript:[NSString stringWithFormat:@"window.jPushPluginreceiveMessageIniOSCallback('%@')",jsonString]];

    });
}
```

>  就是将原来的```window.plugins.jPushPlugin.receiveMessageIniOSCallback``` 改成 ```window.jPushPluginreceiveMessageIniOSCallback``` 

* 定义window.jPushPluginreceiveMessageIniOSCallback
项目使用 angularjs, 我将用service 包装了JPushPlugin 的接口，而且，在接到时间后，通报给其他订阅者。
```
// jpush service wrapper and proxy
.service('jpushp', function($rootScope, $log) {

    window.jPushPluginreceiveMessageIniOSCallback = function(data) {
        try {
            $log.debug("JPushPlugin:receiveMessageIniOSCallback--data:" + data);
            var bToObj = JSON.parse(data);
            // var content = bToObj.content;
            // console.log(content);
            $rootScope.$broadcast('jpushp', bToObj);
        } catch (exception) {
            $log.error("JPushPlugin:receiveMessageIniOSCallback" + exception);
        }
    }
    this.setDebugModeFromIos = function() {
        window.plugins.jPushPlugin.setDebugModeFromIos();
    }

    this.setAlias = function(alais) {
        window.plugins.jPushPlugin.setAlias(alais.toLowerCase());
    }
})
```

**Comment by zhangqinghe** [comment]
@Samurais 赞

**Comment by simplechen** [comment]
GOOD个人已经搞定
