### ISSUE TITLE
ionic build ios && ionic run ios 没法getRegistrationID， 用XCode run 或者 Debug 就正常

### ISSUE THREAD

**Issue by cjy37** [jpush/jpush-phonegap-plugin#261]
#### 编译环境：
node v7.7.1
cordova v6.5.0
ionic v2.2.3
cordova-ios v4.3.1
jpush-phonegap-plugin v3.2.3  

#### PS. Capabilities 中已打开 Push Notifications 开关

**Comment by huangminlinux** [comment]
应该是 ionic 编译选项问题， 具体也不太清楚什么原因。

**Comment by cjy37** [comment]
问题已经找到，需要在plugin.xml增加以下内容到ios节点 “<platform name="ios">” 下面

`		<config-file target="*-Info.plist" parent="UIBackgroundModes">
		  <array>
			<string>remote-notification</string>
		  </array>
		</config-file>
		<config-file target="*-Debug.plist" parent="aps-environment">
		  <string>development</string>
		</config-file>
		<config-file target="*-Release.plist" parent="aps-environment">
		  <string>production</string>
		</config-file>
`

**Comment by Lyfei** [comment]
> 问题已经找到，需要在plugin.xml增加以下内容到ios节点 下面
> 
> > ```
> >         《platform name="ios"》
> > ```
> 
> > ```
> >   <config-file target="*-Info.plist" parent="UIBackgroundModes">
> >     <array>
> >   	<string>remote-notification</string>
> >     </array>
> >   </config-file>
> >   <config-file target="*-Debug.plist" parent="aps-environment">
> >     <string>development</string>
> >   </config-file>
> >   <config-file target="*-Release.plist" parent="aps-environment">
> >     <string>production</string>
> >   </config-file>
> > ```

在Xcode里打开推送和UIBackgroundModes里的设置，问题依旧存在
