### ISSUE TITLE
附加字段取不到

### ISSUE THREAD

**Issue by 395779222** [jpush/jpush-phonegap-plugin#262]
<img width="641" alt="1112" src="https://user-images.githubusercontent.com/8910144/29604257-82004800-8819-11e7-8973-6666ee4781e4.png">
`document.addEventListener("jpush.openNotification", event => {
      //  window['plugins'].jPushPlugin.resetBadge();
      let content = this.nativeService.isIos() ? event['aps'].alert : event['alert'];
      let type = this.nativeService.isIos() ? event['type'] : event['extras'].type;
      console.log("jpush.openNotification" + content);
    }, false)`

**Comment by huangminlinux** [comment]
可以查看一下 event 里面的字段，extras 并不是在 event 字段里面的。

**Comment by 395779222** [comment]
extras 这个字段在哪里，怎么获取。

**Comment by huangminlinux** [comment]
你可以检查一下 event 里面的字段， extra 的字段应该会在 event 里面

**Comment by 395779222** [comment]
没有兄弟，我看了。。。有的话直接取了

**Comment by 395779222** [comment]
可以查看一下 event 里面的字段，extras 并不是在 event 字段里面的。
你可以检查一下 event 里面的字段， extra 的字段应该会在 event 里面
你这俩句话，我都怀疑是不是我理解错了

**Comment by huangminlinux** [comment]
event["testKey"]

**Comment by 395779222** [comment]
`{"isTrusted":false,"_j_uid":10690844565,"_j_business":1,"_j_msgid":3605731518,"actionIdentifier":"com.apple.UNNotificationDefaultActionIdentifier","testKey":"22311111","aps":{"sound":"default","badge":1,"alert":{"subtitle":"房产审核","title":"待审核信息","body":"测试信息"}}}`
type这个参数一直找不到

**Comment by huangminlinux** [comment]
不要用 type 这个 key

**Comment by 395779222** [comment]
好吧，关了这个问题吧，建议在文档中标出来。
