### ISSUE TITLE
提示上传device token成功，但是无法接收到推送

### ISSUE THREAD

**Issue by MrLiHong** [jpush/jpush-phonegap-plugin#266]
环境: 
iOS 10.3.2
XCode:8.3.3
cn.jpush.phonegap.JPushPlugin 2.0.2 

XCode输出日志:
`JPushLog: 
---------------------Jpush(IOS8Version) log---------------------- 

 --------------------Jpush SDK Version:1.8.3--------------------- 

JPushLog: upload device token success 
`

已经后台做了正确的配置:
![image](https://user-images.githubusercontent.com/20055964/30053995-34ed594c-925d-11e7-81ce-2793aa31a2fa.png)

**Comment by huangminlinux** [comment]
检查 (Project -> Target -> Capabilities ) Push Notification 选项是否已经点开，如果没有需要点开
