### ISSUE TITLE
Android手机通知栏看不完全通知的文字

### ISSUE THREAD

**Issue by Jeijie** [jpush/jpush-phonegap-plugin#267]
Android手机通知栏看不完全通知的问题，能不能和IOS一样换行显示?
![screenshot_2017-09-15-16-29-04](https://user-images.githubusercontent.com/9338052/30473441-11ced05c-9a33-11e7-8718-ce389c1bab70.jpg)

**Comment by lhw5123** [comment]
可以尝试推送的时候选择 「大段文本样式（BigTextStyle）」：
<img width="575" alt="537a3fbc-4bb2-4940-b0ab-530ab48b0500" src="https://user-images.githubusercontent.com/6531354/30527954-c9f23faa-9c60-11e7-8579-b4a2bd8ad6a1.png">

如果是用服务器 Library 进行的推送，可以参考 [REST API 文档](https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#notification)。

不过要注意大段文本样式（BigTextStyle）支持 Android 4.1 以上系统，并且在国产某些 rom 上可能无效。

**Comment by Lbywer** [comment]
![image](https://user-images.githubusercontent.com/16092821/36525094-7ac29462-17e3-11e8-899c-6c9aa9b3599f.png)
已设置大段文本样式，但是控制台预览仍然是默认样式。
![image](https://user-images.githubusercontent.com/16092821/36525130-ab9d447e-17e3-11e8-80c5-9decaa26cab9.png)
点击立即发送发送至手机后样式同预览时一样为默认样式。文字无法完全显示。测试机型：红米note4

**Comment by lhw5123** [comment]
@Lbywer 有用模拟器或其他机型测试过吗？

**Comment by Lbywer** [comment]
@lhw5123 感谢您的回复。目前还没有用其他机型测试过。
