### ISSUE TITLE
nexus 6p android 8.0 获取不到registrationID

### ISSUE THREAD

**Issue by sdandroid** [jpush/jpush-phonegap-plugin#269]
其它版本的，可以获取到。

**Comment by lhw5123** [comment]
可以提供下日志吗？

**Comment by lhw5123** [comment]
更新到 v3.2.5 再试一下。

**Comment by sdandroid** [comment]
现在可以获取到了，但是有个问题，插件有用 https://github.com/HsuanXyz/ionic2-jpush，如果app 是新安装的，或者有清除数据，第一次获取 registrationID是问题的。

**Comment by Wiki1991** [comment]
我也遇到了上面的问题，第一次安装的应用无法获取registrationID，版本3.2.3

**Comment by a81584944** [comment]
我也是crash了。。截取了一部分了

java.lang.IllegalStateException: Not allowed to start service Intent { flg=0x20 cmp=com.starbucks.cn/cn.jpush.android.service.DaemonService }: app is in background uid null

**Comment by JoshLipan** [comment]
更新最新版本测试，这个issue先关闭了，有问题再提。
