### ISSUE TITLE
“我想要获取在推送信息里的内容”

### ISSUE THREAD

**Issue by christopher1215** [jpush/jpush-phonegap-plugin#27]
我用jpush-phongap-plugin来做了一个IOS软件。
现在从服务器发送来的推送信息准确的到我这个app，但无法获取在其内的推送内容。
现在我想要获得其内的推送内容。请告诉我调用什么接口能得到其推送内容。
太着急了，能快点就好。谢谢

**Comment by Samurais** [comment]
#26 may help.

**Comment by christopher1215** [comment]
麻烦你再教一下。
// jpush service wrapper and proxy
.service('jpushp', function($rootScope, $log) {

    window.jPushPluginreceiveMessageIniOSCallback = function(data) {
        try {
            $log.debug("JPushPlugin:receiveMessageIniOSCallback--data:" + data);
            var bToObj = JSON.parse(data);
            // var content = bToObj.content;
            // console.log(content);
            $rootScope.$broadcast('jpushp', bToObj);
        } catch (exception) {
            $log.error("JPushPlugin:receiveMessageIniOSCallback" + exception);
        }
    }
    this.setDebugModeFromIos = function() {
        window.plugins.jPushPlugin.setDebugModeFromIos();
    }

    this.setAlias = function(alais) {
        window.plugins.jPushPlugin.setAlias(alais.toLowerCase());
    }
})
我还不清楚上面那个代码写在哪儿？在项目那个部分
angularjs是什么，如何使用？还有service 这个是什么?

**Comment by christopher1215** [comment]
Samurais,
Please help me!!!

**Comment by christopher1215** [comment]
还有window.jPushPluginreceiveMessageIniOSCallback这个在哪儿调用，如何调用（怎么填那个参数等）。
最好给我提供例子，谢谢。
