### ISSUE TITLE
安装插件的时候提示plugin.xml中没有yargs

### ISSUE THREAD

**Issue by yongtaoChen** [jpush/jpush-phonegap-plugin#270]
开发环境是ionic3，cordova已升级成最新版本。
提示信息:
Error: Cannot find plugin.xml for plugin "yargs". Please try adding it again.
yargs是node的模块，怎么加到plugin中？

**Comment by yongtaoChen** [comment]
将cordova的版本降低至6.5.0就没问题了。

**Comment by lhw5123** [comment]
尝试在插件安装命令后加上 `--nofetch`。例如：
```shell
cordova plugin add jpush-phonegap-plugin --variable APP_KEY=your_jpush_appkey --nofetch
```

**Comment by yongtaoChen** [comment]
OK啦，加上--nofetch后cordova7.0.1也可以用了。三克油。
