### ISSUE TITLE
iphone上startJPushSDK报错

### ISSUE THREAD

**Issue by nurdun** [jpush/jpush-phonegap-plugin#271]
我用iphone测试本插件的时候startJPushSDK APi报错了。
错误信息是startJPushSDK is does not exist on type ‘JPush’。
typescript: src/pages/content/content.ts, line: 45 
            Property 'startJPushSDK' does not exist on type 'JPush'. 

      L45:   this.jPush.startJPushSDK()
      L46:   .then(()=>{

然后不知道是不是startJPushSDK这个方法用不了的原因，我用init()方法的时候控制台会提出warning plugin not install

**Comment by lhw5123** [comment]
用的是我们这个库？

**Comment by lhw5123** [comment]
这不是这个库的问题。
