### ISSUE TITLE
在Android 7.1.1上，默认应用通知权限没有打开

### ISSUE THREAD

**Issue by Jeijie** [jpush/jpush-phonegap-plugin#274]
在Android 7.1.1上，默认应用通知权限没有打开，需要手动打开。型号：360手机vizza，Android版本7.1.1；暂时未测过同版本的其他手机。
![screenshot_2017-10-10-09-33-51](https://user-images.githubusercontent.com/9338052/31365540-563adf14-ad9e-11e7-9150-799b4552d343.png)

**Comment by lhw5123** [comment]
应该是 360 手机 rom 的问题，原生 Android 7.1.1 模拟器没发现有这个问题。
