### ISSUE TITLE
注册成功事件ios上没有回调

### ISSUE THREAD

**Issue by giantss** [jpush/jpush-phonegap-plugin#280]
注册成功事件

`document.addEventListener('jpush.receiveRegistrationId', function (event) {
  console.log(event.registrationId)
}, false)`
在ios上没有回调，但是控制台可以看到
![4d51cb98681c588b486242de355da255](https://user-images.githubusercontent.com/13778798/31876261-79eaaea0-b797-11e7-8a3d-414f06fd9311.jpg)

android上可以正常回调。
求解

**Comment by huangminlinux** [comment]
有在 onDeviceReady 调用jpush.init 方法吗

**Comment by giantss** [comment]
@huangminlinux 调用了啊 
我调试源码发现 receiveRegistrationId事件没有触发，receiveMessage事件是可以触发
![f503fb62541c87771a508065ad26fe9b](https://user-images.githubusercontent.com/13778798/31877602-b95ad45c-b79c-11e7-9fc7-4c179f527277.jpg)

**Comment by huangminlinux** [comment]
你的 js 监听代码放到哪？

**Comment by giantss** [comment]
放的位置肯定是没错的，不然android也不会触发的 现在的问题是ios没有触发啊

**Comment by giantss** [comment]
@huangminlinux 
![image](https://user-images.githubusercontent.com/13778798/31879126-06fbf8da-b7a2-11e7-8bf8-e628c7d0584c.png)

**Comment by huangminlinux** [comment]
下个版本修复这个问题。

**Comment by giantss** [comment]
@huangminlinux 能不能先给个改插件源码的方案啊 产品明天上线 急啊 😭

**Comment by huangminlinux** [comment]
事件在 js 没有准备好的时候触发了，这边需要做一个缓存。
这边会尽快发版本。

最简单的做法延迟个几秒再触发也可以解决这个问题。

**Comment by giantss** [comment]
@huangminlinux 不对啊 我把事件注册延迟了5秒、 10秒 也没有触发，我觉得是不是应该在用户点击同意开启消息推送的时候回调呢

**Comment by huangminlinux** [comment]
要保证 jpush.init 方法尽早的调用。

刚发了修复版 3.2.10。

**Comment by giantss** [comment]
@huangminlinux 我用的是version="3.1.7" 版本，在这个版本我测试发现貌似不是你说的这样样（事件在 js 没有准备好的时候触发了），我换成在下个页面里面的点击事件添加receiveRegistrationId这个事件， 还是没有触发，  我暂时还看不到 3.2.10版本。

**Comment by huangminlinux** [comment]
```
npm view jpush-phonegap-plugin
```

**Comment by giantss** [comment]
亲测已修复，感谢🙏。
