### ISSUE TITLE
3.2.10 ios新bug

### ISSUE THREAD

**Issue by giantss** [jpush/jpush-phonegap-plugin#281]
jpush.receiveRegistrationId 事件在文档中描述只会调用一次，但是在ios中会调用很次。
目前发现： 
1，用户点击同意通知后会执行一次。（触发事件的时间太长了吧，一般用户点击同意后都要4-6秒左右）。
2，app没关闭的情况下，一段时间不使用I（进入后台），再次唤醒app的时候也会触发。
3，第三中情况时间不固定，使用app期间，时不时的就会触发这个事件(小概率)。

**Comment by huangminlinux** [comment]
可以更新到 3.2.11 版本
