### ISSUE TITLE
Cordova 使用极光推送，能给过详细教程吗？

### ISSUE THREAD

**Issue by KitchenLiang** [jpush/jpush-phonegap-plugin#282]
cordova plugin add jpush-phonegap-plugin --variable APP_KEY=your_jpush_appkey之后下一步怎么做

**Comment by lhw5123** [comment]
然后在你项目监听 deviceready 事件的回调里调用 init 方法初始化就行了，更多 API 可以看 README 里
的 API 文档。

iOS 还需要配置证书，可以看[JPush 官网文档](https://docs.jiguang.cn/jpush/client/iOS/ios_cer_guide/)或者 Apple 的官方文档。
