### ISSUE TITLE
升级后，设置alias一直报错6002

### ISSUE THREAD

**Issue by chaogao** [jpush/jpush-phonegap-plugin#285]
没有重复调用，一直报错 6002

// 给用户在 jpush 上打标签
              (<any>window).plugins.jPushPlugin.setAlias({ sequence: 2, alias: 'ark_' + this.user.id }, (result) => {
                console.log('registed:' + result.alias);
              }, (error) => {
                console.log(error);
              });

**Comment by huangminlinux** [comment]
请求超时了， 切换网络环境试试。
