### ISSUE TITLE
ios和android收到extra的方式不一样

### ISSUE THREAD

**Issue by superddr** [jpush/jpush-phonegap-plugin#288]
ios的extras内容直接就在event上
android的extras内容在event.extras字段上

能统一一下不?

**Comment by lhw5123** [comment]
下个版本会考虑统一。: )

**Comment by huangminlinux** [comment]
可以升级到 [3.2.13](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.2.13) 版本
