### ISSUE TITLE
IOS无法收到推送

### ISSUE THREAD

**Issue by haipengsong** [jpush/jpush-phonegap-plugin#291]
通过cordova安装插件并指定了APP KEY，但是IOS安装的时候，XCode控制台报错：
          [JIGUANGAlert] ERROR “”不是合法的APP_KEY。
  Android能够收到推送。

**Comment by huangminlinux** [comment]
检查 JPushConfig.plist 的 Appkey 是否正确。

**Comment by huangminlinux** [comment]
我先关闭这个 issue ，如果还有问题可以重新打开。

**Comment by saharaying** [comment]
同样，xcode报错

[JIGUANGAlert] ERROR “”不是合法的APP_KEY。（有关APP_KEY的说明请参考开发文档“SDK集成指南”。https://docs.jiguang.cn/jpush/client/iOS/ios_guide_new/
[JIGUANGService] 请检查"setupWithOption:appKey:channel:apsForProduction:"方法的参数值
