### ISSUE TITLE
ios 设置别名出错 报6002

### ISSUE THREAD

**Issue by koukaicheng** [jpush/jpush-phonegap-plugin#293]
window.JPush.setAlias({sequence: 1, alias: String(id)},
                  (result) => {
                    let sequence = result.sequence;
                    let alias = result.alias;
                    console.log(sequence + '---' + alias);
                  }, (error) => {
                    let sequence = error.sequence;
                    let errorCode = error.code;
                     alert(sequence + '---' + errorCode)
                  })
安卓是正常的

**Comment by huangminlinux** [comment]
6002 超时错误，切换 4G 环境，等待十分钟再试。

**Comment by koukaicheng** [comment]
明白了。还有一个问题想请教一下 ，那个ios的APP角标 总是显示1  卸载了再次安装还是 会出现1 这个是因为我没有做相关的处理吗

**Comment by huangminlinux** [comment]
可以调用 setBadge 这个接口来设置角标。

**Comment by koukaicheng** [comment]
这个 我还想问一下 在ios上面  收到消息的时候  进入软件内 是哪个事件呢  jpush.openNotification是这个吗

**Comment by huangminlinux** [comment]
你的意思是点击推送唤起应用？监听这个事件即可  `jpush.openNotification`。
