### ISSUE TITLE
setAudience 问题

### ISSUE THREAD

**Issue by nodejscss** [jpush/jpush-phonegap-plugin#296]
问题： 如何使用tag数组？

var tag = ['a@d.com', 'b@d.com', 'c@d.com'];
var alias = ['a@d.com', 'b@d.com', 'c@d.com'];
.setAudience(JPush.tag(tag), JPush.alias(alias.join(',')) // 不正常，全部无效

// ---------------------------------------------------------------------------

.setAudience(JPush.alias('a@d.com')) // 正常
.setAudience(JPush.tag('b@d.com')) // 也正常

.setAudience(JPush.alias('a@d.com'), JPush.tag('b@d.com')) // 不正常，只有前面的有效

// ---------------------------------------------------------------------------

.setAudience({tag:['b@d.com']}, {alias:['a@d.com']}) // 全部无效
.setAudience({tag:['b@d.com']}) // 正常
.setAudience({alias:['a@d.com']}) // 正常

**Comment by nodejscss** [comment]
https://docs.jiguang.cn/jpush/server/sdk/nodejs_sdk/

**Comment by nodejscss** [comment]
是 jpush的server, nodejs_sdk.

**Comment by lhw5123** [comment]
那这个 issue 应该提在 [nodejs sdk](https://github.com/jpush/jpush-api-nodejs-client) 库里。这里我先关了。
