### ISSUE TITLE
iOS收到推送消息后如何不更新角标

### ISSUE THREAD

**Issue by fallcool** [jpush/jpush-phonegap-plugin#297]
我在客户端维护了badge数量，但是每次iOS收到推送都将角标数设置为服务器端保存的数值，而android似乎又没有这一功能。有没有办法在收到推送后不改变iOS客户端的badge数值。我也尝试了

window.plugins.jPushPlugin.setBadge(value); 

来更新服务器端的badge数值， 但不成功。谁知道应该怎么办？

**Comment by coolara** [comment]
有两个方法 你用的这个方法只是和服务器端设置了
在手机上没设置
手机上要用另外一个方法设置0 就不用维护了

**Comment by huangminlinux** [comment]
@fallcool  你们服务推送的时候 Badge 参数的值是什么？iOS 的应用收到推送收设置 badge 值是根据这个来的。
如果你们服务端 Badge 为固定数值，那么会应用收到推送就是该数值。
如果你们服务端 Badge 为 '+1', 这种情况下才会使用到极光服务器的 Badge（最终推送的 Badge = 极光 Badge 加一），

API 的功能需要弄清楚 `window.plugins.jPushPlugin.setBadge` 不会直接改变应用本地的角标值（Badge）。
如果需要直接修改应用本地角标调用的是 `window.plugins.jPushPlugin. setApplicationIconBadgeNumber ` 接口

**Comment by YDJSZY** [comment]
能不能任何时候都不显示角标？
