### ISSUE TITLE
ios端APP启动太快无法访问window.JPush对象

### ISSUE THREAD

**Issue by elon-hu** [jpush/jpush-phonegap-plugin#298]
开发环境：
os: macOS High Sierra
node: v8.9.1
cordova: 7.1.0
ios-platform: 4.5.4
jpush-phonegap-plugin: 3.2.12

ios端APP启动太快无法访问window.JPush对象
启动时console.log(window.JPush)打印出undefined
我们设置延时1000ms执行window.JPush.init()才让app正常

**Comment by huangminlinux** [comment]
试试监听 deviceready 事件` document.addEventListener("deviceready", onDeviceReady, false);`
在该事件回调中处理业务逻辑。
