### ISSUE TITLE
iOS 启动崩溃

### ISSUE THREAD

**Issue by tomwey** [jpush/jpush-phonegap-plugin#299]
联机调试环境下，第一次安装使用没问题，删掉APP重新安装启动，APP崩溃。错误如下：

<img width="1153" alt="screen shot 2017-12-11 at 10 40 07" src="https://user-images.githubusercontent.com/522763/33862336-3349a9bc-df1d-11e7-9f0e-c0a4e8a9446d.png">

**Comment by huangminlinux** [comment]
使用 ionic 和 cordova 都没出现你说这种种情况。

**Comment by tomwey** [comment]
找到问题了，设置alias的时候传了一个字符串，而你代码里面是需要一个字典
