### ISSUE TITLE
Android JPushPlugin:transmitPush - instance == null 导致webview没有接到message

### ISSUE THREAD

**Issue by Samurais** [jpush/jpush-phonegap-plugin#30]
# Description

使用jpush nodejs SDK 发下面的消息
```
var JPush = require("jpush-sdk");
var client = JPush.buildClient('', '');

// https://github.com/jpush/jpush-api-nodejs-client
client.push().setPlatform('android')
    .setAudience(JPush.ALL)
    .setNotification('Hi, JPush', JPush.ios('ios alert', 'happy', 5))
    .setMessage('hi, JPush', 'title', 'content-type', {
        foo: 'bar'
    })
    .send(function(err, res) {
        if (err) {
            console.log(err.message);
        } else {
            console.log('Sendno: ' + res.sendno);
            console.log('Msg_id: ' + res.msg_id);
        }
    });
```

如果应用正在运行，不论是在background 还是 foreground. webview都正确的执行了js. 

可如果应用没有运行，收到消息后，打开应用，发现webview没有执行js. 读了代码，发现了问题。

**JPushPlugin.java**

```
	static void transmitPush(String message, Map<String, Object> extras) {
		if (instance == null) { // 在应用没有运行，来消息时，这里运行，直接返回了。
			return;
		}
		JSONObject data = notificationObject(message, extras);
		String js = String
				.format("window.plugins.jPushPlugin.receiveMessageInAndroidCallback('%s');",
						data.toString());
		try {
			instance.webView.sendJavascript(js); // 因为前面返回，这里就没有执行。
		} catch (NullPointerException e) {

		} catch (Exception e) {

		}
	}
```

# Solution
问题的原因是应用没有运行，webview实例不存在，这样js执行不了。
我想到一个方案，使用 数据库 sqlite 做 从 native 到 webview 的数据交互。

检测到 JPushPlugin.instance == null 以后，不立即返回，而是将这条message插入到一个 sqlite 的表中，
webview启动后读取表里的内容，取完了再删除。

sqlite api

* https://github.com/brodysoft/Cordova-SQLitePlugin

* http://developer.android.com/reference/android/database/sqlite/package-summary.html

有没有更好的办法？

**Comment by Samurais** [comment]
@zhangqinghe  Need your help. Thanks.

**Comment by zhangqinghe** [comment]
@Samurais  please send the sample to  me. My email is zhangqh@jpush.cn

**Comment by Samurais** [comment]
@zhangqinghe 好的，这里需要一个queue，js订阅消息，java发布消息，webview启动后，可以接到历史消息，这段时间过年，我也没有实现通过数据库存储数据这个方案。

**Comment by lifei** [comment]
@zhangqinghe 直接用内存就好了呀
