### ISSUE TITLE
无法探测到我的ionic在线用户

### ISSUE THREAD

**Issue by cqiuping** [jpush/jpush-phonegap-plugin#300]
ionic使用的时候是不是只要保证config.xml里面的name和工程名一致就可以了，id要不要一样，为什么探测不到我的app用户

**Comment by lhw5123** [comment]
id 代表的是包名，要和在极光官网控制台里注册的一样才行。

**Comment by cqiuping** [comment]
那name可以不一样吗

**Comment by lhw5123** [comment]
name 无所谓，主要是包名。

**Comment by cqiuping** [comment]
奥奥 好的 谢谢 我去试试
