### ISSUE TITLE
请教一下这是什么问题

### ISSUE THREAD

**Issue by lofzefjg** [jpush/jpush-phonegap-plugin#302]
```objective-c
-(void)setAlias:(CDVInvokedUrlCommand*)command {
    NSDictionary* params = [command.arguments objectAtIndex:0];
    NSNumber* sequence = params[@"sequence"];
    NSString* alias = params[@"alias"];
```

params 是个@"" 空字符串

**Comment by lhw5123** [comment]
js 端是怎么写的。

**Comment by lofzefjg** [comment]
window.plugins.jPushPlugin.init();
        window.plugins.jPushPlugin.setDebugMode(true);//debug

        window.plugins.jPushPlugin.getUserNotificationSettings(function(result) {
          console.log("getUserNotificationSettings(): "+JSON.stringify(result));
          if(result == 0) {
            console.log("系统设置中已关闭应用推送。");
          } else if(result > 0) {
            console.log("系统设置中打开了应用推送。");
          }
        });

        this.setJPushBadge();
        this.setJPushAlias();

**Comment by lofzefjg** [comment]
initJPush() {
    try {
      if(window && window.plugins && window.plugins.jPushPlugin) {
        window.plugins.jPushPlugin.init();
        window.plugins.jPushPlugin.setDebugMode(true);//debug

        window.plugins.jPushPlugin.getUserNotificationSettings(function(result) {
          console.log("getUserNotificationSettings(): "+JSON.stringify(result));
          if(result == 0) {
            console.log("系统设置中已关闭应用推送。");
          } else if(result > 0) {
            console.log("系统设置中打开了应用推送。");
          }
        });

        this.setJPushBadge();
        this.setJPushAlias();
      }
      else
      {
        console.log('initJPush(): window.plugins.jPushPlugin error. ')
      }

    } catch (exception) {
      console.log(exception);
    }
  }

  /**
   * 设置别名
   */
  setJPushAlias(){
    let alias = '';
    if(this.isLogin()){
      let user:AuthUser = this.getLocalUserInfo();
      alias = user.userId;
      alias = alias.replace(/-/g,'');
    }

    try {
      console.log('will setAlias: '+alias);
      window.plugins.jPushPlugin.setAlias(alias, function(){
        console.log("setJPushAlias Success. alias is "+alias);
      }, function(){
        console.log('setJPushAlias Failure. ');
      });
    } catch (exception) {
      console.log(exception);
    }

  }

  setJPushBadge()
  {
    try
    {
      if (!this.platform.is('android')) {
        //ios
        window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0); // 设置角标，ios方法
        window.plugins.jPushPlugin.resetBadge();//服务器的角标
      } else {
        //android
        //window.plugins.jPushPlugin.setStatisticsOpen(true); // 开启统计分析功能，android方法
      }
    }
    catch (exception)
    {
      console.log(exception);
    }
  }


  // ---------- 极光推送 END ----------

  getLocalUserInfo(): AuthUser{
    var user:AuthUser = null;
    if("true"===localStorage.getItem("isLogin"))
    {
      let u = JSON.parse(localStorage.getItem("userInfo"));
      if(u.jUser.img != null)
      {
        u.jUser.img = this.addImageUrlBase(u.jUser.img);
      }
      user = new AuthUser(u,true);
    }
    else
    {
      user = new AuthUser(null,false);
    }
    return user;
  }

**Comment by lhw5123** [comment]
`setAlias` 方法新版本改了参数，可以参考下[文档](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#setalias)。

**Comment by lofzefjg** [comment]
非常感谢

**Comment by lofzefjg** [comment]
这里不设置别名，推送会成功吗？

**Comment by daileimail** [comment]
^3.4.0版本 android可以 ios能够获取devicetoken 但是setAlias 应用崩溃。
