### ISSUE TITLE
安卓调试时通知栏打开事件jpush.openNotification 完全没有回调，如何监听用户的通知栏打开行为

### ISSUE THREAD

**Issue by eatmyball** [jpush/jpush-phonegap-plugin#303]
RT，测试过三星S8 索尼Z5 VIVOX9等几台机型，回调事件都没有触发，难道是收到jpush.receiveNotification事件后自定义通知栏事件？还望能够解答，谢谢！

**Comment by lhw5123** [comment]
用的插件版本是多少？

**Comment by eatmyball** [comment]
对的，是使用ionic3开发的，推送插件版本是最新的

**Comment by lhw5123** [comment]
贴下代码看一下，我这边测试是没问题的，代码是这样的：
```ts
document.addEventListener('jpush.openNotification', (event: any) => {
      alert('open notification: ' + JSON.stringify(event));
    }, false);
```

**Comment by eatmyball** [comment]
我这边是这样的
document.addEventListener("jpush.receiveMessage", (event)=>{
      LogUtils.logN("Message",JSON.stringify(event));
    },false);
点开通知栏的时候，没有打印日志，但是其他的事件是正常的。

**Comment by lhw5123** [comment]
@eatmyball 你这是 `jpush.receiveMessage` 事件啊。

**Comment by eatmyball** [comment]
Sorry，贴错啦
`document.addEventListener("jpush.openNotification", (event)=>{
      LogUtils.logN("Open",JSON.stringify(event));
    },false);`
不好意思啊

**Comment by eatmyball** [comment]
今天下午又调试了一下，open事件正常了，没有改动任何的代码，请问一下大概会是有什么原因导致这种情况呢？

**Comment by mengkeys** [comment]
苹果上面openNotification事件就是一直调不起来，其他事件都正常，好几天了，还是不行

**Comment by mengkeys** [comment]
@eatmyball @lhw5123 怎么整的呀，都是最新的
