### ISSUE TITLE
发送数据一直使用+1，ios角标数字即使清空了也还会继续+1

### ISSUE THREAD

**Issue by liupeng9030** [jpush/jpush-phonegap-plugin#304]
发送数据时使用+1，ios角标数字正常+1，没有问题。但是我把他清空了后，下次接收到消息，还会在上一次的数字基础上继续+1，很是奇怪，应该显示1。怎么解决？

**Comment by huangminlinux** [comment]
最新社区提了类似的问题，https://community.jiguang.cn/t/jmessage-react-plugin/23488/19 ，在社区上处理了。

**Comment by liupeng9030** [comment]
后来研究了下，用resetBadge方法将极光推送云端的数字清零就行了
