### ISSUE TITLE
$window.plugins.jPushPlugin找不到jPushPlugin是什么情况啊?

### ISSUE THREAD

**Issue by Wjp43045** [jpush/jpush-phonegap-plugin#307]
`
		var _init = function(config) {
			window.plugins.jPushPlugin.init();
			//设置tag和Alias触发事件处理
			document.addEventListener('jpush.setTagsWithAlias', config.stac, false);
			//打开推送消息事件处理
			window.plugins.jPushPlugin.openNotificationInAndroidCallback = config.oniac;

			window.plugins.jPushPlugin.setDebugMode(true);
		}`
报错"TypeError: Cannot read property 'jPushPlugin' of undefined",据说极光依赖的插件cordova-plugin-device也是ionic自己装好了,应该没问题啊,重新生成了好几个项目就是进行不下去了,求助

**Comment by lhw5123** [comment]
用的是浏览器？

**Comment by Wjp43045** [comment]
用的两个手机:一个华为荣耀,一个三星,都是一样的情况,调用函数就报错,打印出来window.plugins是"undefined"

**Comment by Wjp43045** [comment]
目前这种情况,接收官网推送的通知是成功的,但是调用不了插件

**Comment by lhw5123** [comment]
参考下 #179。

**Comment by Wjp43045** [comment]
啊?这个代码是ionic3的JPush代码啊?

**Comment by Wjp43045** [comment]
@lhw5123 你说的#179的这个例子不适合我,我用的ionic版本是1.7.14,并不是ionic2,参考的例子是https://www.cnblogs.com/linsu/p/5641158.html,问题的关键我找到了,是window.plugins undefined并不是JPush插件的问题,只是还没找到解决方案

**Comment by lichicode** [comment]
问题解决了么
