### ISSUE TITLE
ios 角标的问题    角标数量会叠加 ， 如何处理

### ISSUE THREAD

**Issue by valitors** [jpush/jpush-phonegap-plugin#312]
ios：  比如  你收到 四条消息  我进入app  后， 角标清空了。 然后又收到四条消息 。 此时应该显示 4条消息，但是现在显示  4+4 = 8 条消息 ， 没有将之前的4条清空 。 如何清除之前的角标数量。

**Comment by huangminlinux** [comment]
有调用 setbadge 设为 0 吗？
