### ISSUE TITLE
使用Cordova安装时出错

### ISSUE THREAD

**Issue by 170cmcurry** [jpush/jpush-phonegap-plugin#314]
## 你的运行环境

* 插件版本:3.3.0
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):android 7.0.0
* Ionic Version (if using Ionic):3.19.1

## 期望效果

插件可以顺利安装成功

## 实际效果

插件安装失败，提示Failed to install 'jpush-phonegap-plugin': Error: ENOENT: no such file or directory, open 'F:\ionic\bangdele-merchant\platforms\android\AndroidManifest.xml'

## 重现步骤

  1. 在ionic项目下使用 `$ cordova plugin add jpush-phonegap-plugin`

## 背景
1.修改项目下的plugin.xml文件，将`<config-file target="AndroidManifest.xml" parent="/manifest">
`改为`<config-file target="app/src/main/AndroidManifest.xml" parent="/manifest">`，运行结果仍然不成功
2.cordova android 7.0.0将AndroidMainfest.xml路径改变了，希望可以尽快修改过来

**Comment by lhw5123** [comment]
建议添加 android platform 时还是添加 6.4.0 版本。

因为 cordova-android 7.0.0 虽然变更了项目结构，但目前其[文档](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#config-file)上还是指明的是：
```xml
<config-file target="AndroidManifest.xml">
```
这边本地按照你的方式修改了之后尝试安装也还是会有问题。目前打算在 cordova-android 或文档有了进一步更新后，这边会再尝试修改。: )

**Comment by 170cmcurry** [comment]
@lhw5123 谢谢你的解答，我看了这链接[Cordova Android 7.0.0 Released!](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)尝试修改了一下，发现不成功，所以提交这个issue，希望你们可以尽快更新。

**Comment by lhw5123** [comment]
@170cmcurry 最新的 v3.4.0 支持 Cordova Android 7.0.0 了。: )

**Comment by Fengmaybe** [comment]
那现在怎么解决，报错安装不了怎么办？
