### ISSUE TITLE
低版本的是自动升级？还是手动升级啊

### ISSUE THREAD

**Issue by lilechao** [jpush/jpush-phonegap-plugin#315]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
具体是指什么的低版本？如果是插件，就我所知是没法自动更新的。
