### ISSUE TITLE
当app在后台收到notification，openNotification 要触发两次

### ISSUE THREAD

**Issue by qiluo** [jpush/jpush-phonegap-plugin#316]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本: 2.0.5
* 平台（Android / iOS）: iOS 
* Cordova version (```cordova -v```):  7.1 
* Cordova platform version (```cordova platform ls```): iOS 4.5.4
* Ionic Version (if using Ionic)  3.9.2

## 期望效果
无论app在前台还是后台，openNotification只触发一次

## 实际效果

这是监听函数
```
document.addEventListener('jpush.openNotification', (event: any) => {
      console.log('Open notification: ' + JSON.stringify(event));
    }, false);
```
当app在前台时，openNotification只会触发一次。
当杀掉app后测试，点击收到的notification，app被拉起，但openNotification触发了两次

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by huangminlinux** [comment]
可以升级到  + jpush-phonegap-plugin@3.3.3

**Comment by qiluo** [comment]
@huangminlinux , 验证了，现在只有一条event了。谢谢

顺便问个问题，我看文档提到了init和startJPushSDK，但查看ionic的封装源码只有init没有startJPushSDK，可是init里面并没有执行任何初始化代码，请问是为什么？

**Comment by huangminlinux** [comment]
如果不知 delay 的话，插件会自动执行这个这个方法。
