### ISSUE TITLE
ios Jpush前台收不到自定义消息，后台能收到

### ISSUE THREAD

**Issue by xumingyi** [jpush/jpush-phonegap-plugin#318]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: android
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): 
Installed platforms:
  android 6.3.0
  browser 5.0.3
  ios 4.5.4
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic):
3.19.1

## 期望效果

期望ios程序在前台和后台都能收到jpush的自定义消息。

## 实际效果

jpush推送自定义消息 ， 程序启动了后台模式android前后台都好用，ios程序在后台能收到推送消息，在前台就走不到回调的listener里， ios  JPush的时候ios和android需要有什么不同的处理？用的这个插件，
  document.addEventListener("jpush.receiveMessage", this.jpushDefineEventListener, false);//接收自定义消息

## 重现步骤

  1.  this.jpush.init()；
  2.   document.addEventListener("jpush.receiveMessage", this.jpushDefineEventListener, false);//接收自定义消息
  3.  程序在后台，推送自定义消息，能收到。
  4.   程序在前台，用户能看的情况下，推送自定义消息，能不到。

## 背景

尝试关闭和打开后台模式。没有解决             this.backgroundMode.enable();             this.backgroundMode.disable();

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by huangminlinux** [comment]
应用需要在打开状态才接受到自定义消息，不明白你为什么在后台能收到这个事件。

注意自定义消息和推送是完全不同的东西，可以参考 https://docs.jiguang.cn/jpush/client/iOS/ios_sdk/ 这个链接 （自定义消息就是文档中的应用内消息）。

**Comment by huangminlinux** [comment]
通过 registrationID 给 iOS 端发送自定义消息，如果前台还是收不到，可以到[极光社区](https://community.jiguang.cn/) 将你发送失败的 msgId 和 appkey 给官方查查发送状态。

**Comment by xumingyi** [comment]
这个问题是我们服务器端推送的android是 receivedMessage, ios端给推得就是notification 所以ios用receivedMessage的监听收不到回调。
