### ISSUE TITLE
安装了插件build ios 报错，移除插件就不报错

### ISSUE THREAD

**Issue by zhaowanhua** [jpush/jpush-phonegap-plugin#320]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境
mac os 

* 插件版本:
最新
* 平台（Android / iOS）:
ios
* Cordova version (```cordova -v```):
6.0
* Cordova platform version (```cordova platform ls```):
ios 4.0.1
* Ionic Version (if using Ionic)
1.7
## 期望效果
ionic build ios success

## 实际效果

build failed 
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/fontWorkSpace/test/platforms/ios/cordova/build-debug.xcconfig,-project,费控移动.xcodeproj,ARCHS=i386,get,费控移动,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/fontWorkSpace/test/platforms/ios/build/emulator,SHARED_PRECOMPS_DfontWorkSpace/test/platforms/ios/build/sharedpch

**Comment by huangminlinux** [comment]
不支持模拟器i386, 用真机是测试。

**Comment by zhaowanhua** [comment]
首先感谢您的回复，其次，能具体讲下怎么解决这个问题么？有其他人出现这个问题 解决了的 先例么？

**Comment by zhaowanhua** [comment]
@huangminlinux

**Comment by zhaowanhua** [comment]
@huangminlinux 首先感谢您的回复，其次，能具体讲下怎么解决这个问题么？有其他人出现这个问题 解决了的 先例么？
我google 百度 都是说 rm 平台， 重新添加插件和 平台，我也试过了，甚至重装了node，也是不行。

**Comment by zhaowanhua** [comment]
我通过 卸载 6.0的cordova 重装6.5  解决了。
