### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by daileimail** [jpush/jpush-phonegap-plugin#321]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:
* Cordova version (``8.0.0```):
* Cordova platform version (```Installed platforms:
  android 7.0.0
  ios 4.5.4```):
* Ionic Version (if using Ionic)  3.19.1
## 期望效果

ios推送成功
## 实际效果

ios setAlias应用崩溃（android没有问题）
## 重现步骤

  1. 安装
  2. init（）
  3. setAlias（）

## 背景

卸载再安装
## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

**Comment by huangminlinux** [comment]
插件版本多少？ 
用最新版本 demo 测试没有问题。

**Comment by FWiner** [comment]
@huangminlinux 插件版本3.4.1  ios11.1 模拟器  setAlias应用崩溃

**Comment by huangminlinux** [comment]
报什么错误？

**Comment by FWiner** [comment]
@huangminlinux 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x60400045be40'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a0711ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010d4adf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a0f1a34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000109ff40a8 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000109ff3a88 _CF_forwarding_prep_0 + 120
	5   ÊØèÂàªÊä•ÈîÄ                        0x0000000106c125b2 -[JPushPlugin setAlias:] + 146
	6   ÊØèÂàªÊä•ÈîÄ                        0x0000000106c2a7b6 -[CDVCommandQueue execute:] + 870
	7   ÊØèÂàªÊä•ÈîÄ                        0x0000000106c2a021 -[CDVCommandQueue executePending] + 833
	8   Foundation                          0x000000010a528948 __NSThreadPerformPerform + 334
	9   CoreFoundation                      0x000000010a014231 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x000000010a0b3e41 __CFRunLoopDoSource0 + 81
	11  CoreFoundation                      0x0000000109ff8b49 __CFRunLoopDoSources0 + 185
	12  CoreFoundation                      0x0000000109ff812f __CFRunLoopRun + 1279
	13  CoreFoundation                      0x0000000109ff79b9 CFRunLoopRunSpecific + 409
	14  GraphicsServices                    0x0000000110ce49c6 GSEventRunModal + 62
	15  UIKit                               0x000000010b3295e8 UIApplicationMain + 159
	16  ÊØèÂàªÊä•ÈîÄ                        0x0000000106b021e1 main + 65
	17  libdyld.dylib                       0x000000010ed60d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by huangminlinux** [comment]
提供 setAlias 的调用代码和参数。

**Comment by huangminlinux** [comment]
检查参数格式是否有误 

https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#setalias
