### ISSUE TITLE
ionic1  安卓 不能成功注册极光

### ISSUE THREAD

**Issue by zhaowanhua** [jpush/jpush-phonegap-plugin#322]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本: 3.4.1 3.2.1 
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```): 6.0 6.2 6.5 8.0
* Cordova platform version (```cordova platform ls```):6.1.2
* Ionic Version (if using Ionic) 1.76

## 期望效果
安装插件后，在 app.js里面 写入2行代码 启动推送，应该在推送平台 可以 推送全部。

## 实际效果
提示我 并没有 客户端 注册了 sdk等等。

## 重现步骤

完全按照文档来的。

## 背景

更改 cordova 版本 ，尝试 低版本插件

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by huangminlinux** [comment]
有没有日志？
appkey 和 包名是不是匹配的？

**Comment by zhaowanhua** [comment]
首先谢谢您的回复，

**Comment by zhaowanhua** [comment]
我 新 下载了 ionic1的 官方 模版项目， 也是一样的情况。

**Comment by zhaowanhua** [comment]
@huangminlinux

**Comment by zhaowanhua** [comment]
![101b1470-0aea-4a71-b528-951ae307a6f8](https://user-images.githubusercontent.com/22017926/36968332-3e3ea9dc-209d-11e8-9784-ff738868c2f4.png)
![279e5ed4-dfa9-47ec-8818-2059de5dfdb5](https://user-images.githubusercontent.com/22017926/36968340-41368312-209d-11e8-869a-44411c13b3da.png)
![3ae3555a-4c8b-451d-be3b-80461a02867d](https://user-images.githubusercontent.com/22017926/36968349-42d33d3c-209d-11e8-991c-ad6e4778fd14.png)
![0beec851-136d-4a7f-ac04-4f0b77267fc3](https://user-images.githubusercontent.com/22017926/36968359-44f67b74-209d-11e8-867d-1ee3cba7aace.png)
![28f97091-3a9f-49d1-bf45-6120c5c919c8](https://user-images.githubusercontent.com/22017926/36968361-4676f2ee-209d-11e8-8beb-4ed28eceb98a.png)

**Comment by zhaowanhua** [comment]
![0beec851-136d-4a7f-ac04-4f0b77267fc3](https://user-images.githubusercontent.com/22017926/36968584-e5a6b494-209d-11e8-97f2-b5de3f23343e.png)
![3ae3555a-4c8b-451d-be3b-80461a02867d](https://user-images.githubusercontent.com/22017926/36968585-e5dcecb2-209d-11e8-8cfd-d836a4bb00f0.png)
![98d62c50-5f09-4b0c-ba9f-bdfb62a8e8a3](https://user-images.githubusercontent.com/22017926/36968586-e6146282-209d-11e8-8edc-bac5eb7bb0e1.png)
![101b1470-0aea-4a71-b528-951ae307a6f8](https://user-images.githubusercontent.com/22017926/36968587-e65325d0-209d-11e8-8ce9-b451d74ecb5c.png)
![279e5ed4-dfa9-47ec-8818-2059de5dfdb5](https://user-images.githubusercontent.com/22017926/36968588-e68a9510-209d-11e8-929a-4fa63ce3f904.png)
![a8f3ef72-10dc-4fbd-a946-367ecae219af](https://user-images.githubusercontent.com/22017926/36968589-e6cdb084-209d-11e8-83b3-137399614c28.png)

**Comment by zhaowanhua** [comment]
jpush 3.4.1    jcore 1.2.0 
我的android platform 是 6.1.2的

**Comment by lhw5123** [comment]
那需要升级 android platform，或者降级插件。
降级插件的话，你可以先命令行安装 v1.1.12 的 cordova-plugin-jcore：
```shell
cordova plugin add cordova-plugin-jcore@1.1.12
```
然后再安装 v3.3.2 的 jpush-phonegap-plugin：
```shell
cordova plugin add jpush-phonegap-plugin@3.3.2 --variable APP_KEY=xxxx
```

**Comment by zhaowanhua** [comment]
我试试 多谢 @lhw5123

**Comment by zhaowanhua** [comment]
我去 。 原来是版本问题。。。  调了 2天  各种重装，累死了。。。
十分感谢各位，谢谢了
