### ISSUE TITLE
Cordova 集成ios版jpush与其他插件冲突

### ISSUE THREAD

**Issue by wscgithub** [jpush/jpush-phonegap-plugin#323]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

iOS 
cordova 6.3.1
Cordova platform version 4.2.1
ionic 2.2.3

## 期望效果

cordova下载的其他插件和jpush插件不冲突，都能正常使用

## 实际效果
Xcode运行时，只有jpush管用，其他插件都失效

## 重现步骤

  1. ionic plugin add jpush-phonegap-plugin --variable APP_KEY=*****
  2.ionic platform add iOS
  3.Xcode 打开项目
  4. ...

## 背景
cordova plugin rm cordova-plugin-device
cordova plugin add cordova-plugin-device
删除ios.json  删除platform 重新安装jpush

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
 Plugin '插件名称' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
所有插件都是报这个错误，
cordova-plugin-BaiduLBS 1 "BaiduLBS"
cordova-plugin-alipay-v2 0.0.3 "alipay"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-opener2 2.0.7 "File Opener2"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-jcore 1.2.0 "JCore"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-wechat 2.1.0 "Wechat"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
cordova-plugin-x-toast 2.5.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by huangminlinux** [comment]
和题主私下沟通，使用相同的代码我这边 ok，应该是环境问题。
