### ISSUE TITLE
解决i386问题时出现错误

### ISSUE THREAD

**Issue by wscgithub** [jpush/jpush-phonegap-plugin#324]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* ios:
* Cordova version (6.3.1):
* Cordova platform version (```4.2.1```):
* Ionic Version (2.2.3)

## 期望效果
Xcode运行时，所有插件都能正常使用

## 实际效果
在解决i386错误时，使用ionic platform update iOS ,会导致./platform/***/plugin变成空目录，里面的.m文件都没有了

## 重现步骤

  1. ionic plugin add jpush-phonegap-plugin --variable APP_KEY=****
  2. ionic build iOS(会报i386的错误)
  3.ionic platform update ios(解决i386错误)
  4. ionic build iOS
  5.Xcode 打开项目，运行项目，插件失效
## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：
运行 ionic build ios时cmd报错
The following build commands failed:
	Ld build/emulator/***.app/*** normal i386
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/*****/projects/ionic_library_aleph_daxing_without_upgrade/platforms/ios/cordova/build-debug.xcconfig,-project,***.xcodeproj,-target,****-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/****/projects/ionic_library_aleph_daxing_without_upgrade/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/****/projects/ionic_library_aleph_daxing_without_upgrade/platforms/ios/build/sharedpch

**Comment by huangminlinux** [comment]
不支持 iphone5s 之前的模拟器， 换成真机试试
