### ISSUE TITLE
集成最新的推送插件，就是没有拿到registrationID，而且不进入getRegistrationID方法的回调

### ISSUE THREAD

**Issue by skytech-ios-dev** [jpush/jpush-phonegap-plugin#325]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境
mac os x1.13.3
angularjs1.0.0 + ionic + cordova

* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):   "android": "6.2.3","ios": "4.4.0"
* Ionic Version (if using Ionic)
V1.0.0
## 期望效果
连接推送服务，接收推送消息
告诉我们你希望达到什么效果。

## 实际效果
感觉init()没有成功，一直接收不到registrationID
告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
插件版本是多少？jpush-phonegap-plugin 和 cordova-plugin-jcore 的。
