### ISSUE TITLE
使用 ionic cordova plugin add jpush-phonegap-plugin --variable APP_KEY=*******添加插件出错

### ISSUE THREAD

**Issue by nixiaozi** [jpush/jpush-phonegap-plugin#326]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:7.0.0
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):8.0.0
* Ionic Version (if using Ionic)：3.19.1

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

添加插件出错！

## 重现步骤

  1. 直接使用 ionic cordova plugin add jpush-phonegap-plugin --variable APP_KEY=*******命令来添加插件会出现以下错误：
Failed to install 'cordova-plugin-jcore': Error: ENOENT: no such file or directory, open 'E:\InoicProject\WebIonicApp\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\WebIonicApp\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\WebIonicApp\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\WebIonicApp\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\WebIonicApp\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

Failed to install 'jpush-phonegap-plugin': Error: ENOENT: no such file or directory, open 'E:\InoicProject\WebIonicApp\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\WebIonicApp\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\WebIonicApp\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\WebIonicApp\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\WebIonicApp\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)
(node:19620) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'E:\InoicProject\WebIonicApp\platforms\android\AndroidManifest.xml'
(node:19620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## 背景

你尝试做过些什么？
我试过再config.xml文件中的<platform name="android">添加<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" />
添加<preference name="AndroidPersistentFileLocation" value="Compatibility" /> 但是都没有解决问题
 
## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
我这边用新建的 ionic 项目没出现这个问题。确定当前项目的 android platform 版本是 7.0.0 吗？

你可以试下先安装插件，再添加 android platform。

**Comment by nixiaozi** [comment]
@lhw5123  谢谢你的回复！上次这个问题已经没有了，这两天又有新的问题了！
 现在先安装插件再安装android platform 会导致在安装文件的时候替换已经原来的插件版本从3.3.2到版本3.4.1，这样也会编译报错，现在我是安装平台后，在替换插件版本，现在可以正常打包，但是推送功能用不了！在android studio中可以看到如下错误日志：
I/chromium: [INFO:CONSOLE(6151)] "Hello AppHttpClientProvider Provider", source: file:///android_asset/www/build/main.js (6151)
I/chromium: [INFO:CONSOLE(8302)] "Hello AccountProvider Provider", source: file:///android_asset/www/build/main.js (8302)
I/chromium: [INFO:CONSOLE(4707)] "MyApp->issimulationLogin=false", source: file:///android_asset/www/build/main.js (4707)
I/chromium: [INFO:CONSOLE(3918)] "Angular is running in the development mode. Call enableProdMode() to enable the production mode.", source: file:///android_asset/www/build/vendor.js (3918)
I/chromium: [INFO:CONSOLE(1218)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1218)
I/chromium: [INFO:CONSOLE(118650)] "Ionic Native: deviceready event fired after 3674 ms", source: file:///android_asset/www/build/vendor.js (118650)
I/App: WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
W/System.err: java.lang.ClassNotFoundException: cn.jiguang.cordova.push.JPushPlugin
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:400)
W/System.err:     at java.lang.Class.forName(Class.java:326)
W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jiguang.cordova.push.JPushPlugin" on path: DexPathList[[zip file "/data/app/com.jianlian.jsy-2/base.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.jianlian.jsy-2/lib/arm64, /data/app/com.jianlian.jsy-2/base.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 13 more
I/System.out: Error adding plugin cn.jiguang.cordova.push.JPushPlugin.
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: java.lang.ClassNotFoundException: cn.jiguang.cordova.push.JPushPlugin
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:400)
W/System.err:     at java.lang.Class.forName(Class.java:326)
W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jiguang.cordova.push.JPushPlugin" on path: DexPathList[[zip file "/data/app/com.jianlian.jsy-2/base.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.jianlian.jsy-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.jianlian.jsy-2/lib/arm64, /data/app/com.jianlian.jsy-2/base.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.jianlian.jsy-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 13 more
I/System.out: Error adding plugin cn.jiguang.cordova.push.JPushPlugin.
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
我现在使用平台为：
Installed platforms:
  android 6.4.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
现在使用的插件为：
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-app-update 1.5.2 "AppUpdate"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-jcore 1.1.12 "JCore"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-wechat 2.1.0 "Wechat"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
jpush-phonegap-plugin 3.3.2 "JPush"

**Comment by alex-0407** [comment]
前两种方式安装都不行，下载到本地安装才行，这样很不方便，不利于多人开发app，问题解决了没
