### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by myamolane** [jpush/jpush-phonegap-plugin#327]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```):  7.1.0
* Cordova platform version (```cordova platform ls```):6.3.0
* Ionic Version (if using Ionic): 3.19.0

## 期望效果

能正常收到通知

## 实际效果

无法收到通知

## 重现步骤

  1. ionic start empty
  2. npm install
  3. ionic cordova plugin add jpush-phonegap-plugin --variable APP_KEY=xxx
  4. ionic cordova platform add android@6.3.0
  5. ionic cordova build android

## 背景

升级了cordova

## Debug logs

包括 Android 或 iOS 的日志：

03-12 16:00:07.577 20790 20882 W System.err: java.lang.ClassNotFoundException: cn.jiguang.cordova.push.JPushPlugin
03-12 16:00:07.577 20790 20882 W System.err: 	at java.lang.Class.classForName(Native Method)
03-12 16:00:07.577 20790 20882 W System.err: 	at java.lang.Class.forName(Class.java:400)
03-12 16:00:07.577 20790 20882 W System.err: 	at java.lang.Class.forName(Class.java:326)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-12 16:00:07.577 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
03-12 16:00:07.577 20790 20882 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 16:00:07.577 20790 20882 W System.err: 	at android.os.Looper.loop(Looper.java:163)
03-12 16:00:07.577 20790 20882 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-12 16:00:07.578 20790 20882 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jiguang.cordova.push.JPushPlugin" on path: DexPathList[[zip file "/data/app/com.gongfuge.artisantest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gongfuge.artisantest-1/lib/arm64, /system/lib64, /vendor/lib64]]
03-12 16:00:07.578 20790 20882 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-12 16:00:07.578 20790 20882 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-12 16:00:07.578 20790 20882 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-12 16:00:07.578 20790 20882 W System.err: 	... 13 more
03-12 16:00:07.578 20790 20882 I System.out: Error adding plugin cn.jiguang.cordova.push.JPushPlugin.
03-12 16:00:07.578 20790 20882 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
03-12 16:00:07.578 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
03-12 16:00:07.578 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-12 16:00:07.578 20790 20882 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-12 16:00:07.578 20790 20882 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-12 16:00:07.578 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-12 16:00:07.578 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
03-12 16:00:07.578 20790 20882 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 16:00:07.578 20790 20882 W System.err: 	at android.os.Looper.loop(Looper.java:163)
03-12 16:00:07.578 20790 20882 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-12 16:00:07.580 20790 20882 W System.err: java.lang.ClassNotFoundException: cn.jiguang.cordova.push.JPushPlugin
03-12 16:00:07.580 20790 20882 W System.err: 	at java.lang.Class.classForName(Native Method)
03-12 16:00:07.580 20790 20882 W System.err: 	at java.lang.Class.forName(Class.java:400)
03-12 16:00:07.580 20790 20882 W System.err: 	at java.lang.Class.forName(Class.java:326)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-12 16:00:07.580 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
03-12 16:00:07.580 20790 20882 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 16:00:07.580 20790 20882 W System.err: 	at android.os.Looper.loop(Looper.java:163)
03-12 16:00:07.580 20790 20882 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-12 16:00:07.580 20790 20882 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jiguang.cordova.push.JPushPlugin" on path: DexPathList[[zip file "/data/app/com.gongfuge.artisantest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gongfuge.artisantest-1/lib/arm64, /system/lib64, /vendor/lib64]]
03-12 16:00:07.581 20790 20882 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-12 16:00:07.581 20790 20882 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-12 16:00:07.581 20790 20882 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-12 16:00:07.581 20790 20882 W System.err: 	... 13 more
03-12 16:00:07.581 20790 20882 I System.out: Error adding plugin cn.jiguang.cordova.push.JPushPlugin.
03-12 16:00:07.581 20790 20882 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
03-12 16:00:07.581 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
03-12 16:00:07.581 20790 20882 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-12 16:00:07.581 20790 20882 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-12 16:00:07.581 20790 20882 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-12 16:00:07.581 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-12 16:00:07.581 20790 20882 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
03-12 16:00:07.581 20790 20882 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 16:00:07.581 20790 20882 W System.err: 	at android.os.Looper.loop(Looper.java:163)
03-12 16:00:07.581 20790 20882 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lhw5123** [comment]
<img width="894" alt="c07506dc-eb34-4c63-ba27-84c2b0def475" src="https://user-images.githubusercontent.com/6531354/37445841-1c770d16-2855-11e8-8924-5001ecc9324d.png">

**Comment by myamolane** [comment]
$ ionic cordova plugin ls
> cordova plugin ls
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-jcore 1.2.0 "JCore"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
jpush-phonegap-plugin 3.4.1 "JPush"

**Comment by lhw5123** [comment]
你项目添加的 android platform 是 6.3.0，所以卸载安装下 v3.4.0 版本之前的插件。

**Comment by myamolane** [comment]
谢谢，不好意思, 误解了这个cordova-android
