### ISSUE TITLE
关于openNotification在app启动后的触发

### ISSUE THREAD

**Issue by qiluo** [jpush/jpush-phonegap-plugin#329]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本: 3.3.3
* 平台（Android / iOS）: iOS
* Cordova version (```cordova -v```): 7.1 
* Cordova platform version (```cordova platform ls```): iOS 4.5.4
* Ionic Version (if using Ionic) 3.9.2

## 重现步骤
当app进程kill后收到push message，验证是否可以监听到openNotification event。

* 如果在app.component.ts deviceReady后立刻添加addEventListener到openNotification，可以触发。
* 如果在home.ts中才添加openNotification event handler，就触发不了。

请问事件触发和代码的添加时机有什么关系？

**Comment by huangminlinux** [comment]
插件初始化前的事件会有缓存， 成功 init 后才对事件下发给 js

**Comment by qiluo** [comment]
肯定都是在init之后才`document.addEventListener('jpush.openNotification', ...`， 根据你的解释，我更觉得什么时候addEventListener都应该可以接收到事件。

可我实际验证，init在deviceReady，如果addEventListener随后，可以收到openNotification。 如果addEventListener放到HomeComponent的构造函数中，就收不到openNotification

谢谢

**Comment by huangminlinux** [comment]
如果应用没有启动的话，确保事件触发前监听这个事件。不然事件已经触发了还没执行监听动作也没法收到。

**Comment by qiluo** [comment]
谢谢，明白了
