### ISSUE TITLE
app_key 如果在js代码中设置？

### ISSUE THREAD

**Issue by CK110** [jpush/jpush-phonegap-plugin#330]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)

## 期望效果

app_key 如果在js代码中设置，这样就可以区分不同环境，不需要每次都要修改config.xml

## 实际效果

在js中初始化的时候，调用init()方法，传入 app_key的参数

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by huangminlinux** [comment]
正常来说 appkey 参数并不需要频繁的修改，安装插件的时候传入这个字段就可以了。
