### ISSUE TITLE
如何在ionic3 里消除角标，看完通知后角标还在

### ISSUE THREAD

**Issue by mrpeng** [jpush/jpush-phonegap-plugin#333]
如何在ionic3 里消除角标，看完通知后角标还在

**Comment by mrpeng** [comment]
我在example没找到setBadge, 怎么用法？在监听打开通知里写一句吗？写一句
setBadge(0);
?

**Comment by mrpeng** [comment]
有回复不？

**Comment by huangminlinux** [comment]
在需要的地方调用就行 ，没有特别的限制， 事件 或者正常业务逻辑里面都可以。

**Comment by mrpeng** [comment]
是用这几句？我用了没反应，是不是漏了什么？

**Comment by huangminlinux** [comment]
jpush.openNotification 事件触发了吗？

**Comment by mrpeng** [comment]
https://community.jiguang.cn/t/topic/13924
我要把以下代码放进去吗？
[[UIApplication sharedApplication] setApplicationIconBadgeNumber:(int)value];
[[UIApplication sharedApplication] setApplicationIconBadgeNumber:0]; //清除角标
//以上方法在任何地方均可调用，根据自己的需要设定即可。譬如：

//杀死后点击icon进入时清除角标
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
application.applicationIconBadgeNumber = 0;
}
//从后台点击icon进入时清除角标
func applicationWillEnterForeground(_ application: UIApplication) {
application.applicationIconBadgeNumber = 0;
}

**Comment by mrpeng** [comment]
我也这么写过，但不正确，看来我的上面还有别的问题。先去排查下。

**Comment by mrpeng** [comment]
constructor(jpush: JPush, device: Device,)
没留意，少了个public
constructor(public jpush:JPush,
