### ISSUE TITLE
按照文档进行安装使用，无法获取到 Registration Id

### ISSUE THREAD

**Issue by Jackenen** [jpush/jpush-phonegap-plugin#337]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:最新版
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):7.1
* Cordova platform version (```cordova platform ls```):
  android 5.1.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic)
3.19.0
## 期望效果

告诉我们你希望达到什么效果。
获取到 Registration Id
## 实际效果

告诉我们实际是什么效果。
获取 Registration Id按钮点击无反应，获取不到Registration Id
## 重现步骤

  1.按照文档进行安装使用插件核对APPkey和包名一致，init方法有调用

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：
点击获取 Registration Id按钮无反应，日志没有报任何内容
* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by haowenb** [comment]
插件版本：最新版
jcore-android-1.1.9.jar
jpush-android-3.1.1.jar
平台：android
$ cordova -v
7.0.1
$ cordova platform ls
Installed platforms:
  android 6.2.3
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0
$ ionic -v
1.7.14


期望效果：注册成功并获取到 Registration Id 正常接收推送
实际效果：获取 Registration Id按钮点击无反应，获取不到Registration Id，没有进入callback
重现步骤：1.app.js中调用 init方法
this.init = function() {
            document.addEventListener('jpush.receiveRegistrationId', function (event) {
              console.log("注册成功"+event.registrationId)
            }, false)
        	// window.plugins.jPushPlugin.init();
            window.JPush.init()
            if (platform == 'iOS') {
                window.plugins.jPushPlugin.setDebugModeFromIos();
            	window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
            } else if (platform == 'Android') {
            	window.plugins.jPushPlugin.setDebugMode(true);
            }
        }

2.点击登录按钮后调用getRegistrationID

背景：这个报名我原来绑定的是别的jpush应用，后来我从jpush平台上删掉了原来的项目，新建了一个test项目，并在项目上把插件卸载重装更换了新的appkey。然后就出现这个问题了。然后我把代码按照新文档的内容核对了一遍，并多次卸载重装插件，问题依旧存在。
包括 Android 或 iOS 的日志：
点击获取 Registration Id按钮无反应，日志没有报任何内容

希望打什么能指导一下，问题到底出在哪里？已经延期一天了

**Comment by JoshLipan** [comment]
注意：插件从 v3.4.0 开始支持 cordova-android 7.0.0，因 cordova-android 7.0.0 修改了 Android 项目结构，因此不兼容之前的版本，升级前请务必注意。

    如果需要安装之前版本的插件，请先安装 v1.2.0 以下版本（建议安装 v1.1.12）的 cordova-plugin-jcore，再安装旧版本插件（比如 v3.3.2），否则运行会报错。
