### ISSUE TITLE
jpush初始化和获取RegistrationID失败

### ISSUE THREAD

**Issue by lordmos** [jpush/jpush-phonegap-plugin#339]
## 你的运行环境

* 插件版本:3.1.1
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):6.5.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.1.2
  ios 4.1.1
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
* Ionic Version (if using Ionic)
2.2.3

## 期望效果
注册JPUSH成功

## 实际效果
jpush.init()和jpush.getRegistrationID()无效

## 重现步骤

根据官网方法集成jpush，包名和AppKey没有问题

## Debug logs

包括 Android 或 iOS 的日志：

Android LogCat报错

04-19 09:27:40.061 31252-31252/com.yixiang.manager D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 132 : login jpush
04-19 09:27:40.062 31252-31252/com.yixiang.manager I/chromium: [INFO:CONSOLE(132)] "login jpush", source: file:///android_asset/www/build/main.js (132)
04-19 09:27:40.110 31252-31383/com.yixiang.manager W/System.err:     at cn.jpush.android.api.JPushInterface.init(SourceFile:110)
04-19 09:27:40.110 31252-31383/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.init(JPushPlugin.java:259)
04-19 09:27:40.111 31252-31383/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
04-19 09:27:40.154 31252-31520/com.yixiang.manager W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
04-19 09:27:40.155 31252-31520/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
04-19 09:27:40.155 31252-31520/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
04-19 09:27:40.205 31252-31518/com.yixiang.manager W/System.err:     at cn.jpush.android.service.ServiceInterface.a(SourceFile:140)
04-19 09:27:40.205 31252-31518/com.yixiang.manager W/System.err:     at cn.jpush.android.a.k.a(SourceFile:91)
04-19 09:27:40.205 31252-31518/com.yixiang.manager W/System.err:     at cn.jpush.android.a.k.a(SourceFile:150)
04-19 09:27:40.205 31252-31518/com.yixiang.manager W/System.err:     at cn.jpush.android.api.JPushInterface.setAlias(SourceFile:476)
04-19 09:27:40.206 31252-31518/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.setAlias(JPushPlugin.java:380)
04-19 09:27:40.206 31252-31518/com.yixiang.manager W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)

**Comment by crapthings** [comment]
init 是同步的？
多执行几次 getRegistrationID，看看能不能拿到？

**Comment by lordmos** [comment]
init有回调吗？

**Comment by crapthings** [comment]
没有回调，我们就是 隔一会儿 pull 一次 确认有了执行的下一步

**Comment by lordmos** [comment]
问题解决了，建议写到你们的文档中。
由于新版本的JPush的目录结构发生相应的修改而老版本的Cordova Android目录（我的是6.1.2）没有修改，因此需要做两件事情。

1. 将platforms/android/app/src/main/java下的cn.jiguang.*拷贝到platforms/android/src/目录下
2. 将platforms/android/jniLibs下的所有cpu型号文件夹拷贝到platforms/android/libs目录下

做完这两个步骤，编译运行。问题就解决了。

另外在使用JPush时需要在ionic中使用以下代码

`
			this.jpush.init().then(() => {
				this.jpush.getRegistrationID().then(rId => console.log("getRegistrationID success : " + rId));
				this.jpush.setAlias({ sequence: 0, alias: 'zhongwei_' + this.getUserInfo().id })
					.then(this.aliasResultHandler)
					.catch(this.errorHandler);
			});`

**Comment by lordmos** [comment]
issue可以关闭了

**Comment by alex-0407** [comment]
这个问题解决了没

**Comment by zlfeeling** [comment]
注意：插件从 v3.4.0 开始支持 cordova-android 7.0.0，因 cordova-android 7.0.0 修改了 Android 项目结构，因此不兼容之前的版本，升级前请务必注意。

如果需要安装之前版本的插件，请先安装 v1.2.0 以下版本（建议安装 v1.1.12）的 cordova-plugin-jcore，再安装旧版本插件（比如 v3.3.2），否则运行会报错。
