### ISSUE TITLE
iOS RegistrationID 获取不到

### ISSUE THREAD

**Issue by EY5740** [jpush/jpush-phonegap-plugin#341]
安卓系统可以获取到ID 并注册成功。但IOS运行时 有提示获取通知栏权限。但拿到RegistrationID 是空的。
项目代码是最新的，今天刚创建的。

**export function coradovaPushInit (callback) {
  try {
    window.JPush.startJPushSDK()
    window.JPush.init()
  } catch (e) {
    alert('推送消息初始化失败')
  }
  if (callback) {
    callback()
  }
}**

**coradovaPushInit()
    coradovaFirstReg(function (msg) {
      if (msg === '') {
        // 进到这里面来了
      } 
    })**

**Comment by cocfident** [comment]
我也遇到了这个问题，是在注册成功后获取的 也是获取失败？求解答

**Comment by EY5740** [comment]
## 问题解决了
- 首先调试时在模拟器上运行是无效的,必须要真机调试。
- 其次，首次注册事件(jpush.receiveRegistrationId)应该方法 cordova(phoneGap)的onDeviceReady 事件里面监听
- 然后监听事件应该在jpush初始化之前执行。也就是说 在onDeviceReady里面先执行receiveRegistrationId， 然后执行 JPush.init()
- xcode 中 push 权限要开启。
