### ISSUE TITLE
SetTag,addTag,deleteTag Methods not working 

### ISSUE THREAD

**Issue by 10061994** [jpush/jpush-phonegap-plugin#342]
I put this code on device ready event and there is no success alert come.Can you Please please respond very fast we need to launch app.Please help me.Thank you so much
Window . JPush . setTags ({ sequence :  1 , tags : [ ' tag1 ' , ' tag2 ' ] },
  ( result ) => {
alert('result');
     var sequence =  result . sequence 
    var tags =  result . tags   // array type 
  }, ( error ) => {
alert('error');
     var sequence =  error . sequence 
    var errorCode =  error . code 
  })

Window . JPush . addTags ({ sequence :  1 , tags : [ ' tag1 ' , ' tag2 ' ] },
  ( result ) => {
alert('result');
     var sequence =  result . sequence 
    var tags =  result . tags   // array type 
  }, ( error ) => {
alert('error');
     var sequence =  error . sequence 
    var errorCode =  error . code 
  })

Window . JPush . deleteTags ({ sequence :  1 , tags : [ ' tag1 ' , ' tag2 ' ] },
  ( result ) => {
alert('result');
     var sequence =  result . sequence 
  }, ( error ) => {
alert('error');
     var sequence =  error . sequence 
    var errorCode =  error . code 
  })

**Comment by huangminlinux** [comment]
其他接口是否正常？
