### ISSUE TITLE
在Cordova中不能正常使用该插件，获取不到registrationId等问题

### ISSUE THREAD

**Issue by user-zhaoyang** [jpush/jpush-phonegap-plugin#344]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:
* Cordova version (```8.0```):
* Cordova platform version (```android 6.4.0、ios 4.5.4```):

## 期望效果

可以使用jpush插件

## 实际效果

使用提供的demo获取不到registrationId，根据文档写也不能正常使用

## 重现步骤

  1. cordova plugin add jpush-phonegap-plugin --variable APP_KEY=我的appkey
  2. 将example文件内的文件放到Cordova项目中的www目录中
  3. cordova build ios

## 背景

你尝试做过些什么？

## Debug logs

2018-05-03 14:13:20.926223+0800 应用名[30954:1165473] ### pluginInitialize
2018-05-03 14:13:21.926402+0800 应用名[30954:1165473] Cordova callback block returned unrecognized type: (null)
2018-05-03 14:13:21.930044+0800 应用名[30954:1165473] Javascript Callback Error: null

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by user-zhaoyang** [comment]
感谢，已经解决了，我觉得问题主要出在我使用的是模拟器进行调试，Cordova Android版本是6.4，使用最新版的jpush插件会有问题吧，随后尝试
cordova-plugin-jcore@1.1.12
jpush-phonegap-plugin@3.3.2
在真机中可以收到推送消息。
感谢🙏

**Comment by huangminlinux** [comment]
👌
