### ISSUE TITLE
Xcode9.3打包后无法registrationID以及setAlias

### ISSUE THREAD

**Issue by WXAK** [jpush/jpush-phonegap-plugin#347]
## 你的运行环境

* 插件版本:
* 平台（iOS）:
* Cordova version (7.0.1):
* Cordova platform version (4.4.0):
* Ionic Version (3.20.0)

## 期望效果

Xcdoe9.3以及最新Xcdoe9.3.1打包后，可以registrationID以及setAlias

## 实际效果

Xcdoe9.3打包后无法registrationID以及setAlias；
低版本的Xcdoe8.3打包后可以registrationID以及setAlias。

## 重现步骤

  1.Xcdoe9.3真机运行项目（开发环境），可以registrationID以及setAlias；
  2. Xcdoe9.3打包（Ad Hoc证书和环境），无法registrationID以及setAlias；
  3.上传App Store（App Store证书和环境），无法registrationID以及setAlias；
  4.  低版本的Xcdoe8.3打包（Ad Hoc证书和环境），可以registrationID以及setAlias；

## 背景

jpush的plugin已经很长时间没有更新了，目前Xcode已经更新到了9.3.1版本了，如果只降低Xcode版本，无法满足iOS11.3及以上用户的需求

## Debug logs

日志就不在这贴了，问题是测试了好几天发现的，一直以为是自己的jpush配置有问题，后来用低版本的Xcode打包才发现，先这么多吧。

**Comment by zhuhee** [comment]
我们和你遇到了同样的问题，折腾死了。。。

**Comment by WXAK** [comment]
@zhuhee 这个问题已经持续一段时间了，目前还没找到有效的解决方法，iOS版本更新很快，用户基本都会根据系统提示升级

**Comment by zhuhee** [comment]
@WXAK 刚才下载了9.1版本又试了试，也没问题，一会试试9.3版本，有可能是9.3.1这个版本的问题

**Comment by huangminlinux** [comment]
用 xcode9.3 打包 adhoc，使用 iOS9.3 和 iOS11.3.1 测试功能正常，可以获取 rid

**Comment by WXAK** [comment]
经过一系列测试，终于测试出问题的原因了。
下面重现下我这边的问题，不一定适合其他的bug

**Comment by WXAK** [comment]
不知道咋添加图片😔
https://community.jiguang.cn/t/xcode9-3-registrationid-setalias/26745/4

**Comment by WXAK** [comment]
新建了一个ionic项目
配置好Push Notifications的功能，少了entitlements文件
查看下签名，多出来了两个plist文件，估计是Xcode9系列更新的entitlements文件。

有问题就得解决，用低版本的Xcode打开，我用的Xcode8.3
修复一下，奇迹出现了，entitlements文件又回来了
而且签名的entitlements文件也回来了，经过测试，打包的APP又可以setAlias、registrationID🎉🎉🎉

**Comment by WXAK** [comment]
总结：
1、Xcode9系列添加Push Notifications功能，把entitlements文件换成了两个开发环境的plist文件；
2、低版本的Xcode可以修改回entitlements文件，使消息正常推送；
3、这个issues可以关掉了
