### ISSUE TITLE
自动安装能解决后期还需要手动修改的问题吗？

### ISSUE THREAD

**Issue by qdsang** [jpush/jpush-phonegap-plugin#35]
@zhangqinghe

**Comment by zhangqinghe** [comment]
不能,后期还需要自己手动修改问题。

**Comment by qdsang** [comment]
@zhangqinghe 
https://github.com/qdsang/jpush-phonegap-plugin/tree/patch-1
我改了盲改了一个版本，没有IOS开发账号，安装Android SDK异常慢。 没法测试

**Comment by zhangqinghe** [comment]
@qdsang 这个方法不能修改android工程的manifest.xml文件中的JPUSH_APPKEY和JPUSH_CHANNEL

**Comment by qdsang** [comment]
@zhangqinghe 刚刚修改了下应该可以了

**Comment by qdsang** [comment]
@zhangqinghe 
![image](https://cloud.githubusercontent.com/assets/804455/6977979/9c362b96-d9fb-11e4-8b34-ebd5b829becb.png)
这个是什么意思？ 缺少统计代码~
以前没弄过Push， CHANNEL 是标记包的环境的吗？

**Comment by zhangqinghe** [comment]
it should add JPush code in Android local,please see the issue #31:https://github.com/jpush/jpush-phonegap-plugin/issues/31

**Comment by zhangqinghe** [comment]
@qdsang log太少了看不出来崩溃原因

**Comment by qdsang** [comment]
@zhangqinghe 虚拟机是x86原因导致的， 加入x86 so解决了
