### ISSUE TITLE
iOS生产环境有问题，开发环境可以获取的到registrationID

### ISSUE THREAD

**Issue by user-zhaoyang** [jpush/jpush-phonegap-plugin#350]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:ios
* Cordova version (8.0):
* Cordova platform version (ios 4.5.4):
* Ionic Version (if using Ionic)
cordova-plugin-jcore 1.1.12
jpush-phonegap-plugin 3.3.2

## 期望效果

生产环境可以推送

## 实际效果

生产环境推送无效

## 重现步骤

  1. 极光平台配置好证书
  2. 安装Cordova极光推送插件
  3. 在极光平台对开发环境的手机和生产环境的手机进行推送
  4.安装完上架的app后再安装本地开发的代码获取不到registrationID

## 背景

弹窗显示registrationID是“”空

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  registrationID
2018-05-23 10:22:40.996136+0800 XXXX[1306:452210] JPushPlugin:registrationID is
2018-05-23 10:22:42.000365+0800 XXXX[1306:452309]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2018-05-23 10:22:42.003603+0800 XXXX[1306:452210] JPushPlugin:registrationID is
2018-05-23 10:22:43.007553+0800 XXXX[1306:452257]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2018-05-23 10:22:43.010830+0800 XXXX[1306:452210] JPushPlugin:registrationID is
2018-05-23 10:22:44.014727+0800 XXXX[1306:452257]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2018-05-23 10:22:44.018825+0800 XXXX[1306:452210] JPushPlugin:registrationID is

**Comment by ankitkmishra** [comment]
I am also facing this  issue 
xcode version :9.3
Cordova version :6.5.0
Cordova platform version (ios 4.3.1)
cordova-plugin-jcore :1.2.0
jpush-phonegap-plugin :3.4.2


On xcode 9.2 this works fine

**Comment by huangminlinux** [comment]
做如下检查：
- 找到 TARGET -> Capabilities -> Push Notification 选项点开
- 找到 TARGET -> Build Setting -> Code Signing Identity  -> Code Signing Entitlements   *****Entitle-release.plist 看看有没有 aps-environment 字段，没有补上

```
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

**Comment by user-zhaoyang** [comment]
@huangminlinux 解决了，是这个问题。感谢，😊

**Comment by huangminlinux** [comment]
@13951821405 是的。

**Comment by chenfengjw163** [comment]
@13951821405 我的生产环境是production 测试是可用的

**Comment by liuxiaofan** [comment]
@huangminlinux   
第一次接触iOS，请问找到 “TARGET -> Build Setting -> Code Signing Identity -> Code Signing Entitlements *****Entitle-release.plist 看看有没有 aps-environment 字段，没有补上  ”  这句什么意思？
我的xcode 是 9.4.1，  Code Signing Identity  下没有Code Signing Entitlements，也没有Entitle-release.plist 这个文件，也是搞了好几天了，一直都是开发环境可以，生产环境不可以。请大神帮帮

**Comment by jipf2016** [comment]
多谢指点，看上去是一个问题，但是我找不到后面这个        -> Code Signing Entitlements *****Entitle-release.plist  

![qq 20180723140346](https://user-images.githubusercontent.com/21164450/43060266-b321a508-8e82-11e8-94e6-e03438f2f8e6.jpg)

**Comment by jipf2016** [comment]
非常感谢，已解决。我无知了，这里是让修改文件，修改 相应目录下****-release.list 文件。
非常感谢。

**Comment by Lbywer** [comment]
![image](https://user-images.githubusercontent.com/16092821/44513363-bf333980-a6ef-11e8-8ff2-8bd9b4ae73e1.png)
请问这个在哪里可以找到呢。我的xcode版本为9.4.1

**Comment by Lbywer** [comment]
![image](https://user-images.githubusercontent.com/16092821/44514058-a75cb500-a6f1-11e8-9603-66151b0ddcd0.png)
找到了。这里会有文件的绝对路径。去文件夹里找到这个文件jiu就可以了。
