### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jnlt33** [jpush/jpush-phonegap-plugin#354]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
jpush-phonegap-plugin 3.3.2 "JPush"
* 平台（Android / iOS）:
* Cordova version (```cordova -v```):
android:6.2.1
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

ound for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:33.076 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:33.076 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:33.076 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:33.077 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:33.077 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:33.077 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:33.077 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:33.078 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:33.078 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:33.078 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:33.079 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:33.079 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:33.079 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:33.079 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:33.080 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:33.082 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649952',true,1,[""],false);
06-07 14:34:33.084 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:33.084 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:34.089 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:34.098 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:34.172 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:34.173 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:34.174 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]
06-07 14:34:34.174 598-739/com.mmv.lmy W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:34.175 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:34.175 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:34.175 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:34.175 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:34.176 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:34.176 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:34.177 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:34.177 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:34.177 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:34.177 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:34.178 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:34.178 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:34.178 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:34.180 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:34.180 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:34.182 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649953',true,1,[""],false);
06-07 14:34:34.185 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:34.185 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:35.189 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:35.197 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:35.272 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:35.272 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:35.273 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]
06-07 14:34:35.273 598-739/com.mmv.lmy W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:35.274 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:35.274 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:35.275 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:35.275 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:35.275 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:35.276 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:35.276 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:35.277 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:35.277 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:35.277 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:35.278 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:35.278 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:35.278 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:35.279 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:35.279 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:35.282 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649954',true,1,[""],false);
06-07 14:34:35.285 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:35.285 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:36.296 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:36.309 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:36.408 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:36.408 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:36.408 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:36.408 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:36.409 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:36.409 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:36.409 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:36.409 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:36.409 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:36.409 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:36.409 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649955',true,1,[""],false);
06-07 14:34:36.411 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:36.411 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:37.414 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:37.421 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:37.533 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:37.540 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:37.541 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:37.541 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:37.542 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:37.542 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:37.542 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:37.542 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:37.542 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649956',true,1,[""],false);
06-07 14:34:37.544 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:37.544 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:38.547 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:38.555 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:38.628 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:38.629 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:38.630 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]
06-07 14:34:38.630 598-739/com.mmv.lmy W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:38.631 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.service.Protocol.GetSdkVersion(Native Method)
06-07 14:34:38.632 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:38.632 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.d.a.a(Unknown Source)
06-07 14:34:38.632 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.init(Unknown Source)
06-07 14:34:38.633 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.api.JCoreInterface.getRegistrationID(Unknown Source)
06-07 14:34:38.634 598-739/com.mmv.lmy W/System.err:     at cn.jpush.android.api.JPushInterface.getRegistrationID(SourceFile:226)
06-07 14:34:38.635 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin.getRegistrationID(JPushPlugin.java:345)
06-07 14:34:38.635 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-07 14:34:38.635 598-739/com.mmv.lmy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-07 14:34:38.636 598-739/com.mmv.lmy W/System.err:     at cn.jiguang.cordova.push.JPushPlugin$5.run(JPushPlugin.java:249)
06-07 14:34:38.636 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 14:34:38.636 598-739/com.mmv.lmy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 14:34:38.637 598-739/com.mmv.lmy W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-07 14:34:38.637 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] JCore .so file do not match JCore .jar file in the project, Failed to init JCore
06-07 14:34:38.638 598-739/com.mmv.lmy W/JIGUANG-JCore: [JCoreInterface] JCore init failed
06-07 14:34:38.640 598-598/com.mmv.lmy D/WebView: evaluateJavascript=cordova.callbackFromNative('JPushPlugin444649957',true,1,[""],false);
06-07 14:34:38.642 598-598/com.mmv.lmy D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 28 : JPushPlugin:registrationID is 
06-07 14:34:38.642 598-598/com.mmv.lmy I/chromium: [INFO:CONSOLE(28)] "JPushPlugin:registrationID is ", source: file:///android_asset/www/index.html (28)
06-07 14:34:39.646 598-739/com.mmv.lmy D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
06-07 14:34:39.654 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreServiceUtils] set Push/Alarm Receiver enabled
06-07 14:34:39.724 598-739/com.mmv.lmy D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.1.9, buildId:172
06-07 14:34:39.725 598-739/com.mmv.lmy E/art: No implementation found for int cn.jiguang.service.Protocol.GetSdkVersion() (tried Java_cn_jiguang_service_Protocol_GetSdkVersion and Java_cn_jiguang_service_Protocol_GetSdkVersion__)
06-07 14:34:39.726 598-739/com.mmv.lmy E/JIGUANG-JCore: [JCoreGlobal] Get sdk version fail![获取sdk版本失败!]

**Comment by JoshLipan** [comment]
注意事项里面写了，android版本问题，参照[#339](https://github.com/jpush/jpush-phonegap-plugin/issues/339)
