### ISSUE TITLE
iOS APP关闭状态,点击推送消息,执行2次onOpenNotification方法.

### ISSUE THREAD

**Issue by zhangjingle** [jpush/jpush-phonegap-plugin#355]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
	jpush-phonegap-plugin-3.3.2
	cordova-plugin-jcore-1.1.12
* 平台（Android / iOS）:
	iOS
* Cordova version (```cordova -v```):
	8.0.0
* Cordova platform version (```cordova platform ls```):
	android 6.4.0
	ios 4.5.4
* Ionic Version (if using Ionic)
	
## 期望效果
	iOS平台,APP关闭状态下,收到推送消息,点击推送消息,启动APP,此时仅执行 onOpenNotification(event) 方法1次
## 实际效果
	iOS平台,APP关闭状态下,收到推送消息,点击推送消息,启动APP,执行 onOpenNotification(event) 方法2次 (alert 了两次 "open Notification:" + alertContent)
## 重现步骤
  1. 创建cordova项目,add iOS/android平台
  2. github下载 cordova-plugin-jcore-1.1.12 和 jpush-phonegap-plugin-3.3.2
  3. cordova add plugin /User/xxx/xxx/cordova-plugin-jcore-1.1.12 --save
	cordova add plugin /User/xxx/xxx/jpush-phonegap-plugin-3.3.2 --variable APP_KEY=xxxxxxxx --save
  4. 拷贝jpush-phonegap-plugin-3.3.2/example目录下的内容到 cordova
项目的www目录下
  5. 配置相关证书和描述文件等,运行在iOS设备上
  6. iOS APP启动,授权消息通知弹框点击"允许"
  7. kill APP,进入极光推送管理端,发送消息,发送成功,设备接收到消息,点击消息,启动APP,提示 两次 alert (open Notification:.....)

## 背景
	设备信息:iPhone7 iOS11.3

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by zhangjingle** [comment]
插件换成 jpush-phonegap-plugin@3.3.3 版本就解决了.
https://github.com/jpush/jpush-phonegap-plugin/issues/316

另外,有两个问题
1.在首页有一段提示,这个提示用3.3.2的版本,是不是改成3.3.3的会好一点.
_注意：插件从 v3.4.0 开始支持 cordova-android 7.0.0，因 cordova-android 7.0.0 修改了 Android 项目结构，因此不兼容之前的版本，升级前请务必注意。

如果需要安装之前版本的插件，请先安装 v1.2.0 以下版本（建议安装 v1.1.12）的 cordova-plugin-jcore，再安装旧版本插件（**比如 v3.3.2**），否则运行会报错。_

2.在release历史中,没找到3.3.3 版本,只有3.3.2
 https://github.com/jpush/jpush-phonegap-plugin/releases

**Comment by JoshLipan** [comment]
npm上有发布3.3.2，没打release
