### ISSUE TITLE
设置别名在安卓5.1版本中无法执行

### ISSUE THREAD

**Issue by lichicode** [jpush/jpush-phonegap-plugin#358]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android）:
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.4
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS:
Node Version: v4.4.7

## 期望效果

在安卓5.1版本设置别名（安卓7.0是可以的）；

## 实际效果

代码无法执行,id无法弹出

## 重现步骤

```
//启动极光推送服务
    window.JPush.init();
    window.JPush.setDebugMode(true);
    window.JPush.getRegistrationID(function(rId) {
      alert(rId);
     
    })

    try {
      window.JPush.setAlias({ sequence: 1, alias: 'bbb' },
  (result) => {
    var sequence = result.sequence
    var alias = result.alias
    alert(JSON.stringify(result));
  }, (error) => {
    var sequence = error.sequence
    var errorCode = error.code
    alert(error);
  })
    } catch (exception) {
      alert(JSON.stringify(exception));
    }
```

**Comment by JoshLipan** [comment]
使用的哪个版本，设置失败报错没有？

**Comment by lichicode** [comment]
cordova-plugin-jcore" spec="^1.1.12"
jpush-phonegap-plugin" spec="^3.3.2"
 3.4.2最新版本7.0也无法运行，所以用了3.3.2版本

**Comment by lichicode** [comment]
setDebugMode 不知道在哪里看，应该是报错了。

**Comment by JoshLipan** [comment]
需要你在初始化之前调用window.JPush.setDebugMode(true)，然后用adb抓原生打印，或者你直接用AndroidStudio打开项目运行也可以看到log。

**Comment by JoshLipan** [comment]
没看到极光相关日志打印
