### ISSUE TITLE
jpushplugin.m 中的部分方法 失效

### ISSUE THREAD

**Issue by wierli** [jpush/jpush-phonegap-plugin#36]
- (CDVPlugin*)initWithWebView:(UIWebView*)theWebView{
    if (self=[super initWithWebView:theWebView]) {
        
        NSNotificationCenter *defaultCenter = [NSNotificationCenter defaultCenter];
        [defaultCenter addObserver:self
                          selector:@selector(networkDidReceiveMessage:)
                              name:kJPFNetworkDidReceiveMessageNotification
                            object:nil];
        
        [defaultCenter addObserver:self
                          selector:@selector(networkDidReceiveNotification:)
                              name:kJPushPluginReceiveNotification
                            object:nil];

    }
    return self;
}

以上两个监听的 函数 前端无法收到回调

-(void)networkDidReceiveNotification:(id)notification{
    
    NSError  *error;
    NSDictionary *userInfo = [notification object];

    NSData   *jsonData   = [NSJSONSerialization dataWithJSONObject:userInfo options:0 error:&error];
    NSString *jsonString = [[NSString alloc]initWithData:jsonData encoding:NSUTF8StringEncoding];
    
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.commandDelegate evalJs:[NSString stringWithFormat:@"cordova.fireDocumentEvent('jpush.receiveNotification',%@)",jsonString]];
    });

}

前端

 var onOpenNotification = function(event){
             	try{
             		var alert   = event.alert;
					var extras  = event.extras;
		            alert(alert);
		            //console.log(extras);
             	}
             	catch(exeption){
             		console.log(exception)
             	}
            }

document.addEventListener("jpush.receiveNotificatio", onOpenNotification, false);

获取不到信息 = - = 怎么办

**Comment by zhangqinghe** [comment]
@wierli 
1.请确认 AppDelegate.m函数中，是否添加了这个函数
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    // Required
    [APService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPushPluginReceiveNotification
                                                        object:userInfo];

}
2.请在
(CDVPlugin)initWithWebView:(UIWebView)theWebView
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo 
这个2个函数下断点，确认哪个函数先被执行，如果是initWithWebView先执行，则正常，否则就是消息下来但是插件没构造好，所以出现这个问题，后续我想办法解决这个问题，方便大家使用

**Comment by wierli** [comment]
我重新build了一下  现在好了


发自我的 iPhone

**Comment by HenryZl** [comment]
您好，
在使用插件过程中发现，和前提条件上述场景相同的情况下，
应用在前台时接收到消息，先执行了：
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler；方法
但是，
- (CDVPlugin*)initWithWebView:(UIWebView*)theWebView；
并没有被执行到，所以 ：
        [defaultCenter addObserver:self
                     selector:@selector(networkDidReceiveNotification:)
                     name:kJPushPluginReceiveNotification
                            object:nil];
没有执行，前端无法收到回调。
但应用在后台时，还是可以正确收到通知提示。
是否为插件配置不正确或者其他的问题，希望能够得到指点。
