### ISSUE TITLE
phonegap+jpush如何实现phonegap build云服务打包

### ISSUE THREAD

**Issue by renqingchao** [jpush/jpush-phonegap-plugin#360]
phonegap build云服务支持纯前段，在线打包。如何集成jpush插件，也支持通过phonegap build云服务生成app？

**Comment by JoshLipan** [comment]
[不支持云打包](https://github.com/jpush/jpush-phonegap-plugin#%E5%85%B3%E4%BA%8E-phonegap-build-%E4%BA%91%E6%9C%8D%E5%8A%A1)
