### ISSUE TITLE
iOS环境下，xcode直接调试系统推送成功，Ad Hoc、Development分发，系统推送不成功

### ISSUE THREAD

**Issue by jipf2016** [jpush/jpush-phonegap-plugin#362]
* 插件版本:   3.4.2
* 平台（Android / iOS）: iOS
* Cordova version (```cordova -v```):  8.0.0
* Cordova platform version (```cordova platform ls```):"cordova-ios": "4.5.4",
* Ionic Version (if using Ionic) 3.20.0

用xcode打包真机调试时可以获取到registrationID，能够接收到网页控制台发送的推送通知，不改变配置，使用 product=》archives=》Ad Hoc、Development=》得到ipa，安装到手机，获取不到registrationID（重复、延迟获取registrationID，也获取不到），接收不到通知。

**Comment by huangminlinux** [comment]
看看是不是这个问题。
https://github.com/jpush/jpush-phonegap-plugin/issues/350#issuecomment-391403275

**Comment by jipf2016** [comment]
谢谢

**Comment by jipf2016** [comment]
根据你的指点已解决
