### ISSUE TITLE
插件安装完，执行JPush.init显示the JPush plugin is not installed

### ISSUE THREAD

**Issue by shad0whz** [jpush/jpush-phonegap-plugin#363]
## 你的运行环境

* 插件版本:
cordova-plugin-jcore@1.2.1
jpush-phonegap-plugin@3.4.1
* 平台（Android / iOS）:
Android 
* Cordova version (```cordova -v```):
 8.0.0
* Cordova platform version (```cordova platform ls```):
android 7.0.0
* Ionic Version (if using Ionic)
3.20.0

## 期望效果

this.mJPush.init().then(res => { alert(res) });执行成功

## 实际效果

![qq 20180725174228](https://user-images.githubusercontent.com/12270485/43193297-3ca6ba38-9032-11e8-9811-bced68c848fa.jpg)

## 重现步骤

  1. cordova plugin add jpush-phonegap-plugin --variable APP_KEY=*****
  2. npm install --save @jiguang-ionic/jpush
  3. app.module.ts ，this.mJPush.init().then(res => { alert(res) })
  4. ionic cordova run android -l -c
## 背景

你尝试做过些什么？
卸载插件，重装
ionic cordova platform remove android
ionic cordova platform add android

## Debug logs

包括 Android 或 iOS 的日志：
![screenshot_2018-07-25-17-39-46 1](https://user-images.githubusercontent.com/12270485/43193427-8c5242dc-9032-11e8-8ac2-f1f313d63b8e.png)

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by JoshLipan** [comment]
参考下：https://community.jiguang.cn/t/ionic-jpush-phonegap-plugin/27038/15

**Comment by shad0whz** [comment]
@JoshLipan
我试过了降级和重装多个方式之后，
在页面中引入`declare let window;` 之后用`window.JPush`可以运行，

但是通过`constructor()`的方式就不行（试验了`android 7.0.0`,`6.0.0`,`5.1.1`版本）。
