### ISSUE TITLE
增加ionic4支持

### ISSUE THREAD

**Issue by tqjxlm** [jpush/jpush-phonegap-plugin#365]
## 你的运行环境

* 插件版本: 
"@jiguang-ionic/jpush": "^1.0.2"，
"jpush-phonegap-plugin": "3.3.3",
"cordova-plugin-jcore": "1.1.12",

* 平台（Android / iOS）:
Android + iOS

* Cordova version (```cordova -v```):
7.1.0

* Cordova platform version (```cordova platform ls```):
Android: 6.4.0
iOS: 4.5.5

* Ionic Version (if using Ionic)
4.0.0-beta.0

## 期望效果

项目更新到ionic4

## 实际效果

在引入jiguang jpush模块时，提示错误“Object(...) is not a function”，代码错误位置为index.js的93行"Cordova()"
同时，在编译的时候提示未安装依赖@ionic-native/core@4和rxjs@5，然而在ionic4中这两个组件的版本已经更新到@ionic-native/core@5.0.0-beta.14和rxjs@6。

## 重现步骤

1. 使用ionic start blank生成纯净项目
2. npm安装jpush phonegap plugin, jcore, jiguang-ionic
3. 在app.module.ts引入provider: JPush
4. ionic serve运行后直接报错

## Debug logs

控制台运行时错误：

index.js:93 Uncaught TypeError: Object(...) is not a function
    at index.js:93
    at Object../node_modules/@jiguang-ionic/jpush/index.js (index.js:350)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:22)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:15)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)

**Comment by huangminlinux** [comment]
使用 ionic@4.0.6 测试没有问题

**Comment by huangminlinux** [comment]
@ionic/angular@4.0.0-beta 项目确实有问题。
ionic-native v5 beta 版本的构建有点问题，等正式版出来再看看。

**Comment by jegged** [comment]
ionic 4正式版已发布，ionic-native5也发布了 这个问题提上日程了没啊

**Comment by dusdong** [comment]
同求对 ionic 4正式版的支持

**Comment by liuyao552** [comment]
大多数ionic项目都会升级到v4，希望尽快支持

**Comment by huangminlinux** [comment]
近期会支持 ionic4版本

**Comment by jakechen0816** [comment]
谢谢作者，希望可以尽快更新。

**Comment by huangminlinux** [comment]
可以升级到 `@jiguang-ionic/jpush@2.0.0` 版本。

**Comment by jakechen0816** [comment]
升级到2.0.0以后，将jPush放到provider里面报了一个错误。
ERROR in src/app/app.module.ts(21,23): error TS2322: Type 'JPushOriginal' is not assignable to type 'Provider'.
[ng]   Type 'JPushOriginal' is not assignable to type 'ClassProvider'.
[ng]     Property 'provide' is missing in type 'JPushOriginal'.
[ng] src/app/services/jpush.service.ts(18,56): error TS2304: Cannot find name 'JPush'.

**Comment by huangminlinux** [comment]
ionic4 以后的插件要引入的是 ngx 这个目录文件了，比如 jpush 的 import 需要这么引入
```
import { JPush } from '@jiguang-ionic/jpush/ngx';
```

**Comment by xuxingshan** [comment]
有没有报这个错误的，插件按照了，不能识别Device，无法识别平台，写死devicePlatform="iOS",可以收到推送
ERROR in src/app/tab1/tab1.page.ts(39,13): error TS2304: Cannot find name 'Device'.

**Comment by bing2011** [comment]
有解决方案了吗

**Comment by bing2011** [comment]
> ionic4 以后的插件要引入的是 ngx 这个目录文件了，比如 jpush 的 import 需要这么引入
> 
> ```
> import { JPush } from '@jiguang-ionic/jpush/ngx';
> ```

是引入的这个   ionic4下  init时依旧是报错，Object(...) is not a function

**Comment by pitt59159** [comment]
插件装下最新版本，我这两天也用了这个插件，可以正常使用的。我的版本如下
ionic 4.12.0 
cordova-android 7.0.0 
cordova-plugin-jcore 1.2.7
jpush-phonegap-plugin 3.6.3
