### ISSUE TITLE
ios设置别名失败

### ISSUE THREAD

**Issue by renqingchao** [jpush/jpush-phonegap-plugin#368]
window.JPush.setAlias({ sequence: 1, alias: 'your_alias' },
  (result) => {
    var sequence = result.sequence
    var alias = result.alias
  }, (error) => {
    var sequence = error.sequence
    var errorCode = error.code
  })

ios调用此方法，不走回调函数，别名一直设置不成功

**Comment by huangminlinux** [comment]
是否在真机上测试？
