### ISSUE TITLE
url下载插件 报错警告

### ISSUE THREAD

**Issue by OmgKevin** [jpush/jpush-phonegap-plugin#369]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## macOS环境

* 插件版本:
* 平台（iOS）:iOS
* Cordova version (```cordova -v```):8.0.0版本
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)

## 期望效果

告诉我们你希望达到什么效果。
我想通过 cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY=your_jpush_appkey 通过url方式添加插件
## 实际效果
终端报错 
(node:84533) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/jpush/jpush-phonegap-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/jpush/jpush-phonegap-plugin.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/jpush/jpush-phonegap-plugin.git/': Empty reply from server
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XX/.npm/_logs/2018-08-23T06_25_07_764Z-debug.log
    at /Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/XX/.nvm/versions/node/v8.11.3/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:84533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84533) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
告诉我们实际是什么效果。

## 重现步骤

  1. ... 创建cordova本地项目 
  2. ... cd至cordova所在项目目录
  3. ... sudo cordova platforms add ios
  4. ... 复制cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY=your_jpush_appkey粘贴，敲回车

## 背景

你尝试做过些什么？
猜想会是权限方面的事情
## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by OmgKevin** [comment]
你好，请问有人帮忙来解决这个问题嘛

**Comment by huangminlinux** [comment]
可以下载到本地通过本地路径来安装。

**Comment by OmgKevin** [comment]
嗯嗯 ，第三种是可以成功的。但是目前我是想通过url的方式下载，请问我应该怎么做

**Comment by huangminlinux** [comment]
安装命令加上 `--nofetch` 试试

**Comment by OmgKevin** [comment]
--nofetch cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY= keyocm ，这样子么，提示：-bash: --nofetch: command not found

**Comment by JoshLipan** [comment]
--nofetch 放后面：cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY= keyocm --nofetch
