### ISSUE TITLE
可以收到推送通知，但通知/消息的事件无响应，求助

### ISSUE THREAD

**Issue by snakefor100** [jpush/jpush-phonegap-plugin#37]
Hi:
 您好，我有个问题想请教下，我用这个插件集成在IOS平台上(cordova+sencha touch)，但和其他有些人遇到的问题可能类似，我能收到推送通知，但是无法获取数据，receiveNotification和receiveMessage事件不响应。我不知道是否是自己理解有问题，我的代码如下(index.html中)：

   window.plugins.jPushPlugin.init();    //起作用，能收到推送通知
   window.plugins.jPushPlugin.setTagsWithAlias(['AA'],'BB'); //起作用，能按照别名，标签收到推送通知
   var onOpenNotification = function(event){  //不起作用，ipad收到通知后，方法内代码不执行
       //window.alert("AA");   //没有弹出AA
       var indexPanel = Ext.ComponentQuery.query('#IndexAbstractPanel')[0];
       indexPanel.setActiveItem(5);
    };
  var onReceiveMessage = function(event){   //不起作用，在极光官网发送消息后，提示发送成功，但                     这个方法内部无响应
       //window.alert("BB");     //没有弹出框
        var indexPanel = Ext.ComponentQuery.query('#IndexAbstractPanel')[0];
	indexPanel.setActiveItem(5);
    };
 document.addEventListener("jpush.openNotification", onOpenNotification, false);
 document.addEventListener("jpush.receiveMessage", onReceiveMessage, false);

（我看到之前也有人提问过类似问题，但我的项目没有用到angular，我对object-c语言也不熟悉，看不大懂之前有人说过的那个方法，不明白为什么要就是将原来的window.plugins.jPushPlugin.receiveMessageIniOSCallback 改成 window.jPushPluginreceiveMessageIniOSCallback，我尝试着改过，没有作用）。

集成的时候我是按照文档步骤操作的，我理解的是不是当收到通知/消息的时候，系统会响应jpush.openNotification/jpush.receiveMessag事件？从而执行onOpenNotification/onReceiveMessage方法？但我不大清楚为什么方法没有响应。。是否还需要加object-c的一些代码？

希望大神有时间能解答下，万分感谢。
（Cordova 4.3.0 ,IOS7环境)

**Comment by W65138497** [comment]
我也遇到同样问题，没有找到解决方案

**Comment by zhangqinghe** [comment]
@snakefor100 
＋ 首先请确认iOS 是否集成成功
＋ 打开调试模式 window.plugins.jPushPlugin.setDebugModeFromIos ()

**Comment by snakefor100** [comment]
@zhangqinghe 
嗯。应该是我的问题，后来这回我又重新新建了个工程，再次尝试集成了下，然后将init方法写在了deviceready初始化方法里面(之前写在了jquery初始化/onload/index.html最上面都不行,不大清楚为什么。也可能是之前集成时候有问题，当时能收到推送我就觉得集成成功了，然后没考虑这方面)，最后确实事件成功响应了
