### ISSUE TITLE
获取registrationId为空

### ISSUE THREAD

**Issue by ericboy** [jpush/jpush-phonegap-plugin#370]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android）:
* Cordova version (```cordova -v```):
8.0.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic)
no

## 期望效果
正常获取registrationId

告诉我们你希望达到什么效果。

## 实际效果
获取到是“”
告诉我们实际是什么效果。

## 重现步骤

  1. 新建项目
cordova create c910 com.eric.hisea Hisea
  2.绑定android环境
 cordova platform add android --save
  3.安装jpush插件
 cordova plugin add https://github.com/jpush/jpush-phonegap-plugin.git --variable APP_KEY=8348da7ddbbf5f59f20033ce
  4. web环境搭建
1）将example放到nginx中
2）将c910\platforms\android\platform_www 中的cordova.js、cordova_plugins.js、plugins 复制到example根目录
3）目录解构
![image](https://user-images.githubusercontent.com/25583681/45294460-fe55ed00-b52d-11e8-946a-a40c48a3ac9f.png)

## 背景
win10 企业版
你尝试做过些什么？
weinre 监控

没有网络请求
控制台打印：
JPushPlugin:registrationID is

**Comment by JoshLipan** [comment]
参考 #338

**Comment by ericboy** [comment]
"dependencies": {
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-jcore": "^1.1.12",
    "cordova-plugin-whitelist": "^1.3.3",
    "jpush-phonegap-plugin": "^3.3.2",
    "cordova-android": "~6.4.0"
  }
按照建议的版本进行重新构建，获取

![image](https://user-images.githubusercontent.com/25583681/45416846-59651c80-b6b3-11e8-86cf-cb7c793c08e5.png)
还有别的排查方式或建议吗？

**Comment by ericboy** [comment]
@JoshLipan 大神，会哪里出了问题，或别的排查方式

**Comment by JoshLipan** [comment]
升级至[v3.5.0](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.5.0)试下
