### ISSUE TITLE
集成cordova-plugin-crosswalk-webview后安卓出现corsswalk mismatch of cpu architecture

### ISSUE THREAD

**Issue by gdtdpt** [jpush/jpush-phonegap-plugin#371]
## 我的运行环境

* 插件版本: jpush-phonegap-plugin@3.4.3
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): Cordova 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Crosswalk version: [https://github.com/fribace/cordova-plugin-crosswalk-webview.git](https://github.com/fribace/cordova-plugin-crosswalk-webview.git)

## 问题描述

项目是原生Cordova项目，非Ionic。项目中原本集成了Crosswalk，运行无异常，最近集成了极光推送，在一些安卓手机上运行无异常，在小米手机上打开App直接会显示`Mismatch of CPU Architecture`提示框，App无法正常运行。

## 进行的尝试

- 只删除cordova-plugin-crosswalk-webview后编译安装，App能正常在小米手机打开。
- 只删除jpush-phonegap-plugin后编译安装，App能正常在小米手机打开。
- 两个插件同时存在，App不能在小米手机正常打开，出现以下提示。

![Alert image](http://wx3.sinaimg.cn/large/006VI9Tcly1fw4arpdxpmj30c806o0u2.jpg)

#### 补充
因为此项目在整合jpush-phonegap-plugin之前一直使用Crosswalk，而且整合jpush-phonegap-plugin后出问题的手机再安装未整合jpush-phonegap-plugin的应用安装包不会出现以上问题，所以我猜想会不会是两个插件之间有什么冲突。

**Comment by JoshLipan** [comment]
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/203

**Comment by gdtdpt** [comment]
@JoshLipan 你好，感谢你的回复。我按照你发的链接里的方法，打开Build Variants界面，但是我的选择框里没有`armv7Debug`这个选项，只有`debug`和`release`，我是不是还有什么遗漏？

![Build Variants](http://wx4.sinaimg.cn/large/006VI9Tcly1fw56ow3vtfj30gw0ky3zq.jpg)

**Comment by JoshLipan** [comment]
建议去cordova-plugin-crosswalk-webview那边提issue问下

**Comment by xiaoxiaofan123** [comment]
请问你解决这个问题了吗

**Comment by gdtdpt** [comment]
@xiaoxiaofan123 最后没有解决，不用crosswalk后用了一段时间修复兼容问题。

**Comment by xiaoxiaofan123** [comment]
> @xiaoxiaofan123 最后没有解决，不用crosswalk后用了一段时间修复兼容问题。

是这两个插件有冲突吗 我也遇到了同样的问题 用了#203回答里的方法输出armv7Debug依然没有解决

**Comment by gdtdpt** [comment]
> 是这两个插件有冲突吗 我也遇到了同样的问题 用了#203回答里的方法输出armv7Debug依然没有解决

cordova-plugin-crosswalk-webview这个插件官方早已经不再维护，所以很容易出现各种问题，建议你们有能力就直接换个框架，不要再用cordova了

**Comment by WangChenXiang** [comment]
注释ndk好像就可以了，这两个好像是冲突的
