### ISSUE TITLE
拥有同样tags的所有设备,只有一台能收到通知

### ISSUE THREAD

**Issue by Story5** [jpush/jpush-phonegap-plugin#372]
## 运行环境

* 插件版本: 3.4.3
* 平台: ios和android
* Cordova version : 8.0.0
* Cordova platform version : ios4.5.5和android7.0.0
* Ionic Version  : 4.2.1

## 期望效果

拥有同样tags的所有设备,都能收到通知

## 实际效果

拥有同样tags的所有设备,只有一台能收到通知

## 重现步骤

  1. 多台设备设置同一个tags值
  2. 使用极光后台对改tags所有设备进行推送
  3. 有且仅有一台设备能够收到通知

## 背景

使用极光后台tags测试推送

**Comment by JoshLipan** [comment]
看下你后台怎么配置推送的

**Comment by Story5** [comment]
我使用极光后台推送测试的

**Comment by JoshLipan** [comment]
知道，推送前会提示你预估设备，还有你的推送设置
![image](https://user-images.githubusercontent.com/16323137/47128524-21f61b00-d2c4-11e8-919f-2f8175f4aa5b.png)

**Comment by Story5** [comment]
预估人数显示就是1条

**Comment by JoshLipan** [comment]
确定其他设备也都绑定的同一个tag吗，可以[getalltags](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#getalltags)获取绑定的tag列表看看
