### ISSUE TITLE
Android 端getUserNotificationSettings 返回值始终是1

### ISSUE THREAD

**Issue by WdBly** [jpush/jpush-phonegap-plugin#378]
## 你的运行环境
android 7.1 和 android8.0
* 插件版本:
* 平台（Android）: Android
* Cordova version ： 7.1.0
* Cordova platform version (```cordova platform ls```):

  android ~6.3.0
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

* Ionic Version (if using Ionic)： 3.19.1

## 期望效果
在使用了 getUserNotificationSettings 方法获取用户是否打开应用通知时，在用户打开应用通知时返回1，在用户关闭通知时返回0.

## 实际效果

实际测试中发现，在已测试的两台android设备中,不管是否打开应用的通知，都返回的1。

经过测试发现在ios中此api返回值虽然是一个对象，但其中的值和当前设备的状态是匹配的。

## 重现步骤

直接调用api即可重现：
//android
window.plugins.jPushPlugin.getUserNotificationSettings(function(value) {
        console.log(value) // 1
 });

## 背景
我尝试在android设备中将应用通知关闭，在状态栏关闭，横幅关闭，锁屏关闭等操作组合测试API返回结果是 1，
我尝试将设备设置为所有通知都不可用，返回结果是1

## Debug logs

包括 Android 或 iOS 的日志：

暂无报错等日志

**Comment by JoshLipan** [comment]
升级至[v3.5.0](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.5.0)
