### ISSUE TITLE
可以给插件安装加上CHANNEL参数吗？

### ISSUE THREAD

**Issue by hywyx** [jpush/jpush-phonegap-plugin#382]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):8.1.2
* Cordova platform version (```cordova platform ls```):android 7.1.2
* Ionic Version (if using Ionic)

## 期望效果

可以给插件安装加上CHANNEL参数吗？

## 实际效果

目前的plugin.xml里JPUSH_CHANNEL是固定的值“developer-default”

## 重现步骤

无

## 背景

虽然可以手动修改，但部署和协同时总是个小麻烦，不知官方能否加入安装参数自动部署

## Debug logs

无

**Comment by JoshLipan** [comment]
暂时不提供，如果和极光其他插件公用的话会发生冲突，建议先手动修改
