### ISSUE TITLE
ionic3 集成极光推送之后 能获取到数据，但是不能跳转内页

### ISSUE THREAD

**Issue by YLQZ** [jpush/jpush-phonegap-plugin#386]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:  3.5.1
* 平台（Android / iOS）: Android 
* Cordova version (```cordova -v```):  8.1.2
* Cordova platform version (```cordova platform ls```):  android 7.1.2，browser ~5.0.1， ios ~4.5.4， osx ~4.0.1，windows ~6.0.0
* Ionic Version (if using Ionic) CLI 4.5.0

## 期望效果
点击推送的消息之后，跳转到消息指定的页面

## 实际效果
点击推送消息之后，只是打开了应用

## 重现步骤

  1. ionic集成极光推送
  2. 监听 jpush.openNotification 事件
  3.
 document.addEventListener(
        "jpush.openNotification",
        (event:any)=>{
          var content
          let data =''
          var page = ''
          var sessionId = ''
          if (this.devicePlatform == "Android") {
            content = event.alert
            data = JSON.parse(event.extras['androidNotification extras key'])
            page = JSON.parse(event.extras['androidNotification extras key']).page
            sessionId = JSON.parse(event.extras['androidNotification extras key']).seeeionId
          } else {
            // iOS
            if (event.aps == undefined) {
              // 本地通知
              content = event.content
            } else {
              // APNS
              content = event.aps.alert
            }
          }
          alert("open notification: " + JSON.stringify(event))
          alert(page)
          alert(sessionId)
          alert(data)
          // this.goToChatPage(page,sessionId)
          this.navCtrl.push(page, {
            sessionId: sessionId
          })
        },
        false
      )

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by JoshLipan** [comment]
网络故障，服务目前正在修复中。
收到事件后的逻辑要自己去处理，具体无法跳转原因需要你自己去定位

**Comment by YLQZ** [comment]
@JoshLipan  那我这种小白是不是不适合做开发了0.0

**Comment by Toooooooooo** [comment]
@YLQZ 打个debug-apk包查在as 查看一下 报错信息，检查一下 页面模板的引入和声明有没有问题。
