### ISSUE TITLE
为什么 iOS 的 jpush.receiveNotification 事件无法获取到其他的参数？

### ISSUE THREAD

**Issue by zwlcoding** [jpush/jpush-phonegap-plugin#39]
为什么 iOS 的 jpush.receiveNotification 事件无法获取到其他的参数？

只能获取到三个参数，新增加的键和值无法获取到？
{
'badge':'1',
'sound':'default',
'alert':'ios push'
}

我尝试使用jpush.receiveMessage 但是并没有任何反应。

**Comment by zhangqinghe** [comment]
@zwlcoding 这个接口是对系统的封装，可以进入UIAppdelegate.m里面 application:didReceiveRemoteNotification: 这个函数里面 查看，从APNS发送的具体内容
