### ISSUE TITLE
android版本的自定义消息接收不到extras

### ISSUE THREAD

**Issue by fenglu09** [jpush/jpush-phonegap-plugin#40]
在文档 “通用API说明” 的 “获取自定义消息推送内容”中介绍，android端返回的数据如下：

{"message":"今天去哪儿",
"extras"{
        "cn.jpush.android.MSG_ID":"154378013",
        "cn.jpush.android.CONTENT_TYPE":"",
        "cn.jpush.android.EXTRA":{"key":"不添没有"}
        }
}
“点击通知后传递的json object 保存在window.plugins.jPushPlugin.receiveNotification，直接访问即可”

但是在测试的过程中发现，接收到的消息是保存在window.plugins.jPushPlugin.openNotification中，
而且，在没有添加附加key/value 的时候，接收到的消息只有{"message":"今天去哪儿"}

**Comment by zhangqinghe** [comment]
能否打开调试模式，打印出更多的log后，将log贴出来看看

**Comment by sy890622** [comment]
我也是同样的我的问题，以自定义消息模式发送的，回调event也是"jpush.receiveMessage"，但是消息确是在window.plugins.jPushPlugin.openNotification.message中

**Comment by sy890622** [comment]
你说的是adb logcat吗？什么log？

**Comment by zhangqinghe** [comment]
嗯 是的就是在log cat中
