### ISSUE TITLE
jmessage 与jpush 再次冲突

### ISSUE THREAD

**Issue by lingdu0001** [jpush/jpush-phonegap-plugin#406]
WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。

你的运行环境
插件版本:
平台（Android / iOS）: IOS
Cordova version (cordova -v) : 8.1.2
Cordova platform version (cordova platform ls): 5.0.1
Ionic Version (if using Ionic) 3.20.1
期望效果
jmessage 与jpush 可以并存

实际效果
冲突了 构建ios的时候报错
❌ duplicate symbol __launchOptions in

AppDelegate+JMessage.o
AppDelegate+JPush.o

❌ ld: 1 duplicate symbol for architecture arm64

❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

重现步骤
安装jpush插件
安装jmessage插件
构建ios
报错。。
升级到最新版本 卸载安装插件,也是老样子

**Comment by pierresh** [comment]
Hello,

I have the same problem, could you please share how you solved that problem? Thanks!

**Comment by pierresh** [comment]
Here is the solution:

in  `/plugins/jpush-phonegap-plugin/src/ios/Plugins`

Open **AppDelegate+JPush.m** and rename the 3 occurences **_launchOptions** as **_launchOptions2**

Then:
```
cordova platform remove ios
cordova platform add ios@5.1.1
```

**Comment by lingdu0001** [comment]
> Here is the solution:
> 
> in `/plugins/jpush-phonegap-plugin/src/ios/Plugins`
> 
> Open **AppDelegate+JPush.m** and rename the 3 occurences **_launchOptions** as **_launchOptions2**
> 
> Then:
> 
> ```
> cordova platform remove ios
> cordova platform add ios@5.1.1
> ```
Solution for android:

In /plugins/jmessage-phonegap-plugin/plugin.xml
Comment lines which contains PushService PushReceiver  AlarmReceiver and DataProvider.
