### ISSUE TITLE
为什么android版本没有receiveNotification这事件呢？

### ISSUE THREAD

**Issue by fenglu09** [jpush/jpush-phonegap-plugin#41]
在iOS版本里面有jpush.receiveNotification事件，在接收到推送消息的时候做一些处理，但是android版本的没有jpush.receiveNotification，无法在接收消息的时候做处理，只有jpush.openNotification时间。能否为android版本的也添加jpush.receiveNotification事件呢？？

**Comment by zhangqinghe** [comment]
@fenglu09 hello，下个版本会加入的，近期会更新，感谢关注。

**Comment by qdsang** [comment]
赞！

**Comment by fenglu09** [comment]
@zhangqinghe  好的，谢谢，希望能够完善一下帮助文档，感觉文档里面有一些对不上的地方

**Comment by zhangqinghe** [comment]
@fenglu09 能不能具体一点，望不吝指出

**Comment by fenglu09** [comment]
1、通用api event - jpush.openNotification
例子里面 ：android端通过 window.plugins.jPushPlugin.openNotification.alert; 获取消息，但是在下面有个说明“点击通知后传递的json object 保存在window.plugins.jPushPlugin.receiveNotification，直接访问即可”，两者矛盾。后来看源码，发现保存在window.plugins.jPushPlugin.receiveNotification。
2、通用api  event - jpush.openNotification 
示例里面：android端通过window.plugins.jPushPlugin.receiveMessage.message获取消息，但是下面有个说明 “点击通知后传递的json object 保存在window.plugins.jPushPlugin.receiveNotification，直接访问即可，字段示例，根据实际推送情况”，两者矛盾。最后发现是保存在window.plugins.jPushPlugin.openNotification 。
    总的来说，感觉通知和自定义消息返回的json object 保存的变量明很难以理解，感觉是你们命名的时候弄错了。这只是我自己的理解，有什么不对的希望你们不要介意。

**Comment by zhangqinghe** [comment]
这个是文档写错了，很快会修正，抱歉！
