### ISSUE TITLE
厂商通道版cordova集成

### ISSUE THREAD

**Issue by lingdu0001** [jpush/jpush-phonegap-plugin#417]
请问能否提供厂商通道版本的cordova插件啊，付费以后客服就给我一个demo让我用，但是照着那个弄到现在的框架里面太费劲了。
另外现在这个插件还有人维护么？感觉作者活跃度不高了。。。是否都转去弄flutter了啊？

**Comment by C-racker** [comment]
参考 https://github.com/C-racker/jpush-phonegap-plugin

**Comment by lingdu0001** [comment]
@C-racker 
感谢分享！！
