### ISSUE TITLE
集成极光推送插件后提交谷歌Play被拒绝

### ISSUE THREAD

**Issue by Symous** [jpush/jpush-phonegap-plugin#423]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
3.7.3
* 平台（Android / iOS）: 
* Cordova version (```cordova -v```): 
8.0.0
* Cordova platform version (```cordova platform ls```):
android 7.0.0
ios 4.5.4
* Ionic Version (if using Ionic)

## 实际效果
谷歌发送的审核被拒绝邮件：
APK REQUIRES PROMINENT DISCLOSURE​
We’ve identified that your app is using Jiguang SDK or library, which facilitates the transmission of collection of Installed Packages information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information 

APK REQUIRES PROMINENT DISCLOSURE​
Your app is uploading users' Jiguang SDK  information to nstalled Packages without a prominent disclosure. Prior to the collection and transmission, it must prominently highlight how the user data will be used, describe the type of data being collected and have the user provide affirmative consent for such use.

在官方网站中找到了一个[解决连接](https://community.jiguang.cn/article/372890)，需要手动集成，但是不确定针对此cordova插件应该如何进行操作？

**Comment by pierresh** [comment]
This is a big problem, and I really hope there is a clean solution for this (and not a workaround to change files manually) ....

**Comment by Symous** [comment]
我目前的解决方案是下载官方提供的支持google play的包，然后在项目中手动替换相关的jar包和so库，已经提交谷歌成功了。
