### ISSUE TITLE
Ionic + Capacitor ，构建IOS时报错“library not found for -ljcore-ios-2.1.4”

### ISSUE THREAD

**Issue by AlwaysLoveme** [jpush/jpush-phonegap-plugin#424]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: IOS
* Capacitor version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic) Ionic5

## 期望效果
构建IOS成功，不报错
告诉我们你希望达到什么效果。

## 实际效果
IOS打包出错，
告诉我们实际是什么效果。
IOS打包出错，无法构建
## 重现步骤
1.使用ionic-cli构建ionic项目，
2.添加此插件，
3.添加IOS平台，
4.Xcode打包出错

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：
ld: library not found for -ljcore-ios-2.1.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by ParryQiu** [comment]
修改对应的 a 文件名称为 libjpush-ios-2.1.4.a 即可。

**Comment by AlwaysLoveme** [comment]
> 修改对应的 a 文件名称为 libjpush-ios-2.1.4.a 即可
这个只能打包不报错，但是运行会闪退，原因是capacitor用的是swift，而此插件是oc,你有啥解决方法没？

**Comment by ParryQiu** [comment]
> > 修改对应的 a 文件名称为 libjpush-ios-2.1.4.a 即可
> > 这个只能打包不报错，但是运行会闪退，原因是capacitor用的是swift，而此插件是oc,你有啥解决方法没？

在 Other Linker Flags 里添加 -ObjC 就可以了，我这可以运行，但是好像注册不到服务器上。
目前遇到的问题
https://github.com/jpush/jpush-phonegap-plugin/issues/430

**Comment by ParryQiu** [comment]
后来还是切换到 Cordova 框架解决了。

**Comment by JoshLipan** [comment]
暂不支持Capacitor
