### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by MrLrx** [jpush/jpush-phonegap-plugin#425]
@  Apple will stop accepting submissions of apps that use UIWebView APIs

**Comment by leeewh** [comment]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
同样收到了苹果的警告

**Comment by JoshLipan** [comment]
[v3.7.6](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.7.6)已修复
