### ISSUE TITLE
构建Android失败

### ISSUE THREAD

**Issue by cnkker** [jpush/jpush-phonegap-plugin#426]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (```cordova platform ls```): Installed platforms: android 8.1.0
* Ionic Version (if using Ionic) 

   _             _
  (_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___| CLI 6.5.0

## 期望效果

构建成功

## 实际效果

构建Android 失败

## 重现步骤

  1. ionic cap sync
  2.  ionic cap open android
  打开Android后，失败

## Debug logs

9:59	Gradle sync failed: Cause: org.xml.sax.SAXParseException; systemId: file:/D:/xxx/android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml; lineNumber: 45; columnNumber: 26; Attribute "name" bound to namespace "http://schemas.android.com/apk/res/android" was already specified for element "application".
		Attribute "name" bound to namespace "http://schemas.android.com/apk/res/android" was already specified for element "application".
		Consult IDE log for more details (Help | Show Log) (24 s 939 ms)

**Comment by soweibo** [comment]
same here

**Comment by cnkker** [comment]
已经解决了！
