### ISSUE TITLE
安装插件的时候报Cannot find plugin.xml for plugin "jpush-phonegap-plugin". Please try adding it again.

### ISSUE THREAD

**Issue by Kyeoni** [jpush/jpush-phonegap-plugin#427]
使用cordova plugin add jpush-phonegap-plugin --variable APP_KEY=xxxx安装插件，报Cannot find plugin.xml for plugin "jpush-phonegap-plugin". Please try adding it again.

**Comment by cnkker** [comment]
你这是没有安装成功

**Comment by Kyeoni** [comment]
> 你这是没有安装成功

是的。当时就是想安装这个插件，但是安装时报找不到xml。后来安装上了，没有报这个。
