### ISSUE TITLE
ITMS-90809 App Store拒绝使用UIWebview 

### ISSUE THREAD

**Issue by ihaoqichan** [jpush/jpush-phonegap-plugin#428]
## 运行环境

* 插件版本:
* 平台（Android / iOS）: iOS
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```):ios 4.5.5
* Ionic Version (if using Ionic): ionic3

## 期望效果

苹果App Store上架。

## 实际效果

由于极光推送插件使用了UIWebview APIs，而App Store不再允许使用UIWebview APIs的，因此被拒。

## 重现步骤

  只要用了该插件都会被拒。

## 背景

尝试过自己将UIWebview的替换WKWebview的，奈何不会iOS编程，希望极光的大神们更新一下该插件，万分感激！

**Comment by JoshLipan** [comment]
[v3.7.6](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.7.6)已修复
