### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability

### ISSUE THREAD

**Issue by Benamin** [jpush/jpush-phonegap-plugin#429]
## 你的运行环境

* 插件版本: 3.7.4
* 平台（Android / iOS）: ios
* Cordova version (```cordova -v```):  8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```):
   ios 5.1.1
* Ionic Version (if using Ionic)
ionic 3
## 期望效果

正常提交APP store,不会提示 [ITMS-90809: Deprecated API Usage],错误

## 实际效果

提交app store失败,提示 
```
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability
```

## 重现步骤
```
1.cordova plugin add jpush-phonegap-plugin --variable APP_KEY=your_jpush_appkey --variable CHANNEL=your_channel
2.打包提交至app store
```

## 背景

cordova-ios 更新至5.1.1
在config.xml中添加

```
<preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

## Debug logs

没有任何报错日志,通过以下命令查包含UIWebView得到文件
```
grep -r UIWebView .
```
查询得到以下结果
```
/Plugins/jpush-phonegap-plugin/JPushPlugin.m:- (CDVPlugin*)initWithWebView:(UIWebView*)theWebView{
```
以上方法应用了UIWebView

希望能够解决下,毕竟4月份之后app store都会拒绝应用了UIWebView的新应用,老应用在12月份之后 也会拒绝提交

**Comment by engine9012** [comment]
同样的问题，希望官方尽快更新下插件

**Comment by JoshLipan** [comment]
[v3.7.6](https://github.com/jpush/jpush-phonegap-plugin/releases/tag/v3.7.6)已修复
