### ISSUE TITLE
当退出应用时，点击推送通知，进入应用，无法获取推送内容

### ISSUE THREAD

**Issue by xvjiangzheng** [jpush/jpush-phonegap-plugin#43]
请教一下，当应用出于停止状态时(如返回桌面)，点击通知进入应用是可以获取通知的内容和附加信息，但是当退出应用时，通知是可以接收的，但是进入应用时无法获取通知里的内容和附加信息，这是什么原因？

**Comment by noru** [comment]
请问楼上是怎样获取通知内容和附加信息的? 我注册"jpush.openNotification"的事件后并无任何反应.

**Comment by xvjiangzheng** [comment]
JPushPlugin.js文件修改
JPushPlugin.prototype.receiveMessageInAndroidCallback方法
this.openNotification=bToObj-->this.receiveNotification = bToObj
JPushPlugin.prototype.openNotificationInAndroidCallback方法
this.receiveNotification=bToObj-->this.openNotification=bToObj

````
document.addEventListener("jpush.openNotification", onOpenNotification, false);
````

````
        function onOpenNotification(event) {
            try {
                //内容
                var alertContent = window.plugins.jPushPlugin.openNotification.alert;
                //附加信息
                var extrasContent = window.plugins.jPushPlugin.openNotification.extras['cn.jpush.android.EXTRA'].newsid;
                $state.go('tab.news-detail', { newsId: extrasContent});
            }
            catch (exception) {
                console.log("JPushPlugin:onReceiveMessage-->" + exception);
            }
        }
````

**Comment by zhangqinghe** [comment]
@xvjiangzheng  请问是什么平台

**Comment by xvjiangzheng** [comment]
android平台

**Comment by zhangqinghe** [comment]
@xvjiangzheng 能否打开调试模式，打印出更多的log后，将log贴出来看看

**Comment by xvjiangzheng** [comment]
@zhangqinghe 好的，那我先自查一下，因为我的调试只能使用adb的，日志太多了

**Comment by xvjiangzheng** [comment]
@zhangqinghe 
问题和官网论坛这个问题一样
[在phoneGap中Android环境下如何在程序关闭的情况下点击Notification打开程序后显示Notification内容？](https://www.jpush.cn/qa/?qa=6874/%E5%9C%A8phonegap%E4%B8%ADandroid%E7%8E%AF%E5%A2%83%E4%B8%8B%E5%A6%82%E4%BD%95%E5%9C%A8%E7%A8%8B%E5%BA%8F%E5%85%B3%E9%97%AD%E7%9A%84%E6%83%85%E5%86%B5%E4%B8%8B%E7%82%B9%E5%87%BBnotification%E6%89%93%E5%BC%80%E7%A8%8B%E5%BA%8F%E5%90%8E%E6%98%BE%E7%A4%BAnotification%E5%86%85%E5%AE%B9%EF%BC%9F)

**Comment by zhangqinghe** [comment]
android平台JPush推送服务，会有一个程序的自启动设置，但是如果某一部分机型限制自启动，JPush就会出现上面的问题。具体机型请参考
第三方系统收不到推送的消息

由于第三方 ROM 的管理软件需要用户手动操作

小米【MIUI】

自启动管理：需要把应用加到【自启动管理】列表，否则杀进程或重新开机后进程无法开启
通知栏设置：应用默认都是显示通知栏通知，如果关闭，则收到通知也不会提示
网络助手：可以手动禁止已安装的第三方程序访问2G/3G和WIFI的网络和设置以后新安装程序是否允许访问2G/3G和WIFI的网络
华为【Emotion】

自启动管理：需要把应用加到【自启动管理】列表，否则杀进程或重新开机后进程不会开启，只能手动开启应用
后台应用保护：需要手动把应用加到此列表，否则设备进入睡眠后会自动杀掉应用进程，只有手动开启应用才能恢复运行
通知管理：应用状态有三种：提示、允许、禁止。禁止应用则通知栏不会有任何提醒
魅族【Flyme】

自启动管理：需要把应用加到【自启动管理】列表，否则杀进程或重新开机后进程无法开启
通知栏推送：关闭应用通知则收到消息不会有任何展示
VIVO【Funtouch OS】

内存一键清理：需要将应用加入【白名单】列表，否则系统自带的“一键加速”，会杀掉进程
自启动管理：需要将应用加入“i管家”中的【自启动管理】列表，否则重启手机后进程不会自启。但强制手动杀进程，即使加了这个列表中，后续进程也无法自启动。
OPPO【ColorOS】

冻结应用管理：需要将应用加入纯净后台，否则锁屏状态下无法及时收到消息
自启动管理：将应用加入【自启动管理】列表的同时，还需要到设置-应用程序-正在运行里锁定应用进程，否则杀进程或者开机后进程不会开启，只能手动开启应用

**Comment by danielking** [comment]
这个问题我也遇到，不是说程序退出后台接收不到推送，而是接收到推送后，点击那条推送启动程序后，程序没有执行JPushPlugin:openNotificationInAndroidCallback

**Comment by taoleifeng** [comment]
我也遇到了这个问题，肿么解决？
