### ISSUE TITLE
Ionic 5 + Capacitor，iOS 集成后启动，在 AppDelegate+JPush.m 的 init_plus 函数处报错

### ISSUE THREAD

**Issue by ParryQiu** [jpush/jpush-phonegap-plugin#430]
* 插件版本:  libjpush-ios-3.2.6.a
* 平台（Android / iOS）: iOS
* Cordova version (```cordova -v```): 
Capacitor CLI   : 1.5.1
@capacitor/core : 1.5.1
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)
Ionic CLI                     : 6.9.2
Ionic Framework               : @ionic/angular 5.1.1

## 期望效果

程序正常启动，如果注释掉 init_plus 函数，App 可以正常启动，但是 jPush 没有正常注册。App 没有请求到推送权限。

## 实际效果

正常启动注册接收推送消息。

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs

启动错误截图如下

![log](https://image.devopen.club/Jietu20200530-164518@2x.png)

**Comment by ParryQiu** [comment]
还是切换到 Cordova 框架解决了。

**Comment by JoshLipan** [comment]
暂不支持Capacitor

**Comment by AlwaysLoveme** [comment]
> 暂不支持Capacitor

什么时候支持

**Comment by conkyliu** [comment]
应该是拿不到key值，很多capacitor用cordova的话会拿不到预设的variable，所以直接写死值

**Comment by AlwaysLoveme** [comment]
> variable

具体在哪里写死呢？不太懂IOS原生
