### ISSUE TITLE
不能初始

### ISSUE THREAD

**Issue by w2ang** [jpush/jpush-phonegap-plugin#44]
在app.js 初始化时，window.plugins.jPushPlugin.init();模拟器下出错 Unable to get property 'jPushPlugin' of undefined or null reference。

**Comment by zhangqinghe** [comment]
@w2ang 你这个是android平台吧？ 因为android平台没有添加x86必须的so文件

**Comment by w2ang** [comment]
\platforms\android\libs\ 下面只有armeabi，和armeabi-7，请问如何添加x86的so文件

**Comment by w2ang** [comment]
网上找不到1.73 so文件。从1.74SDK中找到了 so文件，还是出错？？

**Comment by zhangqinghe** [comment]
我尽快升级 android sdk 这样你就可以使用1.74的so文件了，历史版本x86的so 在jpush portal上找不到.

**Comment by w2ang** [comment]
非常感谢。
因为我对PHONEGAP不熟，有个问题想请教你。
如果我的PHONEGAP APP没开/在后台时，当我点击推送，能否启动我的APP。
我 现在用.jPushPlugin.openNotificationInAndroidCallback ，

**Comment by zhangqinghe** [comment]
区分iOS和android平台，iOS可以，android情况较为复杂，请参照这里http://docs.jpush.io/guideline/faq/#android
