### ISSUE TITLE
请教问题，ionic+ngcordova添加jpush后运行 ionic build android编译错误

### ISSUE THREAD

**Issue by lanbingfeihan** [jpush/jpush-phonegap-plugin#45]
系统环境：windows7 64位  ionic+ngcordova 

BUILD FAILED
E:\Android\android-sdk\tools\ant\build.xml:720: The following error occurred whi
le executing this line:
E:\Android\android-sdk\tools\ant\build.xml:734: Compile failed; see the compiler
 error output for details.

Total time: 1 second

D:\2015\app\code\myApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f D:\2015\app\code\my
App\platforms\android\build.xml -Dout.dir=ant-build -Dgen.absolute.dir=ant-gen"
�

**Comment by zhangqinghe** [comment]
是不是在模拟器环境下？

**Comment by jacklybill** [comment]
質問の解決方法を教えて頂けないでしょうか？
宜しくお願い致します。
