### ISSUE TITLE
官方不打算出一个Capacitor插件吗？

### ISSUE THREAD

**Issue by Lyfei** [jpush/jpush-phonegap-plugin#456]
比起大家魔改方便一些

**Comment by UTSOURCE** [comment]
对支持Capacitor才是ionic官方支持得

**Comment by Lyfei** [comment]
官方能给个答复么

**Comment by AlwaysLoveme** [comment]
我开发了一款capacitor插件，可以使用基础功能，但暂未支持厂商通道，https://github.com/AlwaysLoveme/capacitor-plugin-jpush

**Comment by Lyfei** [comment]
2025了，官方还不考虑吗
