### ISSUE TITLE
meteor 集成问题

### ISSUE THREAD

**Issue by xuehexi** [jpush/jpush-phonegap-plugin#50]
不能初始化，我是用安卓手机usb调试
Uncaught TypeError: Cannot call method 'init' of undefined
 window.plugins.jPushPlugin 找不到
请问是什么问题引起

**Comment by zhangqinghe** [comment]
请问如何安装的插件？

**Comment by xuehexi** [comment]
因为实在找不到meteor安装本地cordova插件的办法。我只能fork您的工程，正确配置plugin.xml和JPushPlugin.java文件。
1. 安装
wangdeMacBook-Pro:demo wang$ meteor add cordova:cn.jpush.phonegap.JPushPlugin@https://github.com/xuehexi/jpush-phonegap-plugin/tarball/5d2dc5d1ded103672413379fef9de2784ee70fd2
具体是参照https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration
2. 调用（index.js）
onDeviceReady: function() {
        app.receivedEvent('deviceready');
        window.plugins.jPushPlugin.init(); 
    }
3. 错误
 (android:http://meteor.local/client/voice.js:50) Uncaught TypeError: Cannot call method 'init' of undefined

按照教程在cordova中新建工程集成您的jpush插件没有问题，本机调试通过，能收到推送消息，问题就是在meteor中调用有问题。

**Comment by xuehexi** [comment]
在日志中发现如下错误
`
/Users/wang/Library/Android/sdk/tools/ant/build.xml:538: Unable to resolve project target 'android-19'
`
正在尝试解决，是这个引起的吗？

**Comment by xuehexi** [comment]
问题解决，在meteor中调用成功。
对于新手注意几个问题：
1.  meteor怎么调用cordova插件。（还是没有找到调用本地文件的办法）
2.  使用meteor run android-device --verbose 调试。
3. 在项目中配置mobile-config.js可以指定项目包名（对应JPushPlugin.java文件import your.package.name.R替换为在Portal上注册该应用的包名，例如(com.thi.pushtest)）
`
App.info({
  id:'com.xuehexi.hello',
  name: 'demo'
});
`
4. Unable to resolve project target 'android-19' 问题，下载相应版本sdk即可

**Comment by qdsang** [comment]
meteor add cordova:cn.jpush.phonegap.JPushPlugin@https://github.com/qdsang/jpush-phonegap-plugin/tarball/d9a2b85156d9357fb76b56ff6ee117083606acf5

或者可以这样，我这个版本就是为了meteor改的

**Comment by liangsun** [comment]
@qdsang :+1:  私以为，对于APPKEY的使用preference的配置，以及使用`android.content.Context;`而不是`R`的重构，都可以提Pull Request上来的。
