### ISSUE TITLE
设置tags只能设置成功一个。

### ISSUE THREAD

**Issue by qdsang** [jpush/jpush-phonegap-plugin#52]
测试平台IOS 8.3

window.plugins.jPushPlugin.setTagsWithAlias(['A23','A24']);

设置回调只设置成功一个tag

 tagAliasResult result code:0 tags:A23 alias:null

**Comment by qdsang** [comment]
@zhangqinghe

**Comment by zhangqinghe** [comment]
请在JPushPLugin.m的setTagsWithAlias函数里下个断电，调试一下传给APService的函数的tag和alias到底是什么数值

**Comment by qdsang** [comment]
window.plugins.jPushPlugin.setTagsWithAlias(['A23,A24']);
调查发现得这么写。。

**Comment by zhangqinghe** [comment]
如果你只设定tag
请用：window.plugins.jPushPlugin.setTags(tags);
