### ISSUE TITLE
Android 5.0 64位机器上找不到jpush的so库

### ISSUE THREAD

**Issue by fantasybei** [jpush/jpush-phonegap-plugin#53]
我在一台华为的Android手机上测试的时候，发现只要调用setAlias，App就崩溃了。
从错误日志中看到下面的错误消息:
lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjpush175.so"
在生成的android项目的lib下面，发现有下面几个目录
armeabi armeabi-v7a armeabi-v8a  arm64-v8a
除了最后一个目录，其他几个都有libjpush175.so文件。 我看plugin.xml是把 arm64-v8a/libjpush175.so 拷贝到了libs/armeabi-v8a目录，对android喝cordova plugin不熟，但是我手动把插件里arm64-v8a/libjpush175.so 拷贝到android工程里的arm64-v8a文件夹下就没有问题了。

不知道是不是个问题？

谢谢

**Comment by zhangqinghe** [comment]
🙏感谢反馈，马上修复

**Comment by TonyLuo** [comment]
@zhangqinghe 问题修复了吗？我用最新版的plugin还是有同样的问题呀
11-01 12:52:15.363: E/AndroidRuntime(2232): FATAL EXCEPTION: Thread-209
11-01 12:52:15.363: E/AndroidRuntime(2232): Process: com.test.mobile, PID: 2232
11-01 12:52:15.363: E/AndroidRuntime(2232): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.mobile-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libjpush175.so"
11-01 12:52:15.363: E/AndroidRuntime(2232): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
11-01 12:52:15.363: E/AndroidRuntime(2232): 	at java.lang.System.loadLibrary(System.java:989)
11-01 12:52:15.363: E/AndroidRuntime(2232): 	at cn.jpush.android.service.PushProtocol.<clinit>(Unknown Source)
11-01 12:52:15.363: E/AndroidRuntime(2232): 	at cn.jpush.android.service.n.run(Unknown Source)
11-01 12:52:15.400: I/OpenGLRenderer(637): Initialized EGL, version 1.4
11-01 12:52:15.450: W/EGL_emulation(637): eglSurfaceAttrib not implemented
11-01 12:52:15.450: W/OpenGLRenderer(637): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa277a360, error=EGL_SUCCESS
11-01 12:52:16.003: I/Choreographer(637): Skipped 31 frames!  The application may be doing too much work on its main thread.
11-01 12:52:44.750: D/NetworkMonitorNetworkAgentInfo [WIFI () - null](637): Probably not a portal: exception java.net.SocketTimeoutException: failed to connect to clients3.google.com/74.125.23.138 (port 80) after 10000ms

**Comment by TonyLuo** [comment]
是不是不支持x86？我在用虚拟机测试android

**Comment by TonyLuo** [comment]
我直接把libjpush175.so放到x86/lib下不能用。
11-01 13:18:13.694: E/art(2577): dlopen("/data/app/com.test.mobile-2/lib/x86/libjpush175.so", RTLD_LAZY) failed: dlopen failed: "/data/app/com.test.mobile-2/lib/x86/libjpush175.so" has unexpected e_machine: 40
11-01 13:18:13.695: E/AndroidRuntime(2577): FATAL EXCEPTION: Thread-239
11-01 13:18:13.695: E/AndroidRuntime(2577): Process: com.test.mobile, PID: 2577
11-01 13:18:13.695: E/AndroidRuntime(2577): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.test.mobile-2/lib/x86/libjpush175.so" has unexpected e_machine: 40
11-01 13:18:13.695: E/AndroidRuntime(2577): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
11-01 13:18:13.695: E/AndroidRuntime(2577): 	at java.lang.System.loadLibrary(System.java:989)
11-01 13:18:13.695: E/AndroidRuntime(2577): 	at cn.jpush.android.service.PushProtocol.<clinit>(Unknown Source)
11-01 13:18:13.695: E/AndroidRuntime(2577): 	at cn.jpush.android.service.n.run(Unknown Source)
