### ISSUE TITLE
插架安装太复杂，不能做到开箱即用

### ISSUE THREAD

**Issue by bastengao** [jpush/jpush-phonegap-plugin#54]
我是第一次碰到安装插件还需要改插件代码的情况。能不能做到开箱即用，这样可以省去很多麻烦。 :smile_cat: 

能像 ionic push 这是使用就挺好的，可以借鉴下 ionic push.

**Comment by zhangqinghe** [comment]
能否给个网址 让我看看？

**Comment by bastengao** [comment]
ionic push 是 ionic 提供的服务 https://apps.ionic.io/landing/push 。 ionic 插件在这里 http://ngcordova.com/docs/plugins/pushNotifications/ , 文档在这里 http://docs.ionic.io/v1.0/docs/push-from-scratch 。希望能给你帮助。

**Comment by zhangqinghe** [comment]
谢谢

**Comment by xml777** [comment]
ionic push 好像是使用的 google 的 gcm ,国内能用么？

**Comment by bastengao** [comment]
@xml777 gcm 不能用，但这不此帖的重点。

**Comment by bastengao** [comment]
https://github.com/BenBBear/cordova-plugin-leanpush 这个插件的安装也挺简单的。
