### ISSUE TITLE
android 点击通知 openNotification 不会被触发，反而 receiveNotification 会被触发

### ISSUE THREAD

**Issue by bastengao** [jpush/jpush-phonegap-plugin#56]
测试 iOS 是正常的，android 无论应用内还是应用外都是触发 receiveNotification。

**Comment by zhangqinghe** [comment]
iOS和android系统机制导致的，iOS是存在后台状态，所以后台状态下系统默认的行为是展示通知不触发消息，如果程序在前台则相反
android 实际上没有和iOS一样后台所以一直都会触发receiveNotification
