### ISSUE TITLE
监听新安装应用的权限问题

### ISSUE THREAD

**Issue by fantasybei** [jpush/jpush-phonegap-plugin#59]
我打包了一个包含jpush库的Android app，提交到豌豆荚，但是提示:
请补充「监听新安装应用」权限的用途解释.

我在jpush网站看了下好像是jpush库添加的，如果是没有用的，可以删掉么？
我对phonegap插件不熟，我手动在AndroidManifest.xml里面删掉下面这一段:
```xml
<intent-filter>
    <action android:name="android.intent.action.PACKAGE_ADDED"/>
    <action android:name="android.intent.action.PACKAGE_REMOVED"/>
    <data android:scheme="package"/>
</intent-filter>
```
然后用cordova build --release android。好像还是会另外一个包含上面这段内容的<receiver android:name="cn.jpush.android.service.PushReceiver">的元素被添加上去添加上去，导致有两个同样的receiver元素，编包出错。

请问这个怎么解决？谢谢

**Comment by zhangqinghe** [comment]
需要修改plugin.xml重相关的代码 再执行命令行重新编译

**Comment by fantasybei** [comment]
@zhangqinghe 这个权限是jpush插件需要的么？如果是不需要的，可不可在你们的库删除掉？因为不然每次别人编包的时候也需要去改一下。

**Comment by zhangqinghe** [comment]
http://docs.jpush.io/guideline/android_guide/ 请参照文档，必须的和可选的都有标记
