### ISSUE TITLE
文档描述

### ISSUE THREAD

**Issue by xml777** [jpush/jpush-phonegap-plugin#61]
AppDelegate.m在哪里啊，src下面没有。

**Comment by zhangqinghe** [comment]
iOS下载都有这个文件  打开xcode cmd+3  搜一下这个类 AppDelegate

**Comment by xml777** [comment]
这个还需要在mac xcode 中编译吗？

**Comment by zhangqinghe** [comment]
嗯 需要

**Comment by zhangqinghe** [comment]
发AppStore 没有mac肿么办。。。

**Comment by xml777** [comment]
我的意思是用了这个插件，还需要吧src下面的ios目录中的源代码编译一次？

**Comment by zhangqinghe** [comment]
是的，加了代码 就必须重新编译。

**Comment by xml777** [comment]
嗯，是这样的，我用的visual studio 2015  ，编译ios的时候，自动连接到事先设置好的mac机器上，我根本没有机会修改AppDelegate.m这个文件。

**Comment by zhangqinghe** [comment]
资源管理器搜索，文本编辑器打开

**Comment by xml777** [comment]
我第一次开发移动项目，不是很 明白 。再麻烦一下。
这个文件在哪里有？ 我下载下来的文件中是没有的

**Comment by zhangqinghe** [comment]
资源管理器 中搜索  AppDelegate.m

**Comment by xml777** [comment]
1.插件源代码中是否有 AppDelegate.m这个文件？
2.资源管理器 中搜索？ 实在mac中搜索吗？

**Comment by zhangqinghe** [comment]
1.有，可定有
2.win 叫资源管理器，mac 叫finder 反正就是文件系统，一搜就知道

**Comment by xml777** [comment]
github的源代码中我真没有找到， 麻烦再问一下，在哪个目录下？

**Comment by zhangqinghe** [comment]
/Users/zhangqinghe/Desktop/phonegapTest/platforms/ios/phonegapTest/Classes
这是我的目录 参考吧

**Comment by xml777** [comment]
github代码中那个目录下，谢谢

**Comment by zhangqinghe** [comment]
github代码代码没有AppDelegate.m, 这个文件是cordova生成的

**Comment by xml777** [comment]
哦，我再研究一下，非常感谢你的耐心解答。
