### ISSUE TITLE
AppDelegate 文件的建议

### ISSUE THREAD

**Issue by xml777** [jpush/jpush-phonegap-plugin#62]
建议不要让用户自己修改AppDelegate.m文件， 而是应该增加“AppDelegate+JPush.h” 和“AppDelegate+JPush.m”这两个文件。参考https://github.com/phonegap-build/PushPlugin

**Comment by zhangqinghe** [comment]
这个很好，🙏，下个版本将更新

**Comment by wangyuzju** [comment]
@xml777 @zhangqinghe 

请问一下 增加“AppDelegate+JPush.h” 和“AppDelegate+JPush.m”这两个文件的原理是啥？对 AppDelegate.m 文件会有什么影响？

为什么加了上面两个文件就不用修改 AppDelegate.m 文件了呢

**Comment by xml777** [comment]
这个是object C的开发规范吧，我对Object C也不是很熟
