### ISSUE TITLE
精简APPKEY等变量的设置

### ISSUE THREAD

**Issue by wgjtyu** [jpush/jpush-phonegap-plugin#63]
可以参考 https://github.com/BenBBear/cordova-plugin-leanpush/blob/master/plugin.xml 的方法来精简APPKEY的设置，而不像目前需要用户手动填写到plugin.xml中。

参考网页中的方法，可以在安装时，直接通过命令行来指定APPKEY等参数

cordova plugin add plugin_url --variable APPKEY=xxx

**Comment by zhangqinghe** [comment]
我参考一下，以前曾经看过但是没找到合理的解决方案

**Comment by wgjtyu** [comment]
哈，我试着精简了一下，可以工作了，发了一个pull request，请参考一下吧

**Comment by zhangqinghe** [comment]
非常感谢，我测试一下，如果ok了我就把这部分代码合并一下

**Comment by xml777** [comment]
完全不用修改代码了么？

**Comment by woshidag** [comment]
感谢楼主

**Comment by sylfree9999** [comment]
求指教如果这样的话那AppKey是存在哪里呀？我之后如果想更改AppKey该如何操作呀？

**Comment by wgjtyu** [comment]
@sylfree9999 会保存到package.json中的

**Comment by sylfree9999** [comment]
@wgjtyu 我很蠢的把所有的package.json都找了一遍（我是ionic的项目），结果没有找到插件下面的package.json
![image](https://cloud.githubusercontent.com/assets/15099465/11999521/f440f25a-aafa-11e5-8711-9f6f3f89a5cb.png)

不过我发现在android.json和fetch.json中有类似的信息
![qq 20151225113429](https://cloud.githubusercontent.com/assets/15099465/11999553/8a49bd7c-aafb-11e5-8676-99a4db611f12.png)

会是在这里么？还有请教一下就是将来如果想要更改package name的话有什么简单安全的方法可以更改所有地方的package name么？

**Comment by wgjtyu** [comment]
@sylfree9999 在ionic项目根目录下的package.json里有插件的配置。每次ionic plugin rm / ionic plugin add都会自动修改package.json。另外所说的修改package name具体是指修改什么？

**Comment by sylfree9999** [comment]
@wgjtyu 在我的ionic项目根目录下的package.json里面不知道为何跟您说的有些不一样，我这里只有cordova插件的信息:
![image](https://cloud.githubusercontent.com/assets/15099465/12000161/e2810a94-ab0b-11e5-8a30-082ac8b68fa1.png)
另外所说的package name就是指我们每次新建一个ionic start myApp XXX的时候会在config.xml里面生成一个这个名字，如果不更改的话，我看安装jPush的时候用的package name也是这个:
![image](https://cloud.githubusercontent.com/assets/15099465/12000189/502340b2-ab0c-11e5-8c52-3c9963962bef.png)
![image](https://cloud.githubusercontent.com/assets/15099465/12000213/c3dfab8a-ab0c-11e5-9de6-ac7487dbb2f1.png)

我搜了一下网上说改这个名字，有人说只要在config.xml里更改就可以，但是我这里更改了以后build就不成功了，所以想问下有没有啥好的方法可以全局都替换掉。谢谢哈！

**Comment by sylfree9999** [comment]
后来发现全局替换是可以Build通过的，只是稍微麻烦一点，像jPush插件里的一些文件要做些更改才行
