### ISSUE TITLE
cordova 插件可以参考 aerogear unifiedpush ，最NB的push插件。

### ISSUE THREAD

**Issue by xml777** [jpush/jpush-phonegap-plugin#64]
最好参考 aerogear unifiedpush server  ，是redhat 官方开源的消息推送平台。而且官方提供了对cordova的支持。这个是我见过的最NB的push 插件 。app端一个json格式config配置就搞定所有参数设置。一行源代码都不用修改。还免费给你提供一个openshift的虚拟机。

中文例子：http://segmentfault.com/a/1190000000358740

客户端：
官网地址：https://aerogear.org/docs/guides/aerogear-cordova/AerogearCordovaPush/
源代码：https://github.com/aerogear/aerogear-cordova-push

服务端：
每个客户单独一个服务端，部署在openshift 上。
官网：https://aerogear.org/push/#unifiedpush
源码：https://github.com/aerogear/aerogear-unifiedpush-server

**Comment by plusmancn** [comment]
感觉jpush还要跑到ide里面，去做二次开发，这个有点不能接受。

**Comment by zhangqinghe** [comment]
@plusmancn 这个主要是封装一下本地的API，因为先有的local api再有这个插件，所以很多地方需要做一些妥协。我也会努力改进插件安装步骤尽量方便大家

**Comment by zhangqinghe** [comment]
稍后我过一下 aerogear这个是怎么写的。。。
