### ISSUE TITLE
按照官方教程报错

### ISSUE THREAD

**Issue by a81584944** [jpush/jpush-phonegap-plugin#66]
按照官方教程 
1.cordova plugin add XXXXXX
2.打开xproject文件，修改pushConfig.plist  app-key ：  XXXXXXX   chanel： 0
3.模拟器报错
  Unkown value for APS_FOR_PRODUCTION (null), default set to development aps evironment

请问下是有什么地方没有设置么

**Comment by zhangqinghe** [comment]
@a81584944 这个应该是iOS的一个警告，是为了兼容以前版本的一些问题，对iOS集成无影响

**Comment by a81584944** [comment]
现在生产环境推送没问题，但是我现在想要真机调试测试环境，上传了证书等等，真机调试的时候一直报

Jpush WARNING
 Unkown value for APS_FOR_PRODUCTION (null), default set to development aps evironment

我的PushConfig.plist  中的 CHANNEL  也置为0了

**Comment by zhangqinghe** [comment]
这个WARNING没有影响

**Comment by a81584944** [comment]
但是我试了开发环境推送不过来啊。。。

还有我看到我的  PushConfig.plist 里面只有两个key

一个是APP_KEY
一个是CHANNEL

这样正常么  CHANNEL  0就是开发环境  1就是生产环境是吧？

**Comment by zhangqinghe** [comment]
CHANNEL 这个标志渠道，并非标志生产和开发环境。如果生产收不到 加我们管理的技术支持的群 458409146

**Comment by a81584944** [comment]
能否加一下群。。
