### ISSUE TITLE
ios AppDelegate (JPush) +(void)load{)中  class_getClassMethod要换成class_getInstanceMethod

### ISSUE THREAD

**Issue by linglong117** [jpush/jpush-phonegap-plugin#67]
ios AppDelegate (JPush) +(void)load{)中  class_getClassMethod要换成class_getInstanceMethod才起作用我用的 xcode6.4

+(void)load{
    
    Method origin;
    Method swizzle;
    
    origin=class_getClassMethod([self class],@selector(init));
    swizzle=class_getClassMethod([self class], @selector(init_plus));
    method_exchangeImplementations(origin, swizzle);
}

**Comment by zhangqinghe** [comment]
ok,收到 我确认下问题
