### ISSUE TITLE
这个插件支持的cordova最低版本和安卓最低版本是多少？

### ISSUE THREAD

**Issue by shikelong** [jpush/jpush-phonegap-plugin#68]
谢谢

**Comment by shikelong** [comment]
支持cordova 3.x版本么

**Comment by zhangqinghe** [comment]
1. android版本 目前SDK只支持Android 2.1或以上版本的手机系统。富媒体信息流功能则需Android3.0或以上版本的系统。
2. cordova版本 3.0或以上版本
