### ISSUE TITLE
获取到的registrationID是空的

### ISSUE THREAD

**Issue by ken8271** [jpush/jpush-phonegap-plugin#70]
我用的cordova的版本是5.1.1的

在页面中获取不到registrationID

![image](https://cloud.githubusercontent.com/assets/10719798/9299556/b63c4098-44ef-11e5-9c94-ab9c40375624.png)

在onGetRegistradionID中alert出来是空的 

这是怎么回事？

**Comment by Hanruis** [comment]
同样遇到这个问题。我开始以为是需要 deviceReady 之后才执行，后来发现不是这样。在想可能是 window.plugins.jPushPlugin.init 可能需要比较长的事件，在这个基础上加入了回调，还是没有还用。

**Comment by Hanruis** [comment]
看了相关的问题，registrationID 这个 api 设计有点问题的。应该获取到极光分配的设备 id 之后才调用回调，但实际上 api 应该是被设计成仅仅是读取 registrationID  这个变量（类似的这个思路）。。所以楼主，你需要设定定时器，不断访问这个 id 是否已经被分配了。

**Comment by zhangqinghe** [comment]
@Hanruis  你是正确的，因为原生SDK底层的API设计问题，所以你的方法可行。获取registrationID的策略是这样的:首先检测本地数据是否保存registrationID，如果保存则直接返回，否则就返回""字符串。因此第一次没有注册成功的时候是没有registrationID的

**Comment by Whedoloca** [comment]
@Hanruis  方便贴一下你的init部分的代码么？

我之前尝试了一直判断是否得到ID值，然后就直接死循环在了这个里面，正常来说这个init需要多久？
还有怎么查看我是因为init时间久没有注册上，还是别的原因没有注册成功，我网上很多人都是直接init一下就可以用了，我一直很疑惑为什么我这么写了一直连不上。
万分感谢~

**Comment by Hanruis** [comment]
@Whedoloca 有时候是会这样，就是一直 getRegistrationID 得到的结果是空。昨天我们也遇到了，一个下午都拿不到 id ，今天就可以了。应该是极光那边的问题。init 部分没什么。就是先调用 init()  接着调用 getRegistrationID() 方法（这里会设一个定时器），直到拿到的 id 不为空。

**Comment by Whedoloca** [comment]
@Hanruis 我这里一直显示是缺少android的permission，但我按照git里的readme修改了package的名字和APP_KEY的值，还需要在添加什么么？JPUSH_CHANNEL值需要改么？还有这里需要修改的package是哪个package的值。
那个定时函数是为了保证拿到RegistrationID还是说为了保证init的实现注册手机，如果只是为了得到registrationID，就是说手机只要运行就会init，那么我的手机总会注册到portal上，只是时间的问题，现在是我手机一直注册不了。。。是不是我哪里理解错了。十分感谢~

**Comment by wuxiaomo6174** [comment]
各位，这个问题现在解决了吗？  怎么又出现了~~~小米手机

**Comment by darkterrorooo** [comment]
遇到这种情况，可能是 RegistrationID 还没有准备好,  特别是刚刚安装应用时。可以等一小段时间后再取尝试几次。参考新版本demo （index.html）

**Comment by xwartz** [comment]
你们都是通过轮询的方式获取？
