### ISSUE TITLE
IOS收到推送通知后，直接打开应用不会触发'jpush.receiveNotification'或'jpush.openNotification'事件

### ISSUE THREAD

**Issue by ljspace** [jpush/jpush-phonegap-plugin#71]
IOS成功接收到推送通知后，直接打开应用不会发'jpush.receiveNotification'或'jpush.openNotification'事件，导致应用无法获取通知内容。Android在该情况下会正常触发事件。

通过IOS消息中心点击通知进入应用和应用在打开的状态下是可以正常触发上面两个事件。

**Comment by zhangqinghe** [comment]
请参考 #56
