### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by dandebin** [jpush/jpush-phonegap-plugin#78]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JPushPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_SecItemAdd", referenced from:
      -[JPFKeychain setObject:forKey:] in libPushSDK-1.8.3.a(JPFKeychain.o)
  "_SecItemCopyMatching", referenced from:
      -[JPFKeychain dataForKey:] in libPushSDK-1.8.3.a(JPFKeychain.o)
  "_SecItemDelete", referenced from:
      -[JPFKeychain setObject:forKey:] in libPushSDK-1.8.3.a(JPFKeychain.o)
  "_SecItemUpdate", referenced from:
      -[JPFKeychain setObject:forKey:] in libPushSDK-1.8.3.a(JPFKeychain.o)
  "_deflate", referenced from:
      _JPFGzip in libPushSDK-1.8.3.a(JPFUtilities.o)

**Comment by darkterrorooo** [comment]
这是在模拟器下运行的吗

**Comment by darkterrorooo** [comment]
请下载最新的插件，最新插件支持： armv7 armv7s i386 x86_64 arm64  几种CPU architecture
