### ISSUE TITLE
只有ios9能注册和推送，其他版本的ios都不能正常使用

### ISSUE THREAD

**Issue by wisegps** [jpush/jpush-phonegap-plugin#79]
是这样，我现在用的是 intel 的XDK开发工具，然后安装插件的方式并不是命令行的，所以这里有一点区别，先提及一下；
然后按文档配置了各个地方，最后device插件也加上了，打包成安卓可以正常使用，注册与推送都没有问题；
但打包成ios就无法注册了，怎么都返回空，极光控制台里也没有新用户显示，于是烦恼了好一阵；
结果前两天使用了同事已经升级了ios9的5s来测试，居然注册成功了，然后推送也能正常收到；
一直毫无头绪，希望能提供一个解决的方向，不胜感激

**Comment by darkterrorooo** [comment]
如果在某个机器上推送正常，在某些机器上不正常。有可能是签名引起的。
签名这里如果使用的是Automatic ,xcode 对不同的手机，会自动适配一个 provisioning profile。
请改非 Automatic。确定使用了正确的 provisioning profile
