### ISSUE TITLE
JPush提示：缺少统计代码

### ISSUE THREAD

**Issue by nqdy666** [jpush/jpush-phonegap-plugin#80]
已经添加appkey，并顺利使用cordova打包成apk，并安装到安卓真机上，但是会提示这个
JPush提示：缺少统计代码
这个问题怎么解决呢？

**Comment by xifengzhu** [comment]
android/java/com/ezitask/app/MainActivity 目录下添加一下代码:
```
import cn.jpush.android.api.JPushInterface;
    //新增
  @Override
  protected void onResume() {
      super.onResume();
      JPushInterface.onResume(this);
  }

  //新增
  @Override
  protected void onPause() {
      super.onPause();
      JPushInterface.onPause(this);
  }
```

**Comment by floraluo** [comment]
补充楼上
MainActivity.java位于platforms/android/src/*/your/packagename/url/*
比如我的包名是com.ionicframework.ioncus，那上面的路径就是platforms/android/src/com/ionicframework/ioncus/
^_^

**Comment by Berial** [comment]
然而加上了还是会提示

**Comment by cnryb** [comment]
@floraluo @xifengzhu 无法找到对应的文件，莫非已经升级了？

**Comment by Darcy20** [comment]
弄成release模式就解决了
