### ISSUE TITLE
sdk好老了，麻烦放上最新的。麻烦尽快让支持IOS9 和 安卓5.1 等新系统 。

### ISSUE THREAD

**Issue by chengrenz** [jpush/jpush-phonegap-plugin#81]
麻烦尽快让支持IOS9 和 安卓5.1 等新系统 。

**Comment by TonyLuo** [comment]
+1

**Comment by crossmo** [comment]
+1

**Comment by newhzh** [comment]
ios最新版是1.8.8了，这插件里的还是1.8.3？

**Comment by chengrenz** [comment]
是呀，还不更新，能让他们快点更新吧

**Comment by crossmo** [comment]
https://github.com/pipitang/jpush-phonegap-plugin

**Comment by chengrenz** [comment]
多谢终于有人更新到别的地了

**Comment by darkterrorooo** [comment]
@chengrenz  已更新，谢谢

**Comment by chengrenz** [comment]
多谢，配置说明文档，没有变吗，不需要更新下吗？

**Comment by crossmo** [comment]
文档需要更新，但是没有。可以直接 
```
cordova plugin add https://github.com/pipitang/jpush-phonegap-plugin --variable API_KEY=your_key
```
参数名字好像是这个，如果不是，按照提示改下，本来期望jpush的人改，好像他们死了，一直没改，只能自己动手了。

真TM担心这个公司也死了。

**Comment by crossmo** [comment]
抱歉，刚发现极光的人活了，哈。

**Comment by darkterrorooo** [comment]
@chengrenz  文档没有改变。现在只是升级了库。 配置如果改了会更新文档的。

**Comment by darkterrorooo** [comment]
@crossmo  哈哈，会持续更新的

**Comment by crossmo** [comment]
@darkterrorooo 大锅，文档改更新了，需要加 --variable API_KEY。你新接手的吧？建议你也耍耍，才知道大家的需求和痛苦嘛哈。
