### ISSUE TITLE
android:使用了openNotificationInAndroidCallback方法，同时注册jpush.openNotification事件的问题

### ISSUE THREAD

**Issue by floraluo** [jpush/jpush-phonegap-plugin#85]
我同时使用了这两个如下
document.addEventListener('jpush.openNotification',function(){}, false);
$window.plugins.jPushPlugin.openNotificationInAndroidCallback=function(){};
当推送通知的时候只有第二个方法会被执行，而jpush.openNotification事件的回调方法无法执行。
如果我注释掉第二行，那jpush.openNotification事件监听就能被执行。
这是为什么呢？？？

**Comment by lhw5123** [comment]
因为 jpush.openNotification 是由jPushPlugin.openNotificationInAndroidCallback 来触发的，也就是说执行顺序是 openNotificationInAndroidCallback -> jpush.openNotification 的回调方法，所以必须要在 openNotificationInAndroidCallback 方法中触发 jpush.openNotification 事件，jpush.openNotification 的回调方法自然才会执行。
![image](https://cloud.githubusercontent.com/assets/6531354/14269042/5acd66d0-fb13-11e5-980b-2a8c560b574b.png)
