### ISSUE TITLE
希望支持Xcode7.0&iOS9&bitcode

### ISSUE THREAD

**Issue by JinChai** [jpush/jpush-phonegap-plugin#86]
ld: '/Users/nbc1/Documents/AFlex_weixin/platforms/ios/灵动校园/Plugins/cn.jpush.phonegap.JPushPlugin/libPushSDK-1.8.3.a(JPFTagAliasValidation.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

希望添加对ios9之后的bitcode的支持

**Comment by xifengzhu** [comment]
你可以在xcode build setting里面禁bitcode

**Comment by darkterrorooo** [comment]
@JinChai  @xifengzhu   现支持bitcode了，请关注最新版本
