### ISSUE TITLE
Badge怎么减1呢

### ISSUE THREAD

**Issue by pzhihao** [jpush/jpush-phonegap-plugin#87]

**Comment by darkterrorooo** [comment]
ios平台下，你可以在 Appdelegate中设置你要的数值

- (void)applicationDidEnterBackground:(UIApplication *)application {
 
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
  [application setApplicationIconBadgeNumber:0];
  [application cancelAllLocalNotifications];
}

**Comment by darkterrorooo** [comment]
1，通过 getApplicationIconBadgeNumber， setApplicationIconBadgeNumber 两个方法可管理本地Badge 值

2，同时通过 setBadge 把你要设置的值更新到后台。

**Comment by coolara** [comment]
getApplicationIconBadgeNumber 返回的data是 数字吗
