### ISSUE TITLE
不支持x86？

### ISSUE THREAD

**Issue by TonyLuo** [jpush/jpush-phonegap-plugin#90]
如题。希望能尽快支持不同的芯片。另外，这个项目好久都没更新了，不会是荒废了吧？
11-01 12:52:15.363: E/AndroidRuntime(2232): Process: com.test.mobile, PID: 2232
11-01 12:52:15.363: E/AndroidRuntime(2232): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.mobile-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libjpush175.so"
11-01 12:52:15.363: E/AndroidRuntime(2232): at java.lang.Runtime.loadLibrary(Runtime.java:366)
11-01 12:52:15.363: E/AndroidRuntime(2232): at java.lang.System.loadLibrary(System.java:989)
11-01 12:52:15.363: E/AndroidRuntime(2232): at cn.jpush.android.service.PushProtocol.(Unknown Source)
11-01 12:52:15.363: E/AndroidRuntime(2232): at cn.jpush.android.service.n.run(Unknown Source)
11-01 12:52:15.400: I/OpenGLRenderer(637): Initialized EGL, version 1.4
11-01 12:52:15.450: W/EGL_emulation(637): eglSurfaceAttrib not implemented
11-01 12:52:15.450: W/OpenGLRenderer(637): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa277a360, error=EGL_SUCCESS
11-01 12:52:16.003: I/Choreographer(637): Skipped 31 frames! The application may be doing too much work on its main thread.
11-01 12:52:44.750: D/NetworkMonitorNetworkAgentInfo WIFI () - null: Probably not a portal: exception java.net.SocketTimeoutException: failed to connect to clients3.google.com/74.125.23.138 (port 80) after 10000ms

**Comment by darkterrorooo** [comment]
你好，phonegap sdk 暂时没有带有android 的 库。如果需要，可到
http://docs.jpush.io/resources/
 下载 x86 sdk ，加入你的android 工程就可以了
