### ISSUE TITLE
希望支持ios9，xcode7

### ISSUE THREAD

**Issue by match08** [jpush/jpush-phonegap-plugin#91]
希望支持ios9，xcode7，在ios9上收不到消息。这些希望尽快升级。

**Comment by justintseng** [comment]
我就是用的ios9 xcode7，是支持的，你可能什么地方写错了，另外要改为http连接。
http://www.yelanxiaoyu.com/app/phonegap%E5%BC%80%E5%8F%91/phonegap-cordova%E6%8F%92%E4%BB%B6%E9%80%82%E9%85%8Dios9.html

**Comment by a81584944** [comment]
你好。原来IOS8的时候 貌似是 好的  但是现在ios9的时候 打开总是执行不了回调 想问下怎么回事  控制台报错

Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

**Comment by flashback313** [comment]
@justintseng 你能分享一下自己的操作过程么？我和楼主环境一样。发送消息之后 jpush 页面显示发送成功，但是手机没有收到推送。谢谢

**Comment by justintseng** [comment]
@flashback313 没什么特别的过程呀，你下载那个demo运行看看

**Comment by flashback313** [comment]
@justintseng 没改东西自己就好了，不过还是谢谢（不知道会不会是中间环节有什么审核之类的）

**Comment by tianhaiyang** [comment]
你好，我这边创建之后再iOS8.4上直接报错，9.0及以上就是可以的，请问是怎么回事？

**Comment by huangminlinux** [comment]
@tianhaiyang  报什么错误？
