### ISSUE TITLE
希望加入im功能

### ISSUE THREAD

**Issue by wierli** [jpush/jpush-phonegap-plugin#92]
希望加入im功能

**Comment by darkterrorooo** [comment]
这个可以有，可以说说你的具体需求吗

**Comment by WangJunru** [comment]
这个需求非常迫切，环信和融云都没有IM的plugin，cordova生态里，IM是可巨大痛点，希望jpush能成为第一个，可以先开放最简单的（文字和图片）

**Comment by darkterrorooo** [comment]
@WangJunru @wierli   你好。IM 功能已发布啦，欢迎关注：https://github.com/jpush/jmessage-phonegap-plugin
