### ISSUE TITLE
ios9，xcode7.1.1，编译出错

### ISSUE THREAD

**Issue by newhzh** [jpush/jpush-phonegap-plugin#93]
一开始bitcode出错，禁止之后此错误没了，但是爆出如下错误：
Undefined symbols for architecture arm64:
  "_deflateEnd", referenced from:
      _JPFGzip in libPushSDK-1.8.3.a(JPFUtilities.o)

后面类似的还有几个，怎么修正这个错误？望指教，多谢

**Comment by darkterrorooo** [comment]
你好，在工程中加上 libz.tdb （或 libz.a） 这个库

**Comment by newhzh** [comment]
@darkterrorooo ，非常感谢，不过我是不是还缺少几个库？我还有以下这些错误提示
Undefined symbols for architecture arm64:
  "_CNCopySupportedInterfaces", referenced from:
      _JPFMACAddress in libPushSDK-1.8.3.a(JPFUtilities.o)
      _JPFSSID in libPushSDK-1.8.3.a(JPFUtilities.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[JPFReachability connectionRequired] in libPushSDK-1.8.3.a(JPFReachability.o)
      -[JPFReachability currentReachabilityStatus] in libPushSDK-1.8.3.a(JPFReachability.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[JPFReachability reachabilityWithAddress:] in libPushSDK-1.8.3.a(JPFReachability.o)
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in libPushSDK-1.8.3.a(JPFUtilities.o)
  "_CNCopyCurrentNetworkInfo", referenced from:
      _JPFMACAddress in libPushSDK-1.8.3.a(JPFUtilities.o)
      _JPFSSID in libPushSDK-1.8.3.a(JPFUtilities.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[JPFReachability reachabilityWithHostName:] in libPushSDK-1.8.3.a(JPFReachability.o)
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[JPFReachability startNotifier] in libPushSDK-1.8.3.a(JPFReachability.o)
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[JPFReachability stopNotifier] in libPushSDK-1.8.3.a(JPFReachability.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[JPFReachability startNotifier] in libPushSDK-1.8.3.a(JPFReachability.o)

**Comment by newhzh** [comment]
@darkterrorooo ,感谢你的帮助，我现在已经加了另外的CoreTelephony.framework和SystemConfiguration.framework已经编译成功了。
