### ISSUE TITLE
addLocalNotification

### ISSUE THREAD

**Issue by xgzl87** [jpush/jpush-phonegap-plugin#95]
添加本地通知怎么没有反应啊

**Comment by darkterrorooo** [comment]
哪个平台

**Comment by xgzl87** [comment]
android，ios都不行

**Comment by lhw5123** [comment]
@xgzl87 Android 经过测试是可以添加本地通知的，或许是你的调用方法有问题？可以把具体的调用代码贴上来。

**Comment by xgzl87** [comment]
直接按照api文档写的， window.plugins.jPushPlugin.addLocalNotification(param.data.builderId,
                param.data.content,
                param.data.title,
                param.data.notificaitonID,
                param.data.broadcastTime,
                param.data.extras);

**Comment by lhw5123** [comment]
![5154af33-6a56-407c-8be0-4aa7df6de282](https://cloud.githubusercontent.com/assets/6531354/13596273/7dc1782a-e54c-11e5-838b-4876fcb23c70.png)
这样写是可以收到本地通知的，你对照看一下。

**Comment by xgzl87** [comment]
谢谢，等iOS版本出来再用它吧，要不然不统一。

**Comment by Yasashi** [comment]
你好，最新的版本已经添加了iOS本地推送的api，现在iOS和Android都支持本地推送了，亲可以更新版本使用哦。
