### ISSUE TITLE
Android平台点开通知之后再次直接打开应用也会触发 jpush.openNotification 事件

### ISSUE THREAD

**Issue by wangyuzju** [jpush/jpush-phonegap-plugin#99]
如题，如果不清除应用程序后台，而是按两次返回键退出程序（程序后台仍然在运行），再次打开应用时，依然会出发 jpush.openNotification 事件，只有杀死应用后台进程之后再进入程序才不会触发 jpush.openNotification 事件

**Comment by darkterrorooo** [comment]
你好：的确会有这个问题。
当这时样做是为了确保进程被kill后还能收到提示。所在加了一次通知。

如果你业务上有需求，你可以在 JPushPlugin 的 initialize 函数中，把以下代码注释掉

		 if(JPushPlugin.openNotificationAlert != null){
			 JPushPlugin.transmitOpen(JPushPlugin.openNotificationAlert, JPushPlugin.openNotificationExtras);
		 }
		 if(JPushPlugin.notificationAlert!=null){
			 JPushPlugin.transmitReceive(JPushPlugin.notificationAlert, JPushPlugin.notificationExtras);
		 }

**Comment by joblinan** [comment]
您好！我在JPushPlugin.java里的initialize中这一段代码注释掉后，从后台再次打开应用后，的确不会弹出旧消息了，但是，但app退出到后台的状态，点击通知栏的消息，无法弹出消息内容。。

**Comment by darkterrorooo** [comment]
O , you are right!   我马上更新一下代码

**Comment by joblinan** [comment]
@darkterrorooo 您好！这个问题已经解决了是嘛？需要我怎么做呢？删除原来的插件，然后重新下载安装？

**Comment by joblinan** [comment]
@darkterrorooo 您好！我已经下载更新了新版插件。之前的问题已经解决了。但当在这种场景时：
1）app处于运行状态时
2）接收到消息，从通知栏点击消息，可弹出显示；这时将app退出到后台
3）app从后台重新启动时，旧消息又弹出了。。

**Comment by darkterrorooo** [comment]
@joblinan  你好。我再修改了这个问题。并测试了想到的各种可能的组合。你再更新代码试试。

另外， 我发现原来的iOS, Android 上的jpush.receiveNotification，jpush.receiveNotification 的触发并不一致，请问你是如何处理的？

为了和ios 上的逻辑统一。修改逻辑如下：
1，从通知栏点开消息，才触发jpush.openNotification事件，这时不会触发 jpush.receiveNotification。因为jpush.openNotification中已带有消息内容了。
2，后台运行时，如果点应用打开，只收到jpush.receiveNotification。
3，在前台运行时，只收到jpush.receiveNotification。

**Comment by joblinan** [comment]
@darkterrorooo 您好。非常感谢您的技术支持：）。我已经更新了新版本。（我在JPushPlugin.js的openNotificationInAndroidCallback函数中加了alert）目前，当收到消息时，只有点击通知栏才弹出信息。而app不管是从后台还是运行状态，进入时都不会看到新消息（receiveMessageInAndroidCallback函数中加alert没有效果）。现在的逻辑和现象是这样的吗？
ps：我现在只开发了android系统，还没有用到ios

**Comment by darkterrorooo** [comment]
是的，openNotificationInAndroidCallback 就是从消息通知栏才弹出。其他情况下，会在 receiveNotificationInAndroidCallback 收到消息。（而不是receiveMessageInAndroidCallback）
